### ISSUE TITLE
Unit testing using subscription

### ISSUE THREAD

**Issue by mikefrancis** [laravel/cashier#168]
At present, there isn't a way to fake/mock a `User` so that `$user->subscribed()` is `true` in a testing environment, therefore meaning middleware has to be changed to ignore this when testing.

Is it possible to fake this data on a `User` so that subscription systems can be tested? For instance:

```
// This doesn't work but I'd imagine something along these lines...
$user = App\User::create([
    'first_name'    => $this->fake->firstName,
    'last_name'     => $this->fake->lastName,
    'email'         => $this->fake->email,
    'password'      => 'password',
    'stripe_plan'   => 'name_of_plan',
    'stripe_active' => 1
]);
$this->be($user);
```

I've got one in the works but am reluctant to merge this into my app's master branch until everything is properly tested.

Also having thought about this, this could also make seeding subscribed users a possibility.

**Comment by mikefrancis** [comment]
Well, after a couple of weeks of hacking around I still can't get this working and due to the lack of a response I'm going to assume it can't be done.

It's a shame as we're always being told to write tested code :cry:

**Comment by tim-peterson** [comment]
Hey @mikefrancis, I also just ran up against this issue. There is solidarity in your frustration. I'll let you know if I figure anything out.

**Comment by jeteon** [comment]
I suppose you might have to put some environment specific code into your application like:

```php
$subscribed = ($is_testing_env) ? true : $user->subscribed();
```

I've also just run into an issue where my application has been tested so far but now I need to integrate Cashier and it seems that might have to change.

**Comment by jeteon** [comment]
@mikefrancis on a second glance at your code, I think your issue might be that the Stripe billing fields aren't in the `$fillable` array for your `User` model so they are ignored when you use the `create()` method with an array.

I also believe you should be using the [Factory](https://laravel.com/docs/5.1/testing#model-factories) approach there which would set that field, even if its not in `$fillable`. If you don't want to do that, you can also make a call to `$user->setStripeIsActive(true)` just before `$this->be($user)`.

**Comment by mikefrancis** [comment]
@jeteon I have set the fillable fields in my User but still no dice - will give the `$user->setStripeIsActive(true)` a try though, assuming this bypasses Stripe?

**Comment by jeteon** [comment]
In a way, yes. What do you get if you execute `dd($user)` immediately after the `User::create()` call?

**Comment by mikefrancis** [comment]
I have since abandoned the project (it was 6 months ago) so I don't have any of this set up, but will try that and get back to you.

**Comment by jeteon** [comment]
Its cool. I thought you might have.

**Comment by crabmusket** [comment]
For any future Googlers who come across this issue: I've decided to 'mock' subscriptions during testing by adding an overridable method that actually creates subscriptions in my repository:

```php
protected function createSubscription(User $user, Team $team, string $plan, string $token, ?string $coupon): Subscription
{
    return $team->newSubscription(Team::PLAN_NAME, $plan)
        ->withCoupon($coupon)
        ->create($token, [
            'email' => $user->email,
            'description' => $team->name,
        ]);
}
```

Then in a mock class that inherits from the real repository, and it used during testing, I override the method like this:

```php
protected function createSubscription(User $user, Team $team, string $plan, string $token, ?string $coupon): Subscription
{
    return $team->subscriptions()->create([
        'name' => Team::PLAN_NAME,
        'stripe_id' => 'fake_id',
        'stripe_plan' => $plan,
        'quantity' => 1,
        'trial_ends_at' => null,
        'ends_at' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ]);
}
```

I'm not sure if this is correct, but it's working-ish for now.
