### ISSUE TITLE
Handling Failed Payments - Downgrade to Free Plan [Request]

### ISSUE THREAD

**Issue by pdanny** [laravel/cashier#170]
With respect to Handling Failed Payments. Could there be an option to downgrade to a free plan instead of outright canceling of the subscription?

**Comment by lostincode** [comment]
You can change how this is handled in your Stripe account settings. Stripe will send a webhook to your server (if setup) and you can handle this however you'd like. More information on the webhooks here:

http://laravel.com/docs/5.1/billing#handling-stripe-webhooks

**Comment by lostincode** [comment]
Here is a code example for the webhook

```php

    /**
     *
     * @param array $payload
     *
     * @return Response
     */
    protected function handleInvoicePaymentFailed(array $payload)
    {
         if ($this->tooManyFailedPayments($payload))
         {
             $billable = $this->getBillable($payload['data']['object']['customer']);

             if ($billable)
             {
                 $billable->stripe_active = false;
                 $billable->subscription_ends_at = $payload['data']['object']['ended_at'];
                 $billable->stripe_plan = 'Free';
                 $billable->save();
             }
       }

        return new Response('Webhook Handled', 200);
    }

```

**Comment by zslabs** [comment]
Wouldn't `$billable` just return the `stripe_id` and not the actual `User`? I would imagine you'd have to do something like:

    $user = User::where('stripe_id', $billable)->firstOrFail();

**Comment by lostincode** [comment]
@zslabs getBillable() returns a EloquentBillableRepository which has a find() method and returns your stripe model. :+1: 

```php
$this->app->bindShared('Laravel\Cashier\BillableRepositoryInterface', function () {
     return new EloquentBillableRepository;
});
```

**Comment by zslabs** [comment]
@lostincode Very cool! Appreciate the explanation on that. Been struggling with http://stackoverflow.com/questions/30955717/laravel-cashier-webhook-get-current-user/31064452 but think that tid-bit might get me off on the right foot.

**Comment by TheShiftExchange** [comment]
Actually - you should use the `handleCustomerSubscriptionDeleted` webhook - *not* the `handleInvoicePaymentFailed`.

The `handleCustomerSubscriptionDeleted` is only called when Stripe is cancelling the subscription (i.e. after 3 failed attempts).

Then you can just use that hook to set the customer as been on a free plan at that point. Like this:

```
protected function handleCustomerSubscriptionDeleted(array $payload)
    {
        $billable = $this->getBillable($payload['data']['object']['customer']);

        if ($billable && $billable->subscribed()) {
            $billable->subscription()->cancel();
        }

        // Now set customer on a free plan here

        return response('Webhook Handled', 200);
    }
```

**Comment by TheShiftExchange** [comment]
@pdanny - you should close this ticket. Using the code above we have a solution. Taylor is busy enough, so no need to bother him now.

**Comment by zofe** [comment]
@TheShiftExchange or someone can help, (I'm on 5.1,  stripe api 2015-10-16)

I'm trying to handle: customer.subscription.deleted so I'm overriding handleCustomerSubscriptionDeleted
but the method is never called..

I'm using 
`Route::post('/stripe/webhook', 'WebhookController@handleWebhook');`
```php
namespace App\Http\Controllers;

use App\Abbonamento;
use Symfony\Component\HttpFoundation\Response;
use Laravel\Cashier\WebhookController as BaseController;

class WebhookController extends BaseController
{

public function handleCustomerSubscriptionDeleted($payload)
    {
        $subscription = $payload['data']['object']['id'];
        $abbo = Abbonamento::bySubscription($subscription)->first();
        if ($abbo and $abbo->subscribed())
        {
            $abbo->subscription()->cancel();
        }
        
        return new Response('Webhook Handled', 200);
    }
}
```

note that I also  tried to handle "handleInvoicePaymentSucceeded"  and this is  called.
but any other method  I try  is never called.
