### ISSUE TITLE
Ability for user to have multiple subscriptions

### ISSUE THREAD

**Issue by andyjessop** [laravel/cashier#172]
Is it on the roadmap to implement multiple subscriptions to cashier? I have a situation where a user is subscribing one or more students to a plan, and it would be great to do this with cashier.

**Comment by lpil** [comment]
:+1:

**Comment by GavinCS** [comment]
you could make your students model billable, instead of the user table. and have a foreign key reference to the user in the student table. I have achieved this where one user subscribes multiple companies to a plan.

**Comment by minisoftgroup** [comment]
@GavinCS Please can you state how you exactly achieved this?

**Comment by themsaid** [comment]
@minisoftgroup 

>you could make your students model billable, instead of the user table. and have a foreign key reference to the user in the student table

This sounds like the best way to go.
