### ISSUE TITLE
[ request ] Allow to filter related models based on subscription status.

### ISSUE THREAD

**Issue by Kryptonit3** [laravel/cashier#175]
If you look at my post here - https://laracasts.com/discuss/channels/eloquent/global-query-scope-and-related-model-method

I am trying to only show `Jobs` that `belongTo` `User` where the `User` is `subscribed()`.

Is there a way we can add a special trait to related models that have a foreign key to user to only show records from users who `subscribed()` returns true for?

**Comment by fetch404** [comment]
I don't think you would need a foreign key.

```php
$jobs = Job::get();

$jobs = $jobs->filter(function(Job $item) {
       return $item->user->subscribed() == true;
});
```

**Comment by Kryptonit3** [comment]
@fetch404 but then you loose the ease of pagination with the database query. - I ended up using a global query scope - [here's how](https://laracasts.com/discuss/channels/eloquent/need-help-writing-remove-for-global-query-scope)

**Comment by themsaid** [comment]
I imagine this can be done using the query builder, or maybe join statements.
