### ISSUE TITLE
invoices takes 16 seconds

### ISSUE THREAD

**Issue by cweaver** [laravel/cashier#177]
when calling $user->invoices() it takes 16 to complete

**Comment by GrahamCampbell** [comment]
That's probably intended.

**Comment by cweaver** [comment]
why would it be intended? is this just because i'm in test mode?

**Comment by GrahamCampbell** [comment]
You didn't say you were in test mode.

**Comment by cweaver** [comment]
is that the cause?

**Comment by taylorotwell** [comment]
Errr.... it definitely wouldn't be intended @GrahamCampbell. 16 seconds?

It could be a factor of network latency to pull the invoice, some kind of slowness generating the PDF, etc.

**Comment by GrahamCampbell** [comment]
I'd say that's expected for a slow server?

**Comment by phleobon** [comment]
Couldn't we put some kind of caching system for the invoices ?

**Comment by Steingate** [comment]
Sure you can, but don't forget to clear the cache when a new invoice is created
