### ISSUE TITLE
Can't pass a timestamp of trial end to Stripe

### ISSUE THREAD

**Issue by tonystatic** [laravel/cashier#185]
I'm trying to create a subscription for registered user. He has a trial period in application, while all the subscription plans don't have one. Is it possible to pass the trial end date (*trial_ends_at* field) to Stripe, when creating first subscription?

Stripe API reference on [creating a new subscription](https://stripe.com/docs/api#create_subscription) says, that the parameter *trial_end* can be passed in this case. Also Laravel Cashier docs say, that:
> If you would like to specify additional customer details, you may do so by passing them as second argument to the create method (...) To learn more about the additional fields supported by Stripe...

I tried to do so in my code..
```php
$user->subscription($plan)->create($creditCardToken, [
    'email' => $user->email, 
    'description' => $user->name,
    'trial_end' => $user->trial_ends_at->timestamp
]);
```
..but I got the InvalidRequest Exception (Received unknown parameter: trial_end).

Is it possible now? And if it is, what am I doing wrong?

Thanks in advance!

**Comment by Thatplayer** [comment]
The "additional customer details" would be what you are passing when you are creating the original stripe customer, not the subscription.

Not in the docs for some reason, but you can do:


```
$user->subscription($plan)->trialFor($user->trial_ends_at)->create($creditCardToken, [
    'email' => $user->email, 
    'description' => $user->name
]);
```

**Comment by tonystatic** [comment]
Thank you! 
It worked perfectly.

**Comment by marcelgruber** [comment]
@Thatplayer 

Dude, WHAT. This is the most obscure post ever and it solves ALL my problems with trial dates and creating subscriptions... That should REALLY be in the documentation.

**Comment by anchetaWern** [comment]
This doesn't work on laravel 5.2. I'm using the following code and I'm getting trialFor not defined.

```
auth()->user()
			->subscription($subscription_name)
			->trialFor('now') // I want to end the trial immediately for customers who don't want to trial
			->create($token);
```

**Comment by enkay** [comment]
How do we do this in 5.3?
