### ISSUE TITLE
Bitcoin Issue

### ISSUE THREAD

**Issue by fgambino** [laravel/cashier#186]
When paying with bitcoin, StripeGateway fails on updateLocalStripeData with

```
setLastFourCardDigits($this->getLastFourCardDigits($customer))
```

Commenting that out seems to work fine.

**Comment by GrahamCampbell** [comment]
Cashier doesn't support bitcoin.

**Comment by Cheater912** [comment]
Ah okay. Well, other than the last 4 not being there, I don't think there's a difference. You should consider adding support for it!

**Comment by GrahamCampbell** [comment]
Yeh, I'm not saying it shouldn't be supported, I'm just saying it's not advertised as officially supported. :)

**Comment by Cheater912** [comment]
Maybe I'll create a pull request then. Thanks!

**Comment by ChadTaljaardt** [comment]
any update?

**Comment by themsaid** [comment]
@ChadTaljaardt no plans for this at the moment.

**Comment by devboxr** [comment]
It's been over 2 years since this issue was opened and cryptocurrencies are bigger than ever. Any chance we could see Bitcoin support in Cashier (and Spark, for that matter) now?

**Comment by OscarEriksen** [comment]
It's been the snowball effect. Cryptocurrencies, not only Bitcoin but also altcoins such as EOS, Ethereum and so on have been getting a momentum. Time to enable coins - in some way atleast.
