### ISSUE TITLE
Deprecated: Automatically populating $HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by JTallis** [laravel/cashier#196]
This is the response that stripe receives when handling the webhook:

    <br />
    <b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />

It's a helpless message by all means. I have no idea where it could come from. There is nothing obvious in the handling of the webhook that could cause such a thing. It may not even be directly related to cashier... but it's coming from somewhere. PHP 5.6.8 + PHP 5.6.11

**Comment by JTallis** [comment]
It's related to PHP rather than Laravel. `always_populate_raw_post_data = -1` needs to be in php.ini and the error won't pop up no more. The default value is 0 so despite it being a deprecated feature, by default it is still being used. It's a bit silly to say the least but that solves the issue anyway. My apologies for not doing my research prior to opening an issue.

**Comment by swapnil-chaudhari-1811** [comment]
I am using Laravel 5.4 with PHP7, so there is no always_populate_raw_post_data in php.ini, still i am getting deprecated error, anyone help me out?

**Comment by kaushik1994** [comment]
Please use **Content-Type = application/x-www-form-urlencoded**  To solve this issue. :100:

**Comment by Vikas0109** [comment]
where i use " Content-Type = application/x-www-form-urlencoded"
