### ISSUE TITLE
[Proposal] Upgrade to Stripe PHP 3.2

### ISSUE THREAD

**Issue by JTallis** [laravel/cashier#197]
Stripe PHP 3.2 has had mostly minor changes since 2.3 but it has had some bug fixes and some feature additions. I've gone through all the files of 3.2 and compared with 2.3 (minus tests).

These are the current changes:

Deletion of accounts has been made possible inside `Account.php` using `Account->delete`.
Disputes have been given more support which includes the addition of `Dispute.php` and an array addition to `Util\Util::convertStripeObjectToArray`.
A couple of deprecations were made in `Charge.php`, specifically `updateDispute` and `closeDispute`.
Renaming of `Object.php` to `StripeObject.php` and the added implementation of JsonSerializable and `JsonSerializable.php` including a bug fix that is present in 2.3 where a null value was returned instead of a variable reference.
Removal of `Refund->instanceUrl` inside `Refund.php` and the addition of `Refund::Retrieve`, `Refund::all` and `Refund::create`
Of course, `init.php` was changed to reflect any file changes.

All are relatively minor changes and ~95% of the API remains the same. I feel as if this would be a beneficial upgrade especially for the added support of disputes and account deletion.

**Comment by taylorotwell** [comment]
Do you know if any of this effects anything in the current Cashier library? None of it off hand seems to really apply.

**Comment by joyfulrodger** [comment]
Hi Taylor, 

Just wanted to chime in here as it appears that when I try to update the Stripe PHP api via composer I am receiving the following feedback:

Problem 1
    - laravel/cashier v5.0.10 requires stripe/stripe-php ~2.0 -> no matching package found.
    - laravel/cashier v5.0.10 requires stripe/stripe-php ~2.0 -> no matching package found.
    - laravel/cashier v5.0.10 requires stripe/stripe-php ~2.0 -> no matching package found.
    - Installation request for laravel/cashier == 5.0.10.0 -> satisfiable by laravel/cashier[v5.0.10].


I'm no composer expert so there may be a way to get around this but I'm just letting you know as I'm trying to use the Refund::create function so need to upgrade the API regardless.

**Comment by taylorotwell** [comment]
I've updated it to Stripe 3.0.

**Comment by joyfulrodger** [comment]
Thanks for that.

Much appreciated
