### ISSUE TITLE
Any plans for adding convenience methods to access customer cards?

### ISSUE THREAD

**Issue by bogdanghervan** [laravel/cashier#199]
Just like we can now deal with invoices for a user implementing the `Billable` contract:

``` php
$user->invoices()
$user->downloadInvoice()
```

We could additionally manage their cards:

``` php
$user->cards()
$user->deleteCard()
```

**Comment by S3D-Jake** [comment]
+1

**Comment by themsaid** [comment]
PR created https://github.com/laravel/cashier/pull/357
