### ISSUE TITLE
[feature request] add stripe-connect's managed accounts

### ISSUE THREAD

**Issue by Evertt** [laravel/cashier#202]
It would be nice to be able to use stripe's new managed accounts via a sweet cashier syntax. So you can build market-places where users can get money from other users. So something like:

``` php
// this methods transfers the money directly between the users
$user1->pay($amount)->to($user2)->create($token);

// this method transfers the money via the platform's stripe account
$user1->pay($amount)->viaUs()->to($user2)->create($token);

// and of course for subscriptions we could do something like
$user1->subscription('monthly')->to($user2)->create($token);
```

[reference](https://stripe.com/docs/connect/payments-fees)

**Comment by commandantp** [comment]
+1
@Evertt did you do something yourself in the meantime?

**Comment by cjke** [comment]
+1 
Also curious if you tackled this outside of the laravel/cashier library

**Comment by Evertt** [comment]
Nope :-$

**Comment by commandantp** [comment]
Looks like I will install the package but just use the Stripe package straight. 
First there is no support for other currencies than USD in Cashier right now. 
This function would be re-workable by passing through directly the currency in the options as well as the other things needed to make it work (see further down).
````
    public function charge($amount, array $options = [])
    {
        $options = array_merge([
            'currency' => $this->getCurrency(),
        ], $options);
        $options['amount'] = $amount;
        if (! array_key_exists('source', $options) && $this->billable->hasStripeId()) {
            $options['customer'] = $this->billable->getStripeId();
        }
        if (! array_key_exists('source', $options) && ! array_key_exists('customer', $options)) {
            throw new InvalidArgumentException('No payment source provided.');
        }
        try {
            $response = StripeCharge::create($options);
        } catch (StripeErrorCard $e) {
            return false;
        }
        return $response;
    }
````

For Stripe to charge via Connect this is an example of what has to be called: 
````
// Get the credit card details submitted by the form
$token = $_POST['stripeToken'];

// Create the charge on Stripe's servers - this will charge the user's card
$charge = \Stripe\Charge::create(
  array(
    "amount" => 1000, // amount in cents
    "currency" => "usd",
    "source" => $token,
    "description" => "Example charge",
    "application_fee" => 123 // amount in cents
  ),
  array("stripe_account" => CONNECTED_STRIPE_ACCOUNT_ID)
);
````

Would just need a bit more flexibility in Cashier and it would work.

**Comment by commandantp** [comment]
still no-one worked on it? Will I be the first?... *sight* :)

**Comment by cjke** [comment]
Our current library is using the Stripe library directly. We've added a very lightweight decorator around it to speed up our use cases, but it's actually very good

**Comment by feeekkk** [comment]
+1

**Comment by jaoued** [comment]
:+1:

**Comment by SunChero** [comment]
would be nice to have this !!

**Comment by rocketvalley** [comment]
+1 for an update to Cashier ... as well as Stripe Connect integration

**Comment by vool** [comment]
+1

**Comment by lem93** [comment]
+1

**Comment by mlantz** [comment]
This is relative to #406

**Comment by kiwo12345** [comment]
+1

**Comment by pihlersimon** [comment]
+1

**Comment by simonezando** [comment]
+1

**Comment by mangrovestudios** [comment]
+1

**Comment by rocketvalley** [comment]
+1

**Comment by Hesesses** [comment]
+1

**Comment by MACscr** [comment]
Still no luck? Seems its been requested for almost 3 years now. Would really be useful for me as well.

**Comment by driesvints** [comment]
The PR for Stripe Connect functionality was rejected so closing this because atm we have no plans of supporting it.
