### ISSUE TITLE
[Request] Save card brand

### ISSUE THREAD

**Issue by DougSisk** [laravel/cashier#218]
We often use the card brand in our apps. Example: Visa ending in 4242. Currently the brand is not saved to the database and we have to call the Stripe API to get it which can be awfully slow. It would be super useful for us if Cashier saved the brand to the database out of the box.

**Comment by vlakoff** [comment]
Looks like this has been implemented in Cashier 6.0, see [Billable::updateCard](https://github.com/laravel/cashier/blob/6.0/src/Billable.php).
