### ISSUE TITLE
Re: Can I charge my customers different amounts every billing period (e.g. metered billing based on usage)?

### ISSUE THREAD

**Issue by rdev5** [laravel/cashier#231]
Please see the following links:
- [Can I charge my customers different amounts every billing period (e.g. metered billing based on usage)?](https://support.stripe.com/questions/metered-subscription-billing)
- [When is an invoice open for modification?](https://support.stripe.com/questions/when-is-an-invoice-open-for-modification)

Is this something you guys plan on supporting anytime soon in [Laravel Cashier](http://laravel.com/docs/5.1/billing)? Seems the documentation only covers predefined subscriptions and one-time charges.

Thanks!

**Comment by colin-stannard** [comment]
I would find this REALLY useful.

**Comment by danharper** [comment]
You can do this by listening for Stripe's `invoice.created` [webhook](https://stripe.com/docs/api#event_types).

> Occurs whenever a new invoice is created. If you are using webhooks, Stripe will wait one hour after they have all succeeded to attempt to pay the invoice; the only exception here is on the first invoice, which gets created and paid immediately when you subscribe a customer to a plan. If your webhooks do not all respond successfully, Stripe will continue retrying the webhooks every hour and will not attempt to pay the invoice. After 3 days, Stripe will attempt to pay the invoice regardless of whether or not your webhooks have succeeded. See how to respond to a webhook.

So Stripe lets you know an hour before they pay an invoice, giving your code one hour to update the invoice with any additional charges (i.e. calculate their "usage" and add an invoice item for it).

**Comment by colin-stannard** [comment]
Awesome, that sounds like exactly the thing. I'll have a go!

I'll post some code when I get it working. I think it would be nice to have this built into cashier.

**Comment by JoshuaDoshua** [comment]
This seems like something you may be able to handle with the "quantity" value?
