### ISSUE TITLE
Customer is being created even when initial charge fails

### ISSUE THREAD

**Issue by mirzabusatlic** [laravel/cashier#234]
There's a case where Stripe customers are created even when the initial charge on a credit card fails. Try testing with the card number `4000000000000341` which is `Attaching this card to a Customer object will succeed, but attempts to charge the customer will fail.`, according to the Stripe docs (https://stripe.com/docs/testing).

This results in the duplication of Stripe customers, and Stripe customers that aren't tracked in the database.

The fix involves passing the `plan` to the Stripe customer creation (which isn't being currently done), like so:

``` php
$stripeCustomer = Stripe_Customer::create([
    'card'     => $token,
    'plan'     => 'your_monthly_plan',
]);
```

I did a workaround and used this as a solution, but I'm not sure to how properly integrate it into Cashier itself which is why I didn't do a pull request.

**Comment by kyranb** [comment]
:+1: Thanks for the the fix - Seems to work and solve the same problem I've been having.

**Comment by kyranb** [comment]
Just an update on this, what I'm seeing is that the original failed invoice remains on the account, so that when they do enter a valid credit card they are charged for two invoices.
