### ISSUE TITLE
How do we handle errors returned from the charge method?

### ISSUE THREAD

**Issue by stueynet** [laravel/cashier#239]
You catch card errors here: https://github.com/laravel/cashier/blob/5.0/src/Laravel/Cashier/StripeGateway.php#L115 and return false. How do we handle the errors from within our application?

**Comment by commandantp** [comment]
+1

**Comment by Kryptonit3** [comment]
in your method where you charge the user, you would check for `false` response like this.
```
$charge = $user->charge(100);

if ( ! $charge) {
    // The charge was denied...
}
```

If the charge is successful, the full Stripe response will be returned in the above example on the `$charge` variable.

https://laravel.com/docs/5.2/billing#single-charges
