### ISSUE TITLE
Unable to upgrade to Laravel 5.2 with Cashier ~5.0

### ISSUE THREAD

**Issue by mirzabusatlic** [laravel/cashier#240]

**Comment by GrahamCampbell** [comment]
Yes, you need to use cashier 6.

**Comment by xKairu** [comment]
Well, yes obviously we would need to use Cashier 6, but the database structure between 5 and 6 is completely different. How are we supposed to reliably migrate existing data?

Taylor said on reddit that he'd want an Artisan command to do just that. Seems strange to have such a drastic, breaking change with zero documentation.

**Comment by GrahamCampbell** [comment]
Not sure. Stick on L5.1 for now I guess. It's LTS for this reason, among others.

Ping @taylorotwell regarding the status of getting an easy migration between major versions setup.

**Comment by taylorotwell** [comment]
Why won't Cashier 5.0 install on 5.2?

**Comment by jaewun** [comment]
@taylorotwell because it uses bindShared in its register method.
