### ISSUE TITLE
Laravel Cashier 6.0 - No Card Up Front?

### ISSUE THREAD

**Issue by ajs87** [laravel/cashier#250]
I'm confused with how to create a no card up front subscription with the new Cashier.

In the older versions, (see L4.2/L5.0 docs) there was a nicely described No Card Up Front section.
That's now been deprecated but doesn't seem to have been replaced by anything.

Can someone please clarrify how you go about implementing a free trial without card details?
Thanks
Alex

**Comment by dsshafer** [comment]
I just ran into the same thing. As far as I can tell, the current philosophy is to move no-card trials into your application code, and Cashier/Stripe doesn't get involved until the user enters a credit card. So you might add a "trial_ends_at" column on your billable model table (usually "users"), then an onTrial() method on the model (usually User).

**Comment by ajs87** [comment]
okay, I was wondering if that was it... it just seems like a step backwards!
 
So how does this work with Stripe trials? 

For example, if I set the plan to have 14 day trial, which we "self manage" with trial_ends_at.  User enters their card details on day 14 of that trial which we handle with Cashier.  Now this is the first that Stripe knows about it this customer, so it applies the 14 day trial again... and the customer will end up with a 28 day trial...

Am I doing something stupid?

**Comment by dsshafer** [comment]
Stripe trials and your app's pre-card trials are completely separate. The trial period you see in Stripe refers to the time after a user enters their credit card, but before the card is charged. (And the "trial_ends_at" column in the subscriptions table is used for Stripe trials, so don't try to use that for your pre-card trial. You'll need your own column, probably on the users table.)

The flow might look like this:

User registers --> optional free pre-card trial (managed by app) --> user subscribes and enters credit card --> optional free trial (managed by Stripe) --> Stripe charges for subscription

**Comment by ajs87** [comment]
Thank you! 
This clarifies things tremendously. 

So actually, there's no such thing as a "Pre-Card Stripe Trial".
Stripe Trials always require a card and adding one on your stripe plans will simply double up on your freebies. 

The Laravel docs really didn't help me here, with the old styple "cardUpFront" variable.

I'll mark this as closed.  Thanks again.

**Comment by jeteon** [comment]
The [documentation](https://stripe.com/docs/guides/subscriptions#working-with-trials) for Stripe's subscriptions with trials states that:
 
> Unlike plans that require immediate payment, you can subscribe a customer to a plan with a trial period without providing a payment method.

So this statement is untrue:

> So actually, there's no such thing as a "Pre-Card Stripe Trial".

except in the context of this particular package. In fact, Stripe will even send you a `customer.subscription.trial_will_end` webhook when the trial period you've specified is about to end so they do actually help you manage that free lead-up period explicitly within their system.

**Comment by ajs87** [comment]
Amazing, thanks for clarifying that. I'll have to look into this a bit more to make sure I deal with it properly.

**Comment by tylercubell** [comment]
> If you would like to offer trial periods without collecting the user's payment method information up front, you may simply set the trial_ends_at column on the user record to your desired trial ending date. This is typically done during user registration:

```php
$user = User::create([
    // Populate other user properties...
    'trial_ends_at' => Carbon::now()->addDays(10),
]);
```

https://laravel.com/docs/5.3/billing#without-credit-card-up-front

**Comment by jeteon** [comment]
Its cool to see that they officially support this use case now :slightly_smiling_face:.
