### ISSUE TITLE
Laravel Cashier 6.0 - subscriptions table

### ISSUE THREAD

**Issue by ajs87** [laravel/cashier#254]
Hi all, 
Running L5.2 with Cashier 6.0,

Copied and ran the migrations.
When calling Cashier methods to change a customer's stripe plan, this is the result:

Stripe Plan changes + event fires to webhook = Great
subscriptions->stripe_plan updated on the table = Great
subscriptions->name is NOT updated on the table... = is this right?

My understanding is that this subscriptions table should be kept in sync with the Stripe details through Cashier.  Have I got something wrong?  Do I need to manually update some of these fields, and if so, which ones do sync and which ones don't?

**Comment by mgustafsson1** [comment]
@ajs87 I think subscriptions.name is an "internal" value, i.e. not related to Stripe. If you change the Stripe plan, the subscriptions.stripe_plan column is updated with the name of the new plan.

The documentation for Cashier suggests to use "main" or "primary" for that name field.

**Comment by ajs87** [comment]
Thanks @mgustafsson1.  I think I've got a handle on this now.  The Cashier documentation wasn't all that clear to be honest, and certainly caused me confusion.  I think it could do with explaining which fields are kept updated and which you are required to update yourself.  Thanks again.  I'll mark this as closed :+1:

**Comment by mgustafsson1** [comment]
@ajs87 No worries! To be honest, I'm not 100% sure what the name field actually does, but I'm guessing it's used when you have multiple products/subscriptions that the user can buy/subscribe to.
