### ISSUE TITLE
trial_ends_at not getting set

### ISSUE THREAD

**Issue by thecodedad** [laravel/cashier#256]
The snippet of code below in SubscriptionBuilder.php is returning NULL every time I create a subscription for a user. I don't believe $this->trialDays is every getting set. 

```
 'trial_ends_at' => $this->trialDays ? Carbon::now()->addDays($this->trialDays) : null,
```

**Comment by thehamr** [comment]
My additions to get it working....

    /**
     * Format the received trial end if it's not null.
     * 
     * @param $trial_end
     * @return static
     */
    public function formatTrialEnd( $trial_end )
    {
        if( ! is_null( $trial_end ) )
        {
            $date = new Carbon;
            $trial_end = $date->timestamp( $trial_end );
        }

        return $trial_end;
    }

and I changed the line originally mentioned to the following...

    'trial_ends_at' => $this->formatTrialEnd($subscription->trial_end),

**Comment by ChristianGiupponi** [comment]
Same for me, not event `ends_at` has been set after the subscription

**Comment by nathanjdunn** [comment]
+1 for this bug, I've set my trial day numbers in Stripe and it isn't pulling through the date...

**Comment by ChristianGiupponi** [comment]
@nathanjdunn you need to set the trial days with:

    trialDays(14)

when you create the subscription.

**Comment by thehamr** [comment]
@christiangiupponi - the number of trial days is supposed to be set automatically based on the defines trial within stripe when the subscription is created in laravel ( per the documentation )

**Comment by thehamr** [comment]
Plus I think it would be silly to not only have to set the trial in the stripe dashboard, but then also your code.

**Comment by nathanjdunn** [comment]
@thehamr is right, it'd be strange for it not to make use of the inbuilt features of Stripe...

**Comment by ajs87** [comment]
I had exactly this problem about a month ago.  It caused a lot of confusion at the time.
Here's the thread I opened, the feedback I got clarified things for me.
https://github.com/laravel/cashier/issues/250

**Comment by thehamr** [comment]
I don't really think the explanations in #250 are the way it's supposed to be functioning / used. If you look at the documentation on Laravel, this is what it states:

> The create method will automatically create the Stripe subscription, as well as update your database with Stripe customer ID and other relevant billing information. If your plan has a trial configured in Stripe, the trial end date will also automatically be set on the user record.

That's a pretty straightforward explanation to me. If Stripe has a trial end date set, Cashier should automatically update the subscriptions trial_ends_at field.

**Comment by ajs87** [comment]
Indeed.  The docs certainly suggest that trial end date should be set automatically, so I agree that there is a bug.

**Comment by themsaid** [comment]
That's no longer the case, docs has changed. Closing then.

**Comment by thecodedad** [comment]
What has changed? Should we no longer expect the trial_end field to be set automatically by Cashier? A little more information in regards to this would be helpful.
