### ISSUE TITLE
[Request] Use facades instead of raw Stripe classes

### ISSUE THREAD

**Issue by jeteon** [laravel/cashier#257]
I've recently integrated the Cashier package into a project I'm working on and testing has become somewhat more complicated and constrained since. A lot of this is due to the fact that a test that involves the billing system and the user model will make actual calls to the Stripe API. Whilst this is okay for integration tests, it really slows down unit tests. 

I suggest that instead of using the raw Stripe classes from the the Stripe package that instead facades be created and that those be used instead. The facades don't really have to do much other than pass on function calls but will allow for mocking using existing Laravel testing aids which will make testing much easier.

**Comment by themsaid** [comment]
No plans for this at the moment.
