### ISSUE TITLE
Ability for pagination

### ISSUE THREAD

**Issue by lstables** [laravel/cashier#263]
When using the following.

```
<table>
    @foreach ($invoices as $invoice)
        <tr>
            <td>{{ $invoice->dateString() }}</td>
            <td>{{ $invoice->dollars() }}</td>
            <td><a href="/user/invoice/{{ $invoice->id }}">Download</a></td>
        </tr>
    @endforeach
</table>
```

As per the docs, how does one get it paginate?

cc @taylorotwell

**Comment by lstables** [comment]
Any advice on this or or to achieve this?

**Comment by Kryptonit3** [comment]
I was looking for info on the same thing a while back. never got anywhere with it

https://laracasts.com/discuss/channels/general-discussion/how-do-you-paginate-a-users-stripe-invoices?page=1

**Comment by Mr-Anonymous** [comment]
It appears the `$user->invoices()` method still has a limit of 10 invoices. Is there a solution yet to list or paginate more than 10 invoices?

**Comment by themsaid** [comment]
You can paginate by passing parameters as the second argument of `invoices()`, see https://stripe.com/docs/api/php#list_invoices

use `limit` and `starting_after`

**Comment by Kryptonit3** [comment]
How hard would it be to have a method built in by default to utilize this feature? @themsaid

**Comment by themsaid** [comment]
Not sure really :) feel free to open a PR though @Kryptonit3

**Comment by Mr-Anonymous** [comment]
Perfect! Thank you for that @themsaid 

I was able to add the invoice pagination using your help. I now show paginated invoices like this:
```
$settings = array('limit' => 12, 'starting_after' => $postData['id']); 
$invoices = $user->invoicesIncludingPending($settings);
```       
Where `$postData['id']` is sent from front-end as a marker which is then used for `starting_after`.
       
Thank you for your help. I was stuck on this for a very long time.
