### ISSUE TITLE
[Request] Add method to delete card

### ISSUE THREAD

**Issue by vlakoff** [laravel/cashier#281]
Please, could you consider adding to the [`Billable`](https://github.com/laravel/cashier/blob/6.0/src/Billable.php) class a `deleteCard` method?

Nowadays it is possible to delete all cards of a given customer, see this [blog post](https://stripe.com/blog/multiple-cards) and the [relevant API](https://stripe.com/docs/api#delete_card).

I'm being frustrated by the amount of websites based on Stripe which don't let deleting the card, despite this being such a fundamental requirement IMO.

You can have an influence on this, just by adding this class method. Thank you in advance.

**Comment by themsaid** [comment]
PR created https://github.com/laravel/cashier/pull/357

**Comment by realripley00** [comment]
I wasn't able to get this to work with deleteCard().  I looked at the cashier git and apparently it's actually getCards().  So if you're having trouble getting this to work try getCards() with an s instead of getCard().

**Comment by vlakoff** [comment]
Thanks for pointing this out. Indeed, Taylor renamed the method from `deleteCard()` to `deleteCards()` in a subsequent [commit](https://github.com/laravel/cashier/commit/15349411a8098b2242de1ebbbea8d350079e6574).

**Comment by rslay** [comment]
There is currently no mention of the `deleteCards()` method, nor any way to delete customers from Stripe's/Braintree's in the docs (https://laravel.com/docs/5.7/billing).

@themsaid, can this be added?

**Comment by tallcoder** [comment]
I don't feel like this should be closed. While, yes, there's a method for deleting all cards. There's no method for deleting a specific card.

**Comment by driesvints** [comment]
@tallcoder yes there is: https://laravel.com/docs/6.x/billing#deleting-payment-methods

**Comment by driesvints** [comment]
You also have `removePaymentMethod` on the billable entity

**Comment by sazibuddin** [comment]
deletePaymentMethods() is deleting all the cards from stripe. 
So I want to delete a specific card from many cards. How it can be? 

I see there have $paymentMethod->delete(); function. what it expect as $paymentMethod here ?

**Comment by driesvints** [comment]
@sazibuddin you can delete a specific payment method with:

```php
$user->removePaymentMethod($id);
```

**Comment by sazibuddin** [comment]
@driesvints, Thanks for your reply. But I struggle that what the function expects as an id? 
Can you please tell me about that?

**Comment by driesvints** [comment]
The payment method ID or a payment method object.

**Comment by sazibuddin** [comment]
@driesvints, I just tried and it works like a champ. Thank you very much. you make my day.

**Comment by driesvints** [comment]
I saw this wasn't documented yet so I sent in a PR for it to the docs: https://github.com/laravel/docs/pull/7559
