### ISSUE TITLE
Billable->updateCard doesn't delete old card

### ISSUE THREAD

**Issue by eliassorensen** [laravel/cashier#282]
When calling updateCard, it correctly adds the new token to the object's attached Stripe customer (and sets it as default).

However, it doesn't delete the old card on the Stripe customer. This results in many cards that Cashier doesn't know exist, because it only has a reference to the newest card in card_brand / card_last_four.

This is unexpected behavior for **update**Card.

This could be implemented together with deleteCard (as requested in #281).

In the future, there could be a need for Cashier to support multiple cards, but it would deprecate updateCard, and instead introduce methods like:
- addCard
- removeCard
- cards
- setDefaultCard

**Comment by DannyFeliz** [comment]
This would be great +1

**Comment by MichaelHoughton** [comment]
@eliassorensen - if you are still looking for this functionality, I have implemented it at:
https://github.com/coderity/wallet

It extends Cashier and adds additional methods - almost exactly as you specified above.

**Comment by driesvints** [comment]
Atm all of this functionality is already available:

- addCard --> `updateCard` on `Billable`
- removeCard --> `delete` on `Card`
- cards --> on `Billable`
- setDefaultCard --> `updateCard` on `Billable`

**Comment by rslay** [comment]
I would be helpful for people looking for a way to delete cards to know that the method for that is `deleteCards()`, for example:
```
$user->deleteCards()
```
removes a card from a user in both the database and on their Stripe customer (not sure about braintree).

I'd like to reference my request for documentation over on issue #281, it seems relevant and I found both of these issue threads searching for a way to do it myself.

**Comment by driesvints** [comment]
I'll send in a PR to the docs for this.

**Comment by driesvints** [comment]
Here it is: https://github.com/laravel/docs/pull/4854
