### ISSUE TITLE
Anchor Billing Cycle API error

### ISSUE THREAD

**Issue by Francismori7** [laravel/cashier#300]
Say someone needs to have all subscriptions anchored on the first of the month rather than the anniversary date, this would be a useful option, but it seems to not work.

Giving out an API parameter unknown error.

**Comment by themsaid** [comment]
@Francismori7  can you please share more details? I don't seem to understand.

**Comment by Francismori7** [comment]
Give me a few hours.

**Comment by themsaid** [comment]
@Francismori7 have you managed to check the issue again?

**Comment by Francismori7** [comment]
Oh wow I completely forgot about this. Tonight I should be able to provide details. *Notes in agenda*

**Comment by themsaid** [comment]
@Francismori7 open another issue when you have time then :)
