### ISSUE TITLE
data missing for mssql

### ISSUE THREAD

**Issue by finalight** [laravel/cashier#306]
using microsoft sql as the database, the error "data missing" will appear

this is because of the milliseconds that the database contains. however upon retrieval, the model doesn't seems to be able to retrieve the milliseconds and yet, Carbon will attempt to assume that there's milliseconds involved and thus the conversion fails.

**Comment by themsaid** [comment]
@finalight can you please provide more details? Can't you alter the storage column type to the default Eloquent dat-time format?

**Comment by themsaid** [comment]
Closing this, let's continue on the other issue: https://github.com/laravel/cashier/issues/315
