### ISSUE TITLE
Using both Braintree and Stripe

### ISSUE THREAD

**Issue by sakalauskas** [laravel/cashier#308]
Hello,

I was using Stripe to allow billing for my "Visitor" model, however I want to add Braintree billing to "User" model, but the namespaces are both the same in laravel/cashier and laravel/cashier-braintree so I can't load seperate traits, etc.

Is it anyway possible to do this without forking the repository?

Thank you,

**Comment by mlantz** [comment]
The two are very different and require completely different db setups so I'm pretty sure you wont be able to toggle so nicely

**Comment by sakalauskas** [comment]
Yep, 

I am aware of that,  but I am using them on different models, so I don't need to switch. 

**Visitor** model will always be billed with Stripe
**User** model will always be billed with Braintree.

Those are two independant to each other, but they are in the same application.

However, as far as I see I can only use one implementation of Cashier, which is sad...

**Comment by mlantz** [comment]
Yeah I suppose the namespaces would conflict... You could micro-service the Vistor one into a separate API based app, which would allow it to remain separate making more control for your app :)

**Comment by sdbruder** [comment]
"completely different" db setups? 
you mean stripe_id and braintree_id ? the only field really different is paypal_email that stripe does not have. the rest is a simple case of renaming everything to 'gateway_id' or something like that.

**Comment by mlantz** [comment]
I simply meant that since the tables have those key columns names name differently you would have to have separate tables etc. Since the Subscription Model wont let you name the table it accesses (which it would be cool if it did) there is a fundamental block in using them together in the same app. Unless you migrate one into a micro-service, or better yet, move both into micro-services which handle all your billing for a single user group base. (just a thought)

**Comment by sakalauskas** [comment]
Thanks for your comments,

These are two separate tables for those two models.

Didn't realised that I was using Cashier version 5 for Visitor model where there no subscriptions table. Which complicates things a bit by a need of having two subscriptions tables as well...

Unfortunately, It won't be possible to do they way I wanted, but idea to put one of it to microservices is probably the way to go or just port the Cashier v5 manually for one of the tables.  I'll decide on that tomorrow.

Thanks to everyone.
