### ISSUE TITLE
Change "subscriptions" table name to "subscription"

### ISSUE THREAD

**Issue by robertmylne** [laravel/cashier#313]
All my table names are in singular and not plural. Is there a protected $table = ""; Available for cashier?

**Comment by bchambers** [comment]
I'd like to change the default too...did you find a way around this limitation?

**Comment by Francismori7** [comment]
Not at the moment. You can fork the project and update it yourself, and require your own fork. 

http://stackoverflow.com/a/13500676

**Comment by guoyunhe** [comment]
I have the same need. Maybe can provide a `config/cashier.php` file to setup own table name.

**Comment by david-navarro** [comment]
Hello! Same issue.. I need to change default connection but I don't want to edit cashier/src/Subscription.php ... Any foresight to do a config file? 
Thx!

**Comment by jesusgalvan** [comment]
Same here, would like to change the default table name. Is there any config/setting to change this?

**Comment by david-navarro** [comment]
I finally solved it creating my own custom class and extends to Subscription, somethis like this: 

`use Laravel\Cashier\Subscription;

class CustomSubscription extends Subscription
{
    protected $connection = 'mysql';

    protected $table = 'subscriptions';

}`

And then I created this trait: 

`use App\CustomSubscription;
use Laravel\Cashier\Billable;

trait CustomBillable{

    use Billable;

    public function subscriptions()
    {
        return $this->hasMany(CustomSubscription::class, 'user_id')->orderBy('created_at', 'desc');

    }

}`

In my User class I did this: 

`use App\Adinton\Traits\CustomBillable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Jenssegers\Mongodb\Eloquent\HybridRelations;
use PHPZen\LaravelRbac\Traits\Rbac;

class User extends Authenticatable
{
    use Rbac, SoftDeletes, HybridRelations, CustomBillable;

[..]
`
This worked for me.

**Comment by UlukUlanbekov** [comment]
`php artisan vendor:publish --tag="cashier-migrations"`

Publish cashier migrationsh and change it as you want. Don't forget to set up your model properly. Good luck :)
[link to documentation](https://laravel.com/docs/8.x/billing#database-migrations)

**Comment by shahzeb1** [comment]
^ to add on to the above, you can now use a custom model without the need to create a `trait`.

https://laravel.com/docs/11.x/billing#using-custom-models
