### ISSUE TITLE
dateformat issue

### ISSUE THREAD

**Issue by finalight** [laravel/cashier#315]
hi, when I use Microsoft SQL Database with different environment (c9, localhost, azure web app, etc, etc..), the cashier date format seems to differ, because of this, I need to change the source code (subscription.php) as such

[code]
    public function getDateFormat()
    {
        return config('app.date_format');
    }
[/code]

the app.date_format reads from the env file, so it would be adjustable depending on the environment.
however, I do not wish to modify the library source code as this will affect the composer, so are there any way to resolve this issue?

**Comment by themsaid** [comment]
>  the cashier date format seems to differ

Can you please provide more details on what makes the date format differ?

**Comment by finalight** [comment]
it's not simple to explain

basically what happens is that, if i use microsoft azure server to read the datetime; it will be in a different format (mmddyyyy)

however, if i use another environment (mac osx/ubuntu) the datetime will be 'u'

in the model file; i've already set the datetime format to be 'u', but azure microsoft doesn't seems to be able interpret the datetime config that i set in the model at all.


therefore, I have to modify the library and read from the .env file instead; which is what I find it as a very hackish way of solving the problem

**Comment by themsaid** [comment]
How do you normally deal with this in a normal Laravel project?

**Comment by finalight** [comment]
it's not about the project itself, it's about the environment that the project is on

by default, you can actually change the datetime format by doing this in the model

```
protected $dateFormat = 'U';
```

however, the cashier isn't recognizing this and thus, producing invalid datetime format.

The thing is, on other OS like mac/ubuntu, it works fine. However, it doesn't work on microsoft environment. So I suspect the root problem is within the environment itself, but I do not know how to actually fix that issue

**Comment by themsaid** [comment]
Can't you format the database to accept the yyyy-mm-dd format?

**Comment by finalight** [comment]
It's already formatted at the database level. However, the cashier will
somehow format into another format which I don't understand why

**Comment by driesvints** [comment]
You can extend the `Subscription` model and override the `subscriptions` relationship on the billable model. Then add any changes you want like the `getDateFormat` method to the overridden class.
