### ISSUE TITLE
onTrial() - replace Carbon::today() with Carbon::now()

### ISSUE THREAD

**Issue by sebzap** [laravel/cashier#319]
Currently following line is used to determine whether a subscription is on a trial.

`return Carbon::today()->lt($this->trial_ends_at);`

However using `Carbon::now()` would be more accurate, because in the current version the onTrial method keeps returning true until the next day. This leads to problems. For example if you cancel the subscription after the trial has actually ended (but onTrial still returns true), the line `$this->ends_at = $this->trial_ends_at;` will be executed, which will lead to the immediate cancellation of the subscription rather than the cancellation at the periods end. (However the user has already payed for the period because the trial has ended in stripe.)

**Comment by jaketoolson** [comment]
I'm experiencing similar bug -- The trial ends at "2016-09-19 22:35:58" and the subscription ends_at "2016-09-19 22:35:58".  It's currently "2016-09-19 22:40:01 and yet valid() still returns true.  Changing it to today() and it returns false as expected.

**Comment by chrisvanpatten** [comment]
I noticed this as well. Definitely doesn't make sense to automatically give users extra time on a trial. If the trial_ends_at is in the past, the trial should be ended, full-stop.

**Comment by Francismori7** [comment]
This depends the use case. Some people will allow until the end of the day for the subscription to be canceled, some want it to end at the second the payment cycle is done. My solution would be to override the ends_at column to use Stripe's returned data instead of the one by cashier.

**Comment by themsaid** [comment]
Closing since it's not actually a bug, it's intended.

**Comment by jaketoolson** [comment]
@themsaid , @Francismori7 You'll note that everywhere in this package a timestamp is needed, even in comparing dates, ```Carbon::now()``` is used and not ```Carbon::today()```.  

So if its intended, its inconsistent and the package should decide on using now or today.

https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L168
https://github.com/laravel/cashier/blob/7.0/src/Subscription.php#L115
https://github.com/laravel/cashier/blob/7.0/src/Subscription.php#L325
