### ISSUE TITLE
[Proposal] 5.3 Tweak (param order in first())

### ISSUE THREAD

**Issue by BenGriffiths** [laravel/cashier#320]
5.3 comes with a change to the ordering of parameters with the method `first()` on collections - this change is needed:

https://github.com/laravel/cashier/compare/6.0...BenGriffiths:BenGriffiths-patch-1

I've not made a pull request yet as I imagine this will need a new branch (i.e 6.1) as it breaks backward compatibility with Laravel 5.2

**Comment by oyed** [comment]
Submit it as a PR. It's not really a proposal, it's a fix; Cashier in 5.3 just doesn't work because no `->subscription()` calls work anymore.

**Comment by sagarrabadiya** [comment]
below code in Laravel\Cashier\Billable.php in subscription method should fix it.

```
return $this->subscriptions->sortByDesc(function ($value) {
            return $value->created_at->getTimestamp();
        })
        ->first(function ($key, $value) use ($subscription) {
            if($key instanceof Subscription) {
                return $key->name === $subscription;
            }
            return $value->name === $subscription;
        });
```

as its comparing if $key is instance of Subscription(laravel 5.3) else it will consider $value(laravel 5.2)

so it will be backward compitible as well.

**Comment by BenGriffiths** [comment]
Closing this as it's not longer required and sorted in 7.0
