### ISSUE TITLE
Is there any support for mongodb?

### ISSUE THREAD

**Issue by rohitkhatri** [laravel/cashier#327]
Does this library has any support for mongodb?

**Comment by GrahamCampbell** [comment]
No, sorry.

**Comment by cedricve** [comment]
Yes it does work with the moloquent library. 
https://github.com/jenssegers/laravel-mongodb

**Comment by cdiacon** [comment]
How do you handle the Subscription model that extends Eloquent instead of Jenssegers\Mongodb\Eloquent ??

**Comment by cdiacon** [comment]
nice, great answer!

**Comment by themsaid** [comment]
closed for lack of activity, feel free to ping cedricve  if you want :)

**Comment by cdiacon** [comment]
found some forks that have the same issue using the Mongodb and wondering if there will be any compatibility update?

**Comment by themsaid** [comment]
No plans for this, sorry :)
