### ISSUE TITLE
Subscription::class transform to trait.

### ISSUE THREAD

**Issue by cedricve** [laravel/cashier#328]
It would be useful to have a similar trait (as the Billable trait) for the Subscription class. I'm currently working with Moloquent (MongoDB version of Eloquent), and this makes it harder to use this. Let me know what you think.

```
 /**
 * Get all of the subscriptions for the user.
 *
 * @return \Illuminate\Database\Eloquent\Collection
 */
public function subscriptions()
{
    return $this->hasMany(Subscription::class, 'user_id')->orderBy('created_at', 'desc');
}
```

To resolve this I copied the Subscription class to my project, and override the Subscriptions() relation method from the Billable trait, in my user model. However having the Subscription trait would make it a lot better to keep the code updated with future releases.

**Comment by themsaid** [comment]
You can extend the Subscription class so that it's up to date with future releases.
