### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::newSubscription()

### ISSUE THREAD

**Issue by joannesnoel** [laravel/cashier#331]
Why i get some error when creating a subscription.

Call to undefined method Illuminate\Database\Query\Builder::newSubscription()

Hope you'll reply ASAP. Thanks

**Comment by rossjcooper** [comment]
What is the class of the object you're calling this on and what version of Cashier are you using?

**Comment by joannesnoel** [comment]
@rossjcooper thanks for the reply. nevermind for this but i have a question. how can i generate the payment method nonce? Thanks.

**Comment by rossjcooper** [comment]
Not sure but I would open this question in a forum or under another issue
