### ISSUE TITLE
Avoid user_id when not using App\User

### ISSUE THREAD

**Issue by mdixon18** [laravel/cashier#332]
I am using a different table/model for my web application as all the logins are based in App\User and the users are bound to an account App\Account. So for relationships sake I would like to use account_id on my subscriptions rather than user_id. How can i achieve this?

**Comment by Repox** [comment]
@mdixon18 I had the same need as you.

I've forked the repo and created branch that should allow you to work with it. I've also opened a proposal issue and (hopefully) waiting for approval (see #334 for details).

You can check out my feature branch here: https://github.com/Repox/cashier/tree/dynamic-model

If by any chance you'd like to add it to your composer to try it out, you can do so by adding the repository and changing the version of the Cashier to my branch:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Repox/cashier"
        }
    ],
    "require": {
        "laravel/cashier": "dev-dynamic-model"
    }
}
```

**Comment by Repox** [comment]
A pull request solving this issue has been merged.
