### ISSUE TITLE
Billable.php

### ISSUE THREAD

**Issue by TTiger** [laravel/cashier#333]
Billable.php seems to have a typo in the collection methods:

Line 190 - ->first(function ($key, $value)
the arguments should be swapped , correct?

According to the documents at:
https://laravel.com/docs/5.3/collections#method-first

The correct order is $value, $key.

Happy to create a PR if you would like, just verified in my app running Spark 2 / Laravel 5.3

**Comment by mazedlx** [comment]
Line 190: `->first(function ($value, $key) use ($subscription) { `

**Comment by cdubant** [comment]
I'm running the following versions and it's not fixed as I have the same swap of parameters.

![image](https://user-images.githubusercontent.com/12911253/34456139-d0e38bae-ed8f-11e7-8513-755ec869d874.png)

Tried to swap them back to what's proposed by @mazedlx and it works fine, though it should be fixed from the source directly.
