### ISSUE TITLE
[Proposal] Add invoiceForUpcoming method to create invoice items without immediately paying them

### ISSUE THREAD

**Issue by kitbs** [laravel/cashier#335]
The `Billable::invoiceFor()` method currently creates a `Stripe\InvoiceItem` and immediately generates an invoice and pays it  by calling `Billable::invoice()` at the end.

I propose a method `Billable::invoiceForUpcoming()` (or other name) that creates a `Stripe\InvoiceItem` without immediately paying it. The use case would be to accumulate various small charges throughout the billing period and only invoice them at once on the usual subscription billing date, rather than a lot of small charges paid individually.

I was experimenting with moving the code from `invoiceFor()` (except the final call to `invoice()`) into a new method `invoiceForUpcoming()` (because the logic for creating an invoice item is the same) and then calling `invoiceForUpcoming()` followed by `invoice()` in the original `invoiceFor()` method to maintain its original behaviour.

e.g.:

``` php
    /**
     * Invoice the customer for the given amount and generate an invoice immediately.
     *
     * @param  string  $description
     * @param  int  $amount
     * @param  array  $options
     * @return bool
     *
     * @throws \Stripe\Error\Card
     */
    public function invoiceFor($description, $amount, array $options = [])
    {
        $this->invoiceForUpcoming($description, $amount, $options);

        return $this->invoice();
    }

    /**
     * Invoice the customer for the given amount in the upcoming invoice and do not generate an invoice immediately.
     *
     * @param  string  $description
     * @param  int  $amount
     * @param  array  $options
     * @return \Stripe\InvoiceItem
     *
     * @throws \Stripe\Error\Card
     */
    public function invoiceForUpcoming($description, $amount, array $options = [])
    {
        if (! $this->stripe_id) {
            throw new InvalidArgumentException('User is not a customer. See the createAsStripeCustomer method.');
        }

        $options = array_merge([
            'customer' => $this->stripe_id,
            'amount' => $amount,
            'currency' => $this->preferredCurrency(),
            'description' => $description,
        ], $options);

        return StripeInvoiceItem::create(
            $options, ['api_key' => $this->getStripeKey()]
        );

    }
```

**Comment by Francismori7** [comment]
I actually agree with this. Please submit a PR.

**Comment by kitbs** [comment]
Thanks, @Francismori7. I'm happy to submit a PR, but is it enough to have one vote? I don't want to fall foul of the contributing guidelines if there's not much community interest. I can always override it in my own trait for now.

**Comment by Francismori7** [comment]
@kitbs, you may submit it, Taylor will probably merge it.
