### ISSUE TITLE
Cancel not working for non-User models

### ISSUE THREAD

**Issue by amsoell** [laravel/cashier#339]
An application I'm writing associates subscriptions with an Organization model, instead of Users. Adding the `use Billable` trait to the Organization model worked fine for creating subscriptions, but calling the `cancel()` method on a subscription returns an error:

> FatalErrorException in Subscription.php line 345:
Call to a member function asStripeCustomer() on null

The indicated line shows that some code assumes a `user` attribute attached to each subscription. I suspect the problem is there.

```php
return $this->user->asStripeCustomer()->subscriptions->retrieve($this->stripe_id);
```

Happy to dig into this myself, but thought I'd post if anyone else has some insight or experience applying Cashier to non-User models.

**Comment by nathanjdunn** [comment]
I've already tried submitting a PR for this but it was rejected for no given reason https://github.com/laravel/cashier/pull/265. I ended up creating my own trait which used Cashier's `Billable` trait and overwrote the method.

**Comment by nathanjdunn** [comment]
Looks like a fix for this issue has been merged https://github.com/laravel/cashier/pull/337.

Can't help but wonder why my fix (made in February) was rejected!

**Comment by amsoell** [comment]
Sorry your PR wasn't taken @nathanjdunn, but the latest one that was accepted appears to be working great. Documentation needs an update in light of it, but thanks to @Repox for getting it done.
