### ISSUE TITLE
[Proposal] Add bank accounts to customer in Stripe

### ISSUE THREAD

**Issue by YaroslavMolchan** [laravel/cashier#340]
I need to add bank accounts to customer and do the same operations like with cards.
Now I copy and rewrite trait `Billable.php` and some its methods to attach bank accounts.
And I dont write this issue and working with my version of trait, but I dont like in `SubscripttionBuilder.php` this lines of code:
`if ($token) {
       $this->owner->updateCard($token);
}`
I think `$this->owner->updateSource($token);` will be better.

I can create Pull request, or maybe it is not necessary for this repository and I would use my forked version alone.

**Comment by rorymcdaniel** [comment]
I'd be interested in this as well. @YaroslavMolchan if you have any suggestions or care to share your fork, I'd appreciate it.

**Comment by themsaid** [comment]
I tried to implement this but the bank account needs to be verified before being ready for use, the verification process means there'll be no immediate charge which I'm not sure if cashier should support this.
