### ISSUE TITLE
Add Laravel dependency/version info

### ISSUE THREAD

**Issue by robjbrain** [laravel/cashier#342]
There's currently no info on what Laravel version cashier is dependent on. For instance if i'm on Laravel 5.1 and can't upgrade to 5.3 but wish to use cashier, it's unclear whether cashier is compatible. The documentation just links to the 5.3 docs for Laravel, which isn't particularly helpful.

Can we add some info in the README about which stable versions of Laravel cashier is compatible with?

**Comment by themsaid** [comment]
You can check that on the billing page of the laravel version you desire https://laravel.com/docs/5.1/billing
