### ISSUE TITLE
A question : Can I change the name of table ?

### ISSUE THREAD

**Issue by khanof89** [laravel/cashier#346]
with my current database setup I already have a table named subscriptions which is being used for paypal subscriptions, is there anyway I can set the name of cashier's subscriptions table to cashier_subscriptions I think defining a protected $table variable in  /vendor/laravel/cashier/src/Subscription.php might do this but then with the update it will be gone. Anything I can do for this ?

**Comment by themsaid** [comment]
You can extend the Subscription model and point to your new class from Billable.php
