### ISSUE TITLE
Custom View Location Not Working

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#347]
I have edited the view location in my Laravel settings so my `view.php` is like this:
```
'paths' => [
        realpath(base_path('public/app/build')),
    ],
```

Just now I published the cashier file so I can edit its view using the command:
```
php artisan vendor:publish
```

After the above command, the cashier's invoice view was copied to the folder `resources/views/vendor/cashier/`.

My problem is, when I create an override of the `receipt.blade.php` and place it inside my view folder `base_path('public/app/build/vendor/cashier/')`, it is not picking up the edits. The override only works when the edit is done to the file in the default location `resources/views/vendor/cashier/`. Why is the custom view location not respected for overrides?

**Comment by Mr-Anonymous** [comment]
I see that `loadViewsFrom` method is in `src/CashierServiceProvider.php` file. So do I need to edit this file to change the view to a custom path? Is there a better way to do this? Editing the vendor src file is an issue since that is not tracked by git and I need to manually remember to edit that path each time during future updates. Am I able to define a custom path elsewhere which can be tracked and easily updated by git?

**Comment by themsaid** [comment]
It's hardcoded based on the convention that laravel follows, you can extend the service provider, update the method, and include your own version of the provider in config/app.php
