### ISSUE TITLE
Braintree payment method chosen wrong

### ISSUE THREAD

**Issue by norbert-berenyi** [laravel/cashier#348]
If a customer has more than one payment method the Billable->charge() method is not working as expected. It charges the first payment method, not the default one.

`$customer->paymentMethods[0]->token`

**I have fixed it by creating a method:** (I hope correctly...)

`$this->defaultPaymentMethod()->token,`

```
/**
 * Choose the default payment method.
 *
 * @return \Braintree\PaymentMethod
 */
private function defaultPaymentMethod()
{
    $customer = $this->asBraintreeCustomer();

    foreach ($customer->paymentMethods as $paymentMethod) {
        if($paymentMethod->default) { return $paymentMethod;}
    }
}
```

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
