### ISSUE TITLE
Attach invoice in email

### ISSUE THREAD

**Issue by yaofong** [laravel/cashier#349]
Hi,

I know that there is a `downloadInvoice()` method, for user to download invoice from the web.

If I need to generate a pdf invoice, attach it and send to customer via email, can I use `downloadInvoice()`?

**Comment by driesvints** [comment]
Hi there, you can use the `pdf` method on the invoice which will return you the string of the PDF which you can then add as a binary file to your mail. 

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
