### ISSUE TITLE
Subscription.php still coupled with user model

### ISSUE THREAD

**Issue by paulhbarker** [laravel/cashier#351]
The asStripeSubscription() method on the Subscription.php class still points to the user model and throws a FatalThrowableError when calling $model->subscription('monthly')->cancel(); 

FatalThrowableError in Subscription.php line 355:
Call to a member function asStripeCustomer() on null

```php
public function asStripeSubscription()
{
    return $this->user->asStripeCustomer()->subscriptions->retrieve($this->stripe_id);
}
```

I noticed that a pr was merged not too long ago that decoupled subscriptions from the user model. Was this missed? I find that overriding this in my own class that extends Laravel\Cashier\Subscription with the proper model works:

```php
public function asStripeSubscription()
{
    return $this->myModel->asStripeCustomer()->subscriptions->retrieve($this->stripe_id);
}
```

Lines 355-358 on 7.0 branch

**Comment by themsaid** [comment]
@paulhbarker the user model here is determined by the environment variable `STRIPE_MODEL`, please make sure you set it correctly or it'll fallback to the App\User model.

**Comment by paulhbarker** [comment]
@themsaid Thanks for pointing me in the right direction. I don't have an environment variable, instead I changed the model in config/Services.php. Works great.
