### ISSUE TITLE
Upgrade to Stripe 4.1.1

### ISSUE THREAD

**Issue by jideokus** [laravel/cashier#352]
There has been some issues when working with cashier 7.0.

> ErrorException in CurlClient.php line 250:
> Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com.
> 
> (Network error [errno 35]: Unsupported SSL protocol version)

After contacting support@stripe.com, I upgraded my apache to 2.4.8, my php to 5.6.8 and my openssl to 1.0.1f afterwhich the error persisted. Support then asked me to upgrade my stripe to stripe 4.1.1. I but cashier uses 3.0 which caused my composer to break.

My workaround was to place the latest copy of stripe in the vendors folder of my app and it works perfectly but this would cause issues when I run an update. It would be great to have this integrated into the next release for cashier.

**Comment by ellisio** [comment]
Any word on getting this upgraded? Composer is now listing this as extremely outdated as Stripe is now on `v4.3.0`.
