### ISSUE TITLE
newSubscription get ends_at = null

### ISSUE THREAD

**Issue by marcoapferegrino** [laravel/cashier#353]
When I call new Subscription always get ends_at with null value.

**Comment by themsaid** [comment]
@marcoapferegrino can you please provide some code sample?

**Comment by themsaid** [comment]
ping @marcoapferegrino

**Comment by marcoapferegrino** [comment]
I solved it adding some code in the library function. I obtained from subscription you get I. The service because the attr ends_at was null I dont know why. Later I will add my code here. Thanks for replying

**Comment by marcoapferegrino** [comment]
I solve it Editing the file
Laravel\Cashier\SubscriptionBuilder

**Original**

` return $this->owner->subscriptions()->create([
            'name' => $this->name,
            'stripe_id' => $subscription->id,
            'stripe_plan' => $this->plan,
            'quantity' => $this->quantity,
            'trial_ends_at' => $trialEndsAt,
            'ends_at' => null,
        ]);`

**Editing**
`return $this->owner->subscriptions()->create([
            'name' => $this->name,
            'stripe_id' => $subscription->id,
            'stripe_plan' => $this->plan,
            'quantity' => $this->quantity,
            'trial_ends_at' => $trialEndsAt,
            'ends_at' => $subscription->current_period_end,
        ]);`

Maybe there is a cleaner and better solution but meanwhile I found this. Let me know if oyou fin other please

**Comment by themsaid** [comment]
The column is used when the subscription is cancelled, check the docs here: https://laravel.com/docs/5.3/billing#cancelling-subscriptions

**Comment by themsaid** [comment]
You shouldn't fill that key while creating a new subscription.

**Comment by marcoapferegrino** [comment]
And it won't be called ended_at?. Ok I understand so where should be stored
this field : date when subscription ends?? I don't find it.

**Comment by themsaid** [comment]
It never ends until it's cancelled, it's auto-renewed.

**Comment by marcoapferegrino** [comment]
Sorry I am new using cashier. So where can I find the date when the
susbcription will be renewed?

**Comment by themsaid** [comment]
The renewal date changes every billing cycle, so we don't store it in cashier.

**Comment by themsaid** [comment]
You can use Stripe webhooks to store that date on every renewal if you want.

**Comment by marcoapferegrino** [comment]
Nice now I understand better what is happening sorry for the misundertood.
Thanks a lot

**Comment by garygreen** [comment]
If your interested, I made a console command which synchronises the renewal date for all your subscription (e.g. the start of when Stripe when next create an invoice/bill the customer). It's a shame Cashier doesn't set this internally when creating a subscription, as you often rely on it to know when to downgrade an account / stop services to a user. Hopefully this helps you 👍 

https://gist.github.com/garygreen/fb4dc0288e2c57f9af015968ff7019bb
