### ISSUE TITLE
Cashier Braintree - subscription('plan')->cancel() not canceling braintree subscription 

### ISSUE THREAD

**Issue by matpulis** [laravel/cashier#355]
I am using laravel cashier to create a subscription based plan purchasing system with Braintree as a payment gateway.

My subscriptions are successfully created, my issue is when canceling.

After I fire:

```php
$user->subscription('pro')->cancel();
```

The user is successfully transitioned into the grace period, but on Braintree the subscription is still active and not canceled.

However when I fire:

```php
$user->subscription('pro')->cancelNow();
```

The subscription on Braintree is now marked as Canceled.

My question is how will Braintree know not to charge this user when I transition the user to the grace period with cancel() if cashier does not mark the subscription in Braintree as canceled.

Maybe I'm missing something here... Do I need to handle this myself when canceling subscriptions using the Briantree PHP SDK.

**Comment by matpulis** [comment]
Ok, actually managed to figure this out.

Firing the:

`$user->subscription('pro')->cancel();`

What the cancel() method actually does is set your subscription on Braintree to end after 1 billing cycle in term canceling the Braintree subscription on the next billing date. To verify this what you need to do is. Find the subscription from the Braintree dashboard and 'edit' the subscription and there you will find that the billing cycle will be set to end after 1 cycle.

Calling the method:

`$user->subscription('pro')->resume();`

On a user in the grace period will set the subscription's end after period too Never

**Comment by CallMeRev** [comment]
hey i im keep getting this issue with braintree , the subscription purchace works and all , but all the like casher - subscription commands dont exacly work when i try to cancel i get a "Call to a member function cancel() on null " and if i try to check if the user is subbed its always false ..

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
