### ISSUE TITLE
How to Get Amount and Invoice Details from Webhook $payload

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#358]
I am using `Laravel 5.3` with Cashier for Stripe. I have set-up a custom controller extending the `CashierController` for handling Webhooks as per the Docs. In this Webhook, how can I get the amount that was charged and invoice details from `$payload`?

```
    public function handleInvoicePaymentFailed($payload)
         {
             // Handle The Event
             $customer = $this->getBillable($payload['data']['object']['customer']);
    
             // NEXT - HOW TO GET THE AMOUNT THAT WAS CHARGED AND INVOICE NUMBER??
    
    
             return new Response('Webhook Handled', 200);
         }

      public function handleInvoicePaymentSucceeded($payload)
         {
             // Handle The Event
             $customer = $this->getBillable($payload['data']['object']['customer']);
    
             // NEXT - HOW TO GET THE AMOUNT THAT WAS CHARGED AND INVOICE NUMBER??
    
    
             return new Response('Webhook Handled', 200);
         }
```
I want to get the following info from the `$payload`:

 1. Amount 
 2. Invoice Number

Can someone share how this can be done please...

**Comment by themsaid** [comment]
Hope you could figure this out. Closing since it's a very old question.

**Comment by saqueib** [comment]
To get the amount use `$payload['data']['object']['amount_due']`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
