### ISSUE TITLE
[Request] Vendor VAT ID on Invoice

### ISSUE THREAD

**Issue by borutjures** [laravel/cashier#360]
There is no way of entering or displaying vendor's VAT ID on the invoices.

A customer cannot use an invoice without a vendor's VAT ID for their accounting. The vendor is also issuing invalid invoices that are not in accordance with the tax rules.

Could an option to specify `'vendorVat' => '12345678'` in the `$data` be added when calling `Cashier\Invoice->download()` and displayed in `receipt.blade.php` under the `$location`:

```
@if (isset($vendorVat))
    {{ $vendorVat }}<br>
@endif
```

**Comment by joshgriggs** [comment]
This is pretty important for EU based companies that are registered for VAT, I would be happy to make a PR for this if needed.

**Comment by driesvints** [comment]
You can easily add this to your own receipt view. See https://laracasts.com/discuss/channels/laravel/customizing-cashier-invoices for publishing the receipt pdf.

**Comment by driesvints** [comment]
Heya. Actually, I just saw this change was added on 7.0 so you're in luck :)
