### ISSUE TITLE
[Question] Cashier Full Money Back Refund

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#363]
Instead of the subscription trial, I would like to offer 14 days money back offer instead. I see that you now have the `refund` method to process stripe refund. But, how do I refund the full amount whatever the user had paid and not a set charge? Do I need to query and find out the last invoice amount paid? I need to cancel the subscription, refund the money and also make sure any new quantities that were added after the first invoice are not charged to the next bill. Can someone help me out here please:

```         
if ($user->subscribed('main')) {
     $user->subscription('main')->cancel();
     // Next how to process full refund and not charge user for any quantity increment added before this request was processed??
}            
```

**Comment by Mr-Anonymous** [comment]
Okay, since my post I progressed a little bit on this scenario. This is what I have now where I am checking the subscription creation date and then processing a refund to if its less than 14 days.
```
$user->subscription('main')->cancel();
if ( Carbon::now() <= $user->subscription('main')->created_at->addDays(14) ) {
  $invoice = $user->invoices()[0];
  $user->refund($invoice->charge);
}
```
This seems to get the job done in most cases. However, the problem I end up having is, if a customer cancels the subscription, then resumes the subscription within the grace period and then cancels it again, all happening within the 14 days, the second time its cancelled, the refund is processed on the charge again and I end up getting an error `Charge has already been refunded.`. I am not sure how to check if the invoice charge has already been processed and only refund the money if its not refunded already.

Has anyone got any suggestions please..

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
