### ISSUE TITLE
createAsStripeCustomer no add card

### ISSUE THREAD

**Issue by ApuRed** [laravel/cashier#364]
I want to make unique payments but when I use createAsStripeCustomer this creates the user but does not associate the credit card or debit card, which can be wrong? Because with the subscriptions I have no problem.

**Comment by websanova** [comment]
Also having this issue.

**Comment by MichaelHoughton** [comment]
@ApuRed - can you confirm if you are passing a token when as a parameter when using `createAsStripeCustomer`?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
