### ISSUE TITLE
Subscribe for teams

### ISSUE THREAD

**Issue by paulocastellano** [laravel/cashier#365]
Hi,

Currently cashier require user_id in subscriptions table, it is bad when we have software for team, like zendesk for example.

How us resolve it?

**Comment by richartkeil** [comment]
@paulocastellano You can use your team as the subscription user. It's not the cleanest way to handle this but works without problems.

**Comment by paulocastellano** [comment]
@richartkeil thanks

**Comment by richartkeil** [comment]
@paulocastellano Since 7.0 Cashier doesn't use the User model as the default Billable model for Stripe anymore. If your Team model is Billable, you have to rename the `user_id` column in your subscriptions table to `team_id` (foreign key name of the model).
