### ISSUE TITLE
Check if a Charge has been Refunded already

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#366]
In Cashier, is it possible to check if an Invoice charge has been refunded already?

**Comment by mlantz** [comment]
Technically the when making a request to the Stripe API you get a "amount_refunded" value but there is no method I know of to access an existing charge

**Comment by driesvints** [comment]
Since refunding is an (undocumented) feature of Cashier I believe this would indeed be useful. I'll mark this as a feature request. I'll also try to document the refunding behavior.

**Comment by driesvints** [comment]
I looked into this a bit more but I'm unsure if this can be done easily atm. For example, the invoice object only has a single latest charge object where you can check the `refunded` status but I'm fairly sure you can pay invoices in pieces somehow or even individual line items one by one. So I'm not sure as what the perfect way would be to determine the invoice status from all that.

https://stripe.com/docs/api/invoices/object#invoice_object-charge

**Comment by driesvints** [comment]
I'm going to close this as I don't think there's an easy way to check this.
