### ISSUE TITLE
How to extend Subscription model?

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#367]
I have created couple of custom tables that has the `subscription_id` (ID from cashier subscription table) foreign key.  I would like to add the eloquent relation to my models and the same `hasMany` relation in Subscription model. How can I extend the subscription model from cashier please?

**Comment by Remo** [comment]
I had to add a custom relation to the subscription model. Not sure where exactly you want to use this, but in my case it always starts with the user object. I was able to override the `subscriptions` method in the user class like shown below:

```php
public function subscriptions()
{
   return $this
      ->hasMany(YourSubscription::class, $this->getForeignKey())
      ->orderBy('created_at', 'desc');
}
```

**Comment by MichaelHoughton** [comment]
@Mr-Anonymous - you can simply add a new Subscription model in your project, and extend the Cashier Subscription Model File.

e.g. make the following file in your app directory (or where ever your model files are stored):

```php
<?php

namespace App;

use Laravel\Cashier\Subscription as CashierSubscription;
use Illuminate\Database\Eloquent\Model;

class Subscription extends CashierSubscription
{
    public function yourCustomMethod()
    {
        // add them here
    }
}
```

You will then have all the functionality of the Laravel Subscription methods, plus any custom ones you need.

**Comment by shanecp** [comment]
You also need to override the relationship on the User model.

```
	/**
	 * Get all of the subscriptions for the Stripe model.
	 *
	 * @return \Illuminate\Database\Eloquent\Collection
	 */
	public function subscriptions()
	{
		return $this->hasMany(\App\Subscription::class, $this->getForeignKey())->orderBy('created_at', 'desc');
	}
```

**Comment by driesvints** [comment]
Yeah you should be able to achieve this by only overwriting the `subscriptions` method on the billable model.

**Comment by paul-adams-985** [comment]
Superb. Perfect

**Comment by JohnnyWalkerDesign** [comment]
@driesvints I understood the comments made by @MichaelHoughton and @shanecp, but I was confused by your comment. Could you clarify what you mean? Thank you.

**Comment by driesvints** [comment]
@JohnnyWalkerDesign take a look at @shanecp's example above my comment. That way you can overwrite the subscription model. There's one more new place where you need to overwrite it though in the latest Cashier Stripe version: https://github.com/laravel/cashier-stripe/blob/12.x/src/SubscriptionItem.php#L43

But please remember we don't officially support this and it's at a risk of breaking changes.

**Comment by JohnnyWalkerDesign** [comment]
Thanks! Hmm. The only reason I'd wish to "extend" it is to add a couple of new helper methods unique to my project that will potentially make my life easier. I'd never overwrite any existing methods and risk breaking them. I guess I could just create a new Model though...

**Comment by elanclarkson** [comment]
The officially supported way to do this is now with the following, typically in the `boot` method of `App\Providers\AppServiceProvider`:

```
use Laravel\Cashier\Cashier;
use App\Models\Cashier\Subscription;
use App\Models\Cashier\SubscriptionItem;
 
/**
 * Bootstrap any application services.
 */
public function boot(): void
{
    Cashier::useSubscriptionModel(Subscription::class);
    Cashier::useSubscriptionItemModel(SubscriptionItem::class);
}
```

Docs: https://laravel.com/docs/11.x/billing#using-custom-models
