### ISSUE TITLE
[BUG] Subscription Quantity doesnt go below 1 when using decrementQuantity()

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel/cashier#368]
I am finding this behaviour odd and I dont know if its meant to work this way. This is the case:

User starts a new subscription with 1 quantity:
```
$user->newSubscription('main', 'monthly')->quantity(1)->create($token);
```
Later, user deletes that 1 quantity so there should be a decrement of that quantity (note: user doesnt want to cancel the subscription. He only want to bring the quantity back to 0 and then add more later when needed):
```
$user->subscription('main')->decrementQuantity(1);
```
But what happens is, Cashier is not reducing the quantity to 0. It remains at 1.

I also tried different scenario where user adds 2 quantity when creating a subscription and later deletes 2 quantity, Cashier only deletes 1 and leaves 1 quantity in the subscription. Why is that?

When I looked at `Subscription.php`, I noticed that the `updateQuantity()` is setting a minimum value of 1 and not 0 and hence this could be happening.
```
$this->updateQuantity(max(1, $this->quantity - $count));
```
That is not good since if a user reduces the same number of quantity that was added, he is still being charged for minimum 1 quantity when he shouldn't need to pay for that. 

I don't want to cancel the subscription all together if it reaches 0 since in my app, user can add and remove quantity multiple times on that subscription during the month and this behaviour is not working right.

Is this supposed to be like this? If so, why was it intended to have minimum 1 and not 0 which is probably more logical? Could this be changed to 0 instead of 1?

Can someone share your thoughts please?

**Comment by lukehebb** [comment]
This is because instead of having a subscription with 0 quantity you should cancel the subscription. You can set up a new one later with $user->newSubscription();

**Comment by driesvints** [comment]
When you don't have any quantity left it's best to cancel the subscription. The reason for this is that otherwise Stripe will just generate $0 invoices which serve no purpose.

**Comment by alphametric** [comment]
I recently encountered a situation like this. My solution was to extend the subscription model and then override the `decrementQuantity()` method to allow for setting to zero. Alternatively, you can just use the `updateQuantity()` method and set the exact value it should be. That allows for setting zero.
