### ISSUE TITLE
Downloading Invoices failing

### ISSUE THREAD

**Issue by tehcodedninja** [laravel/cashier#378]
I had invoice downloading on one project working then decided to rewrite whole project over in new folder and new eviroment. When I try to do downloadInvoice() on either project, I get the following.

`at HandleExceptions->handleError(2, 'A non-numeric value encountered', '/ignite/vendor/dompdf/dompdf/src/FrameReflower/Table.php', 577, array('style' => object(Style), 'columns' => array(array('x' => 0, 'min-width' => 163.0, 'max-width' => 163.0, 'used-width' => null, 'absolute' => 163.0, 'percent' => 0, 'auto' => false), array('x' => 0, 'min-width' => 154.494, 'max-width' => 276.219, 'used-width' => null, 'absolute' => 0, 'percent' => 0, 'auto' => true)), 'i' => 1, 'dims' => array(0, 0, '0', '0', 'auto', 'auto', '2px'), 'delta' => 'auto')) in Table.php line 577`

**Comment by fwartner** [comment]
Having the same problem in my Spark application.
Please fix *ASAP*..

**Comment by faustbrian** [comment]
Same issue here, my client's currently can't download their invoices. Using the Braintree package.

@taylorotwell Anyone working on this?

**Comment by ConsoleTVs** [comment]
Maybe some dompdf issues?

**Comment by fwartner** [comment]
Should be fixed with the newest Cashier release. Have installed the dev-master branch and it's working perfectly.

**Comment by ConsoleTVs** [comment]
@fwartner Is there any way to pay a sigle charge (not subscription) without the user beeing a subscriber? Seems it asks for it and in some cases you might only want single payments.

**Comment by fwartner** [comment]
$user->charge('amount'); should work I guess

**Comment by ConsoleTVs** [comment]
If i'm not wrong it asks for the user to be a customer already (and in fact it must) but that function does not require the stripe token, so it must be added manually i guess to the user's table... the sub method have a ->create($token) and that makes the deal!

Do you think (i haven't tried it) that ->charge($ammount)->create($token) would work?

**Comment by fwartner** [comment]
I would refer to the docs ^^

**Comment by netpok** [comment]
It's a dompdf issue and it's fixed in v0.8.0, cashier needs to update to that version.

**Comment by driesvints** [comment]
Should be fixed in the latest version.
