### ISSUE TITLE
[Proposal] dynamic subscription model loading to offer flexibility of using non elequent model

### ISSUE THREAD

**Issue by netcode** [laravel/cashier#380]
We had some trouble try to use cashier in Mongo db using non elequent based models though packages like [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb). and to make it work we overwrited the billable trait function subscriptions , and added our own version of subscription models.

My suggesion is:
-  add a new config for subscription model like we you made with user model and make it fallback to package version of subscription
-  add subscription function as a trait  and added to the model 

Now anyone need it will easily change the config , create a new model subscription (extends from whatever ) and added the trait to it. if he wants to use the default he don't need to add anything the package will load the default model.

**Comment by driesvints** [comment]
This goes a little beyond what Cashier is intended to do. In most Laravel apps you would add this to a User model or Team model. If you want you can just make these changes for your own use case or release your own package. But it's going a little too far for Cashier itself.
