### ISSUE TITLE
Call to a member function create() on null

### ISSUE THREAD

**Issue by lstables** [laravel/cashier#381]
Although I'm getting the Stripe Token like so:

````
in Billable.php line 385
at User->updateCard(object(Token)) in SubscriptionBuilder.php line 212
at SubscriptionBuilder->getStripeCustomer('tok_19oWykA5zF9kYK3AAOoQP6YM', array('email' => 'test@email.com')) in SubscriptionBuilder.php line 177
````

I'm getting the above error, the `stripe_id` is saving within the `users table` but nothing else. Is cashier up to date with new changes at Stripe?

@taylorotwell @themsaid

**Comment by lstables** [comment]
Anyone? Is this a big or something??

All I'm calling is

````
$user = Auth::loginUsingId(1);
$user->newSubscription('main', 'monthly')->create($request->stripeToken);
````

**Comment by kyranb** [comment]
I'm getting the same when a card is declined.

**Comment by lstables** [comment]
Not sure if Cashier has been updated to reflect Stripe's new API, that is the question. So until this is resolved, I've starting just using the API directly with no issues :)

**Comment by themsaid** [comment]
hmm I don't seem to be able to replicate, can you please share more details?

**Comment by lstables** [comment]
@themsaid I have the stripe key & secret set within my `.env` file, also have the following JS as described on the stripe docs:

````
$(document).ready(function () {
    Stripe.setPublishableKey('xxxxxxxxxxxxxxxxxxx');

    var stripeResponseHandler = function(status, response) {

        var $form = $('#payment-form');


        if (response.error) {
            // Show the errors on the form
            //$('.payment-errors').text(response.error.message).addClass('alert alert-danger');
            $form.find('.payment-errors').text(response.error.message).addClass('alert alert-danger');

            if (response.error.message) {
                $form.find('.submit').prop('disabled', false);
            }
        } else {
            // token contains id, last4, and card type
            var token = response.id;
            // Insert the token into the form so it gets submitted to the server
            $form.append($('<input type="hidden" name="stripeToken" />').val(token));
            // and re-submit
            $form.get(0).submit();
        }
    };
    jQuery(function($) {
        $('#payment-form').submit(function(e) {
            var $form = $(this);
            // Disable the submit button to prevent repeated clicks
            $form.find('.submit').val('Please Wait...').prop('disabled', true);
            //$('#processingModal').modal({
            //    show: true
            //});
            // Request a token from Stripe:
            Stripe.card.createToken({
                number: $('#card-number').val(),
                cvc: $('#card-cvc').val(),
                exp_month: $('#card-month').val(),
                exp_year: $('#card-year').val()
                //address_zip: $('.address_zip').val()
            }, stripeResponseHandler);
            // Prevent the form from submitting with the default action
            return false;
        });
    });

});
````

Then within my controller just calling:

````
$user = Auth::loginUsingId(1);
$user->newSubscription('main', 'monthly')->create($request->stripeToken);
````

HTML as follows:

````
{!! Form::open(['url' => 'stripeSuccess',  'id' => 'payment-form']) !!}

            {{ csrf_field() }}
            <div class="payment-errors"></div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="street">Card Number</label>
                    <input type="text" class="form-control" data-stripe="number " value="{{ App::environment() == 'local' ? '4242424242424242' : '' }}" id="card-number">
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="street">CVC</label>
                    <input type="text" class="form-control" data-stripe="cvc" value="{{ App::environment() == 'local' ? '123' : '' }}" id="card-cvc">
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="street">Expiration Date</label>
                    <select data-stripe="exp-month" class="form-control" id="card-month">
                        <option value="" disabled selected>Month</option>
                        <option value="1">1 (Jan)</option>
                        <option value="2">2 (Feb)</option>
                        <option value="3" @if (App::environment() == 'local') selected @endif>3 (Mar)</option>
                        <option value="4">4 (Apr)</option>
                        <option value="5">5 (May)</option>
                        <option value="6">6 (Jun)</option>
                        <option value="7">7 (Jul)</option>
                        <option value="8">8 (Aug)</option>
                        <option value="9">9 (Sep)</option>
                        <option value="10">10 (Oct)</option>
                        <option value="11">11 (Nov)</option>
                        <option value="12">12 (Dec)</option>
                    </select>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="street"><br /></label>
                    {!! Form::selectYear(null, date('Y'),  date('Y') + 15, App::environment() == 'local' ? '2020' : 'Year', ['data-stripe' => 'exp-year', 'class' => 'form-control', 'id' => 'card-year']) !!}
                </div>
            </div>

            <div class="form-group">
              <div class="col-lg-3">
                 <button class="btn btn-success submit">Subscribe</button>
              </div>
            </div>
            {{ Form::close() }}
````

**Comment by lstables** [comment]
If i `dd()` the `$request->all()` it does show the `stripeToken` but then displays the following error, like it's trying to update, even though it's a brand new subscription:

````
in Billable.php line 385
at User->updateCard(object(Token)) in SubscriptionBuilder.php line 212
at SubscriptionBuilder->getStripeCustomer('tok_19oWykA5zF9kYK3AAOoQP6YM', array('email' => 'test@email.com')) in SubscriptionBuilder.php line 177
````

**Comment by themsaid** [comment]
Check if the user model has `stripe_id` set already.

**Comment by themsaid** [comment]
Also can you share the full stack trace of the exception?

**Comment by lstables** [comment]
No stripe id as ot was a new subscription and that is basically the stack trace

**Comment by themsaid** [comment]
What's your cashier verison?

**Comment by lstables** [comment]
Latest 7.0 and latest laravel

**Comment by themsaid** [comment]
I'm sorry but everything seems fine to me, testing Spark implementations as well, Forge is using cashier too and all these apps are working fine. I think it's something in your app.

**Comment by lstables** [comment]
But what could it be it's a fresh install of everything and followed docs through, but yet using the strip API directly produces no issues at all.

**Comment by lstables** [comment]
So guessing it's nothing to do with my setup, just tried another complete fresh install with the same versions and settings and still the same error.

**Comment by themsaid** [comment]
Can you put the fresh app in a repo I can clone and check?

**Comment by lstables** [comment]
No, as I just did it to check it wasn't me, sorry! Think I'll do the API direct, just wanted to use Cashier for time saving, but never mind!

**Comment by themsaid** [comment]
@kyranb can you please share more details so I can help?

**Comment by kyranb** [comment]
@themsaid 

Sure thing! Essentially creating a Stripe user like so:

```php

$billableModel->newSubscription('default', $subscriptionId)
                           ->quantity($quantity)
                           ->withCoupon($couponCode)
                           ->create($stripeToken, $this->stripeCustomerMetadata($userMetaData));
```

When the user uses a card that is declined by the bank (but still valid), it is attached to the billableModel, but the subscription is not created.  This leaves the billableModel with a stripe_id and card details, but no associated subscription in the database.

On stripe's side, the customer is represented there, but without a subscription.

I've been solving this, by manually going to stripe, creating a subscription, then entering it in my database manually, not fun at all :/

**Comment by themsaid** [comment]
@kyranb I'm trying to generate the issue but all seems to work fine :/ I'm not sure what it might be.

Regarding your specific case I end up using a stripe test card from https://stripe.com/docs/testing#cards and managed to get a card declined exception, a stripe_id was added to the db but the next attempt to make a subscription using a working card everything works.

**Comment by DaveBagler** [comment]
I ran into the same error and was able to track down my problem.

I set a breakpoint https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L374 and looked at the information I was getting back from Stripe. I had recently deleted some test data from Stripe but as it turns out Spark was holding on to the old Stripe customer id in the stripe_id int the teams table.

It meant that I was just getting a response from Stripe just telling Cashier that the customer was deleted and missing the information Cashier needed. I suggest stepping through that function and taking a look at the response you're getting Stripe.

**Comment by ejlocop** [comment]
i'm having the same issue as well. 

in line [https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L385](https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L385) the `$customer->sources` is null. why is that?

**Comment by lstables** [comment]
Not sure what happened, but I re-installed Cashier and all is good now.

**Comment by ejlocop** [comment]
tried reinstalling `laravel/cashier` and the problem is still there.

**Comment by ejlocop** [comment]
@themsaid

**Comment by josemiguelramirez** [comment]
I had the same issue, you must delete the data related to stripe in the user table,  after reinstalled and test so many different things the only way to activate this , was deleting the data in my table.

**Comment by azamk100** [comment]
josemiguelramirez thank you. Clearing the stripe data from user table did the trick for me:

                // Need to reset all elements here, otherwise newSubscription->create() will throw an exception
                $user->stripe_id = null;
                $user->card_brand = null;
                $user->card_last_four = null;
                $user->trial_ends_at = null;
                $user ->save();

**Comment by socialpilgrim** [comment]
if u r running old version, this thread will help you 
[working fix](https://github.com/laravel/cashier-stripe/issues/1033)
