### ISSUE TITLE
update to require dompdf 0.8 php 7.1

### ISSUE THREAD

**Issue by paulocastellano** [laravel/cashier#383]
Issue on github from dompdf:

https://github.com/dompdf/dompdf/pull/1378

**Comment by aaronhuisinga** [comment]
#382 was just merged and takes care of this. Just waiting on @taylorotwell to release and updated version.

**Comment by paulocastellano** [comment]
@aaronhuisinga thanks

**Comment by alexlopezit** [comment]
Any plan to update to 0.8.1 as per this issue? [dompdf/dompdf/issues/1272](https://github.com/dompdf/dompdf/issues/1272)
