### ISSUE TITLE
Cashier on L5.4 and Valet/PHP7.1 PHP Fatal error

### ISSUE THREAD

**Issue by shealan** [laravel/cashier#385]
Hi there. Added Cashier `"laravel/cashier": "~7.0"` to a virtually new L5.4 project. As soon as I add the service provider to my config.php I get a PHP Fatal error out of memory error killing the whole project. Has anyone else seen this?

**Comment by shealan** [comment]
I've just tried this on a totally fresh L5.4 project. Same happens. As soon as I add the service provider the site is killed dead with a memory error.

**Comment by jcisarano** [comment]
I experienced a similar problem when setting up Cashier, and in my case, it was due to a mistake in how I was registering the service provider. I had:

Laravel\Cashier\CashierServiceProvider,

when I should have been using:

Laravel\Cashier\CashierServiceProvider::class,

Hope that helps.

**Comment by shealan** [comment]
Thank you, that's it! Looks like the 5.4 documentation is incorrect.

```Laravel\Cashier\CashierServiceProvider::class``` works.

**Comment by jcisarano** [comment]
Cool, glad it worked.

**Comment by kalungipatricia** [comment]
Laravel\Cashier\CashierServiceProvider::class doesn't work for me it still brings the same error

**Comment by Harry-Torry** [comment]
This arises when composer is using too much memory and php kills it. Try increasing your RAM allocation on the vm, or doing it straight from the host OS.

**Comment by shealan** [comment]
@Harry-Torry the memory error was erroneous. It was an issue with the way the class was referenced that was causing the out of memory error.
