### ISSUE TITLE
[Braintree] Messed up branch names prevent pulling in latest changes

### ISSUE THREAD

**Issue by faustbrian** [laravel/cashier#387]
Related to https://github.com/laravel/cashier/issues/386 and https://github.com/laravel/cashier/issues/378

Since this PR https://github.com/laravel/cashier-braintree/commit/611d7c7eabb8f11d70f881c88ce578f491451417 to fix those issues has ben merged on https://github.com/laravel/cashier-braintree there was no new release so I wanted to pull in dev-master to get my application live and running again but because the branch aliases are messed up composer always pulls in the dev-master branch from 1 year ago which requries dompdf 0.6.

Both the master and 2.0 branch are aliased as 2.0-dev and no matter if I pull in dev-master or 2.0-dev it will always favor the old version with dompdf 0.6

@taylorotwell Please tag a new release asap for cashier & cashier-braintree.

**Comment by kostaspt** [comment]
@faustbrian If you need a temp fix, make this change in your `composer.json`:

```
{
    "require": {
        ...
        "laravel/cashier-braintree": "dev-patch-2",
        ...
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/kostaspt/cashier-braintree.git"
        }
    ],
}
```

**Comment by faustbrian** [comment]
I am using a local version until this will be fixed, which I hope is soon.

**Comment by faustbrian** [comment]
@taylorotwell @themsaid Any updates on this?

**Comment by faustbrian** [comment]
@taylorotwell Will there be a new release soon that will include this change? https://github.com/laravel/cashier-braintree/commit/611d7c7eabb8f11d70f881c88ce578f491451417

Would rather pull in a stable release than a branch.
