### ISSUE TITLE
Document: Billable trait method createAsStripeCustomer()

### ISSUE THREAD

**Issue by scottgrayson** [laravel/cashier#388]
https://laravel.com/docs/5.4/billing

https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L530

This method is useful if you want to add a card before subscribing.  Or if you want to have some customers that have cards but no subscriptions. Source code is easy to understand but more people should know about this.

**Comment by driesvints** [comment]
Sent in a pr for this: https://github.com/laravel/docs/pull/4622
