### ISSUE TITLE
Coupon is marked as used even if payment is declined/fails

### ISSUE THREAD

**Issue by gomako** [laravel/cashier#389]
A customer may fill in a payment form incorrectly, not have enough funds etc. If they use a valid coupon, then using the following method marks the coupon as used (or increments the use count) then errors on the card.

    try {
        if ($coupon) {
            $this->user->newSubscription('default')
                ->withCoupon('ABC123')
                ->create($request->get('stripeToken'));
        }
    } catch (\Stripe\Error\Card $e) {
        return redirect()->back()->with(['error' => $e->getMessage()]);
    }

The user can try again but the coupon may not be valid if it's a limited use one.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
