### ISSUE TITLE
Cashier totally broken in Laravel 5.4?

### ISSUE THREAD

**Issue by shealan** [laravel/cashier#390]
I have tried to add Cashier to a fresh Laravel 5.4 install on the latest Valet and the latest Homestead.

It instantly kills both when the Cashier service provider is added to my config.php.

Can anyone else confirm they have Cashier working on a Laravel 5.4 install?

**Comment by shealan** [comment]
Turns out that the L5.4 documentation is slightly inaccurate. You should register the service provider in config.php with ```Laravel\Cashier\CashierServiceProvider::class``` to avoid killing your project. Note the ```::class``` on the end.

**Comment by chafreaky** [comment]
You can either add 
`Laravel\Cashier\CashierServiceProvider::class` 
or 
`"Laravel\Cashier\CashierServiceProvider"`
to your `config/app.php` file.

I believe the documentation let's you make your own choice by just asking to register the provider.

**Comment by shealan** [comment]
Without ```::class``` it broke the site every time on multiple machines and sites.

**Comment by mcteo** [comment]
Is this a duplicate of #385 ? If so, why not add a pull request for the documentation (found [here](https://github.com/laravel/docs/blob/5.4/billing.md)), rather than opening a new bug?

**Comment by markwalet** [comment]
Absolutely. This isn't a bug..

Please close this issue.

**Comment by shealan** [comment]
Sorry guys. Pull request for docs done and issue closed. 👍🏼
