### ISSUE TITLE
FastSpring implementation

### ISSUE THREAD

**Issue by markvital** [laravel/cashier#391]
Is there any way to integrate Laravel Cashier with [FastSpring](http://fastspring.com/) payment system? https://github.com/FastSpring/fastspring-api

**Comment by fgambino** [comment]
Note that they have a new API for their new storefront:
https://docs.fastspring.com/integrating-with-fastspring/fastspring-api

**Comment by habibworld** [comment]
how do i implement Fastspring on Laravel?? please help meeeeeeee

**Comment by mlantz** [comment]
I think you'll have to implement your own system to work with FastSpring, Cashier only works with Stripe and Braintree there is no assurance the API wrappers would work nicely with the implementation here.

**Comment by markvital** [comment]
Thank you!

**Comment by bgultekin** [comment]
Late more than a year :) but I created a package for this. People who come from google can check https://github.com/bgultekin/cashier-fastspring .

**Comment by markvital** [comment]
@bgultekin Wow, thank you so much!
