### ISSUE TITLE
Simple charge without subscription

### ISSUE THREAD

**Issue by paulocastellano** [laravel/cashier#392]
Will be great if can charge customers without subscription in cashier.

**Comment by feeekkk** [comment]
https://laravel.com/docs/5.4/billing#single-charges

**Comment by ConsoleTVs** [comment]
I think they still require to be subbed (or at least they need to go through the create method implemented in the subscription method)

**Comment by MichaelHoughton** [comment]
@paulocastellano - if you are still looking for this feature, consider trying Coderity Wallet - it extends Cashier and has this feature:

https://github.com/coderity/wallet#charging-without-a-subscription

**Comment by SomethingWrong** [comment]
This worked pretty good for me without subscription (I don't have any tables for subscriptions or so): 

`$user->charge($amount * 100, ['source' => $token]);`

Where `$user` is simple instance of `User` which uses Cashier's `Billable` trait and `$token` is Stripe token which I received during client-side checkout process.

For more info just check the [`charge()` method](https://github.com/laravel/cashier/blob/534049509cdd483c5a685bd08adea49789a4a133/src/Billable.php#L38) of `Billable` trait to understand how it works exactly.

**Comment by driesvints** [comment]
Think this was answered with the answers above. Thanks everyone!
