### ISSUE TITLE
Fleshing out payment models + adding new payment providers.

### ISSUE THREAD

**Issue by mcteo** [laravel/cashier#395]
Hi, I love the idea of unifying multiple underlying payments SDKs to allow for easy swapping between providers.

I noticed the following in the docs:
> If you're only performing "one-off" charges and do not offer subscriptions, you should not use Cashier. Instead, use the Stripe and Braintree SDKs directly.

Are there any plans on changing this? (i.e. supporting one-off charges?) I am creating a web application at the moment and I think something like KickStarter's payments model would be most similar - people pay arbitrary sums, and they can be withdrawn by the user whenever.

Also, would you be open to adding more payments providers?

**Comment by inxilpro** [comment]
Take a look at https://github.com/laravel/cashier/pull/423 — I'd love feedback.

**Comment by driesvints** [comment]
At the moment it's too much work to review large PRs like this but I can see this being useful. It'll be difficult however to sync functionality between multiple providers. I'll mark this as a feature request for the time being.

**Comment by driesvints** [comment]
Going to close this one as Cashier now implements Stripe charges and we're not planning on adding any other payment providers.
