### ISSUE TITLE
Handling multiplan subscriptions at Stripe

### ISSUE THREAD

**Issue by jurihub** [laravel/cashier#397]
Stripe handles multiple plans included in one subscription (they are subscription items).
This is useful because this way the customer will see only one debit on their bank account for every billing cycle instead of seeing one for every subscribed plan. Eg. if your customer is subscribed to a main service plus 4 features, they will get 5 debits every month. This is bad for service providers because (a) it is ugly (b) it is more expensive due to the fix fees.
For more details, cf. https://stripe.com/docs/subscriptions/multiplan

Implementation ideas:

- Similarly to the Subscription class, the SubscriptionItem class should be created to handle the plans included in the subscription.

- The MultisubscriptionBuilder class, extending the SubscriptionBuilder class, should be created to handle the creation process including multiple plans.

- New methods should be added to the Billable trait and to the Subscription class to check if the user is on a given plan when it is included in a multiplan subscription.

- The unit test should be appended to handle the new scenarios.

**Comment by joegarbett** [comment]
Is it possible for someone to review this? Else I will implement it myself?

**Comment by jurihub** [comment]
FYI we created a pull request for this issue and we've been using our fork successfully since than ( https://github.com/laravel/cashier/pull/398 ). We've also added SEPA Direct Debit as a new payment method recently.

**Comment by timothyallan** [comment]
@jurihub Is your fork working with 5.5? I'm quite keen to get multiple plans going.

**Comment by jurihub** [comment]
We didn't test it under 5.5 yet. But it should work

**Comment by educolo** [comment]
Someone tested this on Laravel 5.5 ?
I didn't see any news on the official package also

**Comment by user3579** [comment]
hi @jurihub , can you describe how to use your fork for multiplan subscription? thanks.

**Comment by Abhi0725** [comment]
@taylorotwell Please accept this pull request.

**Comment by driesvints** [comment]
We're still open for PRs for this.

**Comment by tanthammar** [comment]
@taylorotwell please implement this

**Comment by gvnn** [comment]
This feature will be also useful for testing with https://github.com/stripe/stripe-mock which provides a quick mock http server. Currently requests to the subscription endpoint is rejected because `plan` and `quantity` properties are not allowed.

**Comment by basepack** [comment]
@taylorotwell @driesvints Any update on this PR, maybe it now fits in Cashier better?

**Comment by driesvints** [comment]
Unfortunately not. Currently focusing on the upcoming v10 and SCA compatibility.

**Comment by mwienk** [comment]
@driesvints any updates on this? It looks like `items` is a required field on the subscription creation: https://stripe.com/docs/api/subscriptions/create, does that mean it can be added?

**Comment by samuelhautcoeur** [comment]
@taylorotwell @driesvints Also very interested in this. Please consider it.

**Comment by signvikas** [comment]
@taylorotwell Please accept this pull request.

**Comment by taylorotwell** [comment]
Locking to get rid of additional "please do this" comments which are just clutter.

**Comment by driesvints** [comment]
It has begun: https://github.com/laravel/cashier/pull/900

**Comment by driesvints** [comment]
The PR got merged and will be in v11
