### ISSUE TITLE
Can we use cashier for strip connect as well? Not just for stripe but for stripe connect too ?

### ISSUE THREAD

**Issue by wasifiqbal1990** [laravel/cashier#399]
I want to use stripe connect on laravel so let me know if I can use that using laravel cashier.

**Comment by zhaklinab** [comment]
So, any answer for this one?

**Comment by DevinWalker** [comment]
+1

**Comment by driesvints** [comment]
The PR for Stripe Connect functionality was rejected so closing this because atm we have no plans of supporting it.
