### ISSUE TITLE
[Request] Config option to override Subscription model default connection

### ISSUE THREAD

**Issue by bickle66** [laravel/cashier#401]
I'm not sure if there is already a way to do it built in but it would be great if I could override the database connection that Subscription.php model is pointing to with a `config/cashier.php`.

with:
`[
  'connection' => 'new_db'
]`

I see this was already suggested in https://github.com/laravel/cashier/issues/313

**Comment by mlantz** [comment]
Technically you could override the `Subscription::class` with your own reference in the Model. For example if you put `App\CustomSubscription as Subscription;` then you can just extend the base Subscription Model which Cashier provides

**Comment by robertholf** [comment]
+1

**Comment by driesvints** [comment]
This seems very specific to your use case. I don't see this being added to Cashier anytime soon, sorry. You can always override stuff or release your own fork.
