### ISSUE TITLE
[question] Stripe ACH support

### ISSUE THREAD

**Issue by jamesgraham** [laravel/cashier#402]
Has anyone successfully integrated this as a payment method?

**Comment by spenserhale** [comment]
I am also curious if anyone has.

**Comment by nara-l** [comment]
Still curious about this implementation. No one?

**Comment by nickparker39** [comment]
When you pass a token into the `create()` function, the Billable trait automatically determines whether it is a card or a bank account. Stripe handles the rest on their end. See: https://github.com/laravel/cashier/blob/7.0/src/Billable.php#L458

You can generate an ACH token by following the Stripe.js docs: https://stripe.com/docs/stripe-js/reference#stripe-create-token 

```js
stripe.createToken('bank_account', {
  country: 'US',
  currency: 'usd',
  routing_number: '110000000',
  account_number: '000123456789',
  account_holder_name: 'Jenny Rosen',
  account_holder_type: 'individual',
}).then(function(result) {
  // Handle result.error or result.token
});
```

**Comment by driesvints** [comment]
Gonna close this in favor of https://github.com/laravel/cashier/issues/402

Thanks for reporting.

**Comment by jamesgraham** [comment]
@driesvints 402 is this same ticket?

**Comment by driesvints** [comment]
@jamesgraham ah sorry man. I meant https://github.com/laravel/cashier/issues/507.

**Comment by ColinLaws** [comment]
By the way, yes I did implement ACH successfully. I used a service called Plaid that integrates with your Stripe account. They provide you with front-end components that you can drop into your page that make calls securely to their API and allow users to log into their banks and select an account to pay with. Then a stripe token is passed back and can be used exactly like a stripe token generated with a card. 

There are some limitations to simply handing off the ACH account's stripe token. Currently, Cashier is biased towards only returning cards and not bank accounts. The underlying Stripe API object returns payment sources as single array, and Laravel is intentionally filtering out sources marked as being a card. This is where you will likely need to either modify Cashier or just consume the Stripe API objects and working around Cashier.

If I get time, I will look into making this change to Cashier myself.

**Comment by astora367** [comment]
@ColinLaws Any progress on this change to accept ACH payments in Cashier? I'm looking to make ACH payments the default method of payment for my web app and am torn that Cashier doesn't have this yet.
Like it says on Stripe's ACH Guide, the user would verify their account through Plaid and then I should be able to process it from there.
If there's no immediate update for this feature soon, any advice on what I need to modify Cashier or use Cashier as my main billing interface and digest Stripe's API another way? Thanks!

**Comment by driesvints** [comment]
@astora367 The Stripe Payment Methods API (which is used in Cashier) doesn't supports this yet: https://stripe.com/docs/payments/payment-methods

**Comment by ColinLaws** [comment]
@astora367  Throughout Cashier, when interacting with payment sources on a customer, Cashier specifies that the type of object to retrieve from the sources list is of type 'Card'.

Instead of pulling payment sources through Cashier, I wrote my own code in user land to pull a list of sources including bank accounts. Below is an example (in cashier\src\Billable.php) of the 'cards' function on the billable trait. Instead of using this method to pull payment sources, I wrote my own functions on my Billable model to pull bank accounts as well. 

```php
/**
     * Get a collection of the entity's cards.
     *
     * @param  array  $parameters
     * @return \Illuminate\Support\Collection
     */
    public function cards($parameters = [])
    {
        $cards = [];

        $parameters = array_merge(['limit' => 24], $parameters);

        $stripeCards = $this->asStripeCustomer()->sources->all(
            ['object' => 'card'] + $parameters
        );

        if (! is_null($stripeCards)) {
            foreach ($stripeCards->data as $card) {
                $cards[] = new Card($this, $card);
            }
        }

        return new Collection($cards);
    }
```

Also, thanks for the update @driesvints

**Comment by ankurk91** [comment]
@driesvints
https://stripe.com/docs/billing/subscriptions/ach-debit

Stripe officially support for subscription with ACH direct bebit using payment intents

**Comment by driesvints** [comment]
@ankurk91 all payment methods should already be covered in the latest Cashier.
