### ISSUE TITLE
Calling cancelNow() while on trial results in incorrect subscribed() result

### ISSUE THREAD

**Issue by gbradley** [laravel/cashier#403]
If a user is on their trial period and `cancelNow()` is used to cancel their subscription immediately, the subscription's `onTrial()` still returns `true`. This means that `subscribed()` also returns `true`, which I wouldn't expect as the subscription ended "now" rather than at the end of the trial.

**Comment by jaketoolson** [comment]
@gbradley see this: https://github.com/laravel/cashier/issues/319

For some reason they are ignoring it still :(

**Comment by FPGL** [comment]
Hi,

Did you try `skipTrial()`?

**Comment by driesvints** [comment]
Actually this is the correct and wanted behavior. `cancelNow` only implies that you want your subscription to be cancelled immediately and not, for example, at the end of its period. Trials have nothing to do with this. If a user is still on its trial then it will simply continue unless you explicitly also call `skipTrial` like @FPGL suggested above. Hope this clarifies things.

**Comment by gbradley** [comment]
@driesvints I can see the logic for not affecting the trial by default, although it remaiins odd to me that the result of `subscribed()` can still be true after cancelling. Anyway, thanks for clarifying the intended behaviour :)
