### ISSUE TITLE
Bump cashier-braintree

### ISSUE THREAD

**Issue by andrewklau** [laravel/cashier#408]
Issue tracking seems to be disabled on cashier-braintree 

Could we please get a release for https://github.com/laravel/cashier-braintree/commit/611d7c7eabb8f11d70f881c88ce578f491451417

**Comment by logan-jobzmall** [comment]
Agreed. Cashier-braintree needs to be updated to include all the date inconsistencies (now vs today, etc) and everything else. @taylorotwell any ideas about the complexity of this?

**Comment by mkarnicki** [comment]
Hi @logan-jobzmall . I'm looking into using Cashier. What inconsistencies did you exactly mean?

PS Taylor informed me he doesn't work on issues on OS projects, so if you'd like to get this improved, it's best to help and send in a PR.

**Comment by logan-jobzmall** [comment]
@mkarnicki - Specifically [this ticket](https://github.com/laravel/cashier/issues/319) and [this ticket](https://github.com/laravel/cashier/issues/466) - although the original was closed, there was a PR that fixed some of the issue people were seeing specifically [here](https://github.com/laravel/cashier/pull/60)

Thanks for the information! Good to know that.

**Comment by mkarnicki** [comment]
Hey @logan-jobzmall , thanks for detailed response! Yes, I see it would make sense to address those with a PR (one that would hopefully get approved). I would agree with other commenters these cashier behaviors would seem inconsistent (or even cause errors in Stripe). Thank again.

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
