### ISSUE TITLE
Custom options on subscription creation

### ISSUE THREAD

**Issue by tomhughes-invento** [laravel/cashier#410]
Recently I needed to support Connect's application fee system in Cashier in order to properly support a large feature we were working on for 1 of our products. Part of this involved applying an application_fee_precent to the create() method (we needed flat fees, but for whatever reason Stripe doesn't support applying flat application fees on a subscription, so we had to work out the percentage required to hit the correct fee).

Part of this change meant extending the create method in SubscriptionBuilder.php to support this. Rather than simply adding the application_fee_percent to the buildPayload() method I opted to extend its flexibility by accepting an option array of data from the user via a third argument in create() and merged it with the existing array there (allowing keys set in the builder to override anything sent in by the call.

```
protected function buildPayload(array $subscriptionPayload = [])
{
    return array_filter(array_merge($subscriptionPayload, [
        'plan' => $this->plan,
        'quantity' => $this->quantity,
        'coupon' => $this->coupon,
        'trial_end' => $this->getTrialEndForPayload(),
        'tax_percent' => $this->getTaxPercentageForPayload(),
    ]));
}
```

This is a small enough change, however helps increase the flexibility of creating subscriptions with things that aren't directly supported by Cashier (like Connect)

**Comment by driesvints** [comment]
The PR for Stripe Connect functionality was rejected so closing this because atm we have no plans of supporting it.
