### ISSUE TITLE
cashier-braintree default payment method

### ISSUE THREAD

**Issue by antongorodezkiy** [laravel/cashier#413]
Issue tracker on braintree-cashier is disabled, so asking here.

Maybe I understood something wrong, but when I tested code on the line https://github.com/laravel/cashier-braintree/blob/2.0/src/Billable.php#L33 it returns first payment method and not the default one.

Is it by design? For me it seems to be more correct if we can use default payment method there. To achieve that case we can search it by `default` property:

```
Braintree\PayPalAccount (1) (
        protected _attributes -> array (12) [
            'billingAgreementId' => NULL
            'createdAt' => DateTime (3) (
                public date -> string (26) "2017-06-09 13:14:41.000000"
                public timezone_type -> integer 3
                public timezone -> string (3) "UTC"
            )
            'customerId' => string (8) "123"
            'default' => bool TRUE // this one
...
```

My use case is the following:
I've used braintree-cashier with Laravel Spark and when I've changed the payment method it still charges the previous one.

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
