### ISSUE TITLE
School manager system 

### ISSUE THREAD

**Issue by amine8ghandi8amine** [laravel/cashier#428]
![errore cashier](https://user-images.githubusercontent.com/18240387/28220756-9239f3f4-68b8-11e7-87a7-ad88af07a16f.png)

**Comment by amine8ghandi8amine** [comment]
no one to help????

**Comment by talevskiigor** [comment]
Error is not related to Cashier it self, this just tells you: you need to implement the methods when you use extend ... if you are switch to PHPStorm it will tell warn you for this error even during you write the code, no need to open the browser to see the error.

**Comment by amine8ghandi8amine** [comment]
if you are in my place and yu dont have php storm what you could do step by step

**Comment by kyranb** [comment]
Cashier a été conçu pour les abonnements, j'ai l'impression que vous ne les besoin pas?

Au lieu de cela, je vous recommande d'utiliser ce package:  https://github.com/cartalyst/stripe-laravel

**Comment by talevskiigor** [comment]
@amine8ghandi8amine just open BilableContract and implement the methods ...

**Comment by amine8ghandi8amine** [comment]
thankyou @talevskiigor  and @kyranb 
i will see what i can do

**Comment by MichaelHoughton** [comment]
@amine8ghandi8amine - feel free to close this ticket if your issue is resolved.
