### ISSUE TITLE
Database field name proposal

### ISSUE THREAD

**Issue by flarpy** [laravel/cashier#434]
Thanks for Cashier, makes subscriptions a breeze

In the subscriptions table is a field called "ends_at". I suggest this should be renamed "ended_at" so that it reflects accurately what it is ie, it is only populated if the subscription has ended and also stripe nomenclature

https://stripe.com/docs/api/php#subscription_object
> ended_at
timestamp
If the subscription has ended (either because it was canceled or because the customer was switched to a subscription to a new plan), the date the subscription ended.

**Comment by Remo** [comment]
@flarpy it's a bit tricky because you can cancel a subscription at the end of its period. In that case the value in `ends_at` will be in the future. Either way, the name can be misleading.

**Comment by driesvints** [comment]
You can atm fill this in to end in the future and still be on a grace period so this is actually a good way to describe it. But thanks for the suggestion.
