### ISSUE TITLE
Request: Allow subscription using stripe card source ids

### ISSUE THREAD

**Issue by emergingdzns** [laravel/cashier#436]
I would like to be able to create a subscription for a user that already has a default card source on file with Stripe (same for braintree and other services that store cards)..

For example, we have customers that have subscriptions. We want to allow them to add on additional subscriptions. We could do this by requiring them to re-enter their card numbers. But I'd like to allow them to select an existing card source (which I would pull from Stripe and show the last 4 numbers so they can select the right one) and then add a new subscription using the card id rather than the card token.

Can this be added to Cashier?

**Comment by mydnic** [comment]
Actually I believe you can by calling ->newSubscription('main', 'the-new-plan-id')->create()

You simple have to leave the ->create() empty

**Comment by shadle10** [comment]
@mydnic is right; I just tested this out with Laravel 5.4 and Cashier ~6.0.

**Comment by driesvints** [comment]
Yeah you can just create a new subscription without passing a token if you already have set a card.
