### ISSUE TITLE
[Proposal] Re-add billing_cycle_anchor support

### ISSUE THREAD

**Issue by joshuadwire** [laravel/cashier#439]
I noticed that `billing_cycle_anchor` is no longer settable through Cashier. #394 mentions that `billingCycleAnchor` is outdated, being replaced by setting `trial_date`, but this does not handle automatic proration like `billing_cycle_anchor` does.

As far as I know, `billing_cycle_anchor` is the only parameter that gets Stripe to move the billing cycle date and automatically calculate the proration amount. I checked with Stripe, and it's still a supported parameter for this use case:

> While the `billing_cycle_anchor` parameter is still undocumented, this is an accepted way to set the billing date of a subscription. That said, you should only use this parameter if you know what you're doing it, and how it works.
>
> If you've already an understanding of this parameter - which you likely do by discovering this! - then you can by all means use this to set the start date of a subscription and handle proration automatically, without needing to build logic on your end like you would otherwise need to.

My particular use case is to get two different subscriptions started at different times to line up for the same renewal date. Would a pull request to implement this be welcomed?

**Comment by garygreen** [comment]
If your interested, I made a console command which synchronises the renewal date for all your subscription (e.g. the start of when Stripe when next create an invoice/bill the customer). It's a shame Cashier doesn't set this internally when creating a subscription, as you often rely on it to know when to downgrade an account / stop services to a user. Hopefully this helps you 👍 

https://gist.github.com/garygreen/fb4dc0288e2c57f9af015968ff7019bb

**Comment by driesvints** [comment]
You can use the `anchorBillingCycleOn` on a subscription which will be set when swapping plans. This indeed documented but welcoming PRs to add this to the docs.
