### ISSUE TITLE
Laravel 5.5 cashier test subscriptions with short trial

### ISSUE THREAD

**Issue by htchtc052** [laravel/cashier#440]
I tested web site subscriptions users through stripe.   Website uses php laravel 5.5 with cashier on linux server.

How to make a short grace period for tests?

I use this code:

        $user->newSubscription('main', $request->get('subs_type'))
          ->trialUntil(Carbon::now()->addSeconds(330))
          ->create($request->get('stripeToken'), [
            'email' => $user->email,
        ]);
        
        
instead of the usual

        $user->newSubscription('main', $request->get('subs_type'))
          ->trialDays(1)
          ->create($request->get('stripeToken'), [
            'email' => $user->email,
        ]);

But after the end of the short trial laravel cashier method onTrial() returns true. Since the method compares dates, not hours or minutes. 
        
         /**
         * Determine if the subscription is within its trial period.
         *
         * @return bool
         */
        public function onTrial()
        {
            if (! is_null($this->trial_ends_at)) {
                return Carbon::today()->lt($this->trial_ends_at);
            } else {
                return false;
            }
        }

Are there any practices that will correct this.

Of course, I do not want to edit the source of laravel cashier

**Comment by sagar-mi** [comment]
Yes, You can change trial_ends_at field after this 

$user->newSubscription('main', $request->get('subs_type'))
      ->trialDays(1)
      ->create($request->get('stripeToken'), [
        'email' => $user->email,
    ]);
$user->trial_ends_at = "Your date & TIme"

**Comment by driesvints** [comment]
Think this will be solved when https://github.com/laravel/cashier/issues/440 is fixed. Thanks for reporting.
