### ISSUE TITLE
[Composer] Ambiguous class resolution

### ISSUE THREAD

**Issue by unckleg** [laravel/cashier#444]
`Warning: Ambiguous class resolution, "Laravel\Cashier\Cashier" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/Cashier.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/Cashier.php", the first will be used.

Warning: Ambiguous class resolution, "Laravel\Cashier\CashierServiceProvider" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/CashierServiceProvider.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/CashierServiceProvider.php", the first will be used.

Warning: Ambiguous class resolution, "Laravel\Cashier\Billable" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/Billable.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/Billable.php", the first will be used.

Warning: Ambiguous class resolution, "Laravel\Cashier\Subscription" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/Subscription.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/Subscription.php", the first will be used.

Warning: Ambiguous class resolution, "Laravel\Cashier\Invoice" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/Invoice.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/Invoice.php", the first will be used.

Warning: Ambiguous class resolution, "Laravel\Cashier\SubscriptionBuilder" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/SubscriptionBuilder.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/SubscriptionBuilder.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Http\Controllers\WebhookController" was found in both "/opt/lampp/htdocs/ugc/vendor/laravel/cashier-braintree/src/Http/Controllers/WebhookController.php" and "/opt/lampp/htdocs/ugc/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php", the first will be used.
`

How should I install both Stripe & Braintree together ?

**Comment by MichaelHoughton** [comment]
@unckleg - I don't actually think this is currently supported - or at least, I am curious why you need to do this!

It is possibly a Composer Issue - see: https://github.com/composer/composer/issues/4195

**Comment by unckleg** [comment]
It is not "a Composer issue", the class map is invalid. 

There are two "Cachier" classes under same namespace (directory/composer. and we should not agitating for why someone would use both packages.

This is the problem of the package that needs to be fixed.

**Comment by mirzabusatlic** [comment]
+1 I'm trying to explore if it's possible to use Cashier (Stripe) & Cashier (Braintree) together. Running into the same namespace collision problem. I want to use Stripe for credit card processing but Braintree for it's PayPal integration only...

**Comment by unckleg** [comment]
The only solution for this problem is to change the composer packages class map, and it's requires more in depth refactor process.

**Comment by mirzabusatlic** [comment]
I ended up creating a console command that runs before composer autoload dumps and appends a sub-namespace to each of the composer packages. I now have two different namespaces:
```php
Laravel\Cashier\Stripe;
Laravel\Cashier\Braintree;
```

Use it yourself:
https://gist.github.com/mirzabusatlic/494e592c29ec965d5428e9e226d6fdaf

**Comment by pavlo04** [comment]
Hi @mirzabusatlic! Thank you for script. Can you please clarify how to use it properly? I use it in my User model in following way:
`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Cashier\Stripe;
use Laravel\Cashier\Braintree;


class User extends Authenticatable
{
    use Notifiable;
    use Braintree;
    use Stripe;
...`

And get this:
TRAIT 'LARAVEL\CASHIER\BRAINTREE' NOT FOUND

Thanks in advance

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues

**Comment by wadewtwt** [comment]
仔细看看你Ambiguous class resolution报的文件路径在哪儿，看用的上吧，用不上就删了吧
