### ISSUE TITLE
createAsStripeCustomer not saving via User Model.

### ISSUE THREAD

**Issue by testuser890880** [laravel/cashier#453]
Cashier/src/Billable.php, 
createAsStripeCustomer($token, array $options = [])

$this->stripe_id = $customer->id; //<- Is setting the stripe customer ID.
$this->save(); //<- returns true but database not updated. No error's.

Using Laravel 5.5.

**Comment by testuser890880** [comment]
Just did another test to check that it's not the model:
The test below works outside of the Cashier/src/Billable.php but not within.

use App\Model\User;

$user = User::find(1);
$user->stripe_id = 'Test 123';
$user->save();

**Comment by testuser890880** [comment]
This may not be related to Cashier. It also seems $this->save() is not working within models.

**Comment by MichaelHoughton** [comment]
Can you confirm if you have set the $fillable attribute in your model?

**Comment by testuser890880** [comment]
protected $fillable = [
	'username',
	'email',
	'password',
	'stripe_id',
	'card_brand',
	'card_last_four',
	'trial_ends_at'
];

I am able to update a user model using save() from a controller, but when using save() within the trait Billable, the DB fields are not being undated (just remain null). Oddly, it is returning true and the $customer->id (stripe_id) can be seen in the user object after it has been saved. 

I'm also unable to save within any mode using $this->save(), so something is at miss here. I'm assuming as the Billable is an instance of the user and that is a model. then maybe being unable to save within a model is creating the problem.

I'm going to do a test now on a fresh install to wok out what is creating issue.

**Comment by testuser890880** [comment]
Its not Cashier, I just tested, can close this if you like.

**Comment by MichaelHoughton** [comment]
@testuser890880 - you should be able to close this yourself, as you created the initial ticket!
