### ISSUE TITLE
UpdateCard Method Not Working

### ISSUE THREAD

**Issue by sagar-mi** [laravel/cashier#458]
$sub->updateCard($token); is returning
this error "could not determine which URL to request: Stripe\Token instance has invalid ID",
I am already passing stripe token but i don't understand whats going wrong.

**Comment by MichaelHoughton** [comment]
@sagar-mi - does the user have an existing subscription?

**Comment by sagar-mi** [comment]
Yes

**Comment by MichaelHoughton** [comment]
@sagar-mi - can you share the $token variable - are you passing just the token ID there?  That is all you need to pass - so not the full object, just the token string.

**Comment by sagar-mi** [comment]
Yes i am just passing String token.

**Comment by MichaelHoughton** [comment]
@sagar-mi - OK - the way a token is generated is somewhat outside the scope of Cashier.  It might be easier to create the token on the server side - but I don't know if that is outside the scope of your requirements.

**Comment by sagar-mi** [comment]
But i dont understand why isit necessary to use form.get(0).submit for submit the form?

**Comment by sagar-mi** [comment]
I have solved it By added different on click event and pass value through hidden field.
