### ISSUE TITLE
Can not update default card details anymore

### ISSUE THREAD

**Issue by ahalimkara** [laravel/cashier#460]
This might be a rare case but it happened today for me, so i just want to share here maybe it worth to check. When creating Stripe customer:
```php
Auth::user()->createAsStripeCustomer($token);
```
It created Stripe customer, card and associated them on Stripe but failed to update `card_brand` and `card_last_four` columns at my database. So when i call `Auth::user()->updateCard($token);` for same user it never updates because of following control:
```php
if ($token[$token->type]->id === $customer->default_source) {
  return;
}
```

In case of database connection problem or something else when card details could not be updated on database, is it possible to add a new check inside control as:
```php
if ($token[$token->type]->id === $customer->default_source) {
  if (! $this->card_brand)
    $this->fillCardDetails($token[$token->type])->save();
  return;
}
```

I am using Laravel 5.5 with Cashier 7.0

**Comment by sagar-mi** [comment]
I think this problem occur because you are adding same card.

**Comment by ahalimkara** [comment]
Yes same card, but still there must be a way to update `card_brand` and `card_last_four` columns when calling `updateCard`.

**Comment by sagar-mi** [comment]
@ahalimkara what is mean of update same card? updateCard method only update value if the card was different from the last one.

**Comment by ahalimkara** [comment]
In my first post, the problem was to unable to update database (card created and associated with customer at Stripe successfully). So user might use same card for purchase etc. but i will never set default card for customer in my database if i fail to add to database in first purchase. Or i need to do it manually. I just thought it might be good to have an extra check in `updateCard` method.

**Comment by sagar-mi** [comment]
@ahalimkara Cashier manage everything if you go with proper documentation, whenever you create new subscription with this method

`$user->newSubscription('main', 'premium')->create($stripeToken);`

it will automatically did entry on database and same in the case whenever you updateCard method it will automatically update your card and make new card as default card and next time user won't need to purchase the subscription after plan expired , its automatically renewed if user won't cancel their subscription and if user cancel subscription and want to resume again than you can resume it with resume method if user is still Grace period, in short there is everything available in cashier, for more details read document.

https://laravel.com/docs/5.5/billing

**Comment by ahalimkara** [comment]
Thank you @sagar-mi for information. The problem was not about usage of Cashier, it was just a suggestion and I think contributors understood what it is.

**Comment by Iphoning** [comment]
Have the save issue. User was associated with stripe, but card_last_four and card_brand have null values. How it is possible?

**Comment by driesvints** [comment]
The card brand and last four should always be filled. If not, it seems that there was a hiccup on your end. You can always use the `updateCardFromStripe` to sync the card details again from Stripe.
