### ISSUE TITLE
calculate expirey date for stripe subscription

### ISSUE THREAD

**Issue by keyurpraj** [laravel/cashier#461]
first time subscribe for stripe and that my plan expired date and time so how do i calculate in laravel 5.4?

**Comment by spikerok** [comment]
I think you are looking for:
https://laravel.com/docs/5.4/billing#defining-webhook-event-handlers

Essentially when Stripe bills subscription event will be called, Stripe will send an object across. Refer to the link below for the object structure:
https://stripe.com/docs/api#invoice_object

I think you are looking for 
""period": {
          "start": 1512086285,
          "end": 1514678285
        },"

**Comment by keyurpraj** [comment]
i think bellow code use for expire date 
$user->subscription('main')->current_period_end

**Comment by keyurpraj** [comment]
webhook call autometically handle event

**Comment by keyurpraj** [comment]
I have get current_period_end for '1512086285' but i need to full date format

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
