### ISSUE TITLE
stripe subsscribe 

### ISSUE THREAD

**Issue by keyurpraj** [laravel/cashier#463]
i have create a stripe subscribe plan first create customer and then charge card then customer to subscribe  but how to calculate the subscribe is expire.

- customer store card and subscribe ongoing but problem is customer is remove existing card and add new card so when customer subscribe complete or not please give me a answer.

**Comment by sagar-mi** [comment]
@keyurpraj No, Subscription will not be cancel if you change card and make new card as default one than next time charge will be deducted from that new card and you can check whether subscription is end or not 
with subscribed method.
if ($user->subscribed('main')) {
    //
}

for further information read document : https://laravel.com/docs/5.5/billing

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
