### ISSUE TITLE
onTrial() - replace Carbon::today() with Carbon::now()

### ISSUE THREAD

**Issue by enkay** [laravel/cashier#466]
This issue has been brought up before and closed because it's the intended behavior. Bug or not, this intended behavior breaks Cashier and is inconsistent with other time checks in the package.

Currently, the following line is used to determine whether a subscription is on a trial.
return Carbon::today()->lt($this->trial_ends_at);

If a user is on a trial and tries to swap their plan on the day their trial expires (and after the time in the day when it expires), Cashier Subscription's swap method will use the above method to determine if the user is on trial. Because this will return true, it will try to pass a trial_end timestamp in the past which errors out on Stripe's API.

If people want to give their trial users until the end of the day, that should be on them to override Cashier to support that behavior. There's no reason to have an imprecise date check that breaks the package as intended behavior.

Thanks for considering!

Previous issue: https://github.com/laravel/cashier/issues/319

**Comment by driesvints** [comment]
Heya. After discussing this with the rest we agree this can be changed. Accepting PRs for this, otherwise I'll send in one myself later.

**Comment by driesvints** [comment]
This is apparently already fixed on 5.7, just not implemented on master.
