### ISSUE TITLE
[Question] Braintree Subscription

### ISSUE THREAD

**Issue by waferstick** [laravel/cashier#467]
Can I subscribe a product instead of a user?

Just like digitalocean, when creating a droplet it automatically subscribe the user for creating a droplet.

Can I do that with cashier braintree?

**Comment by bbashy** [comment]
Question: have you tried adding the trait to that model?

**Comment by waferstick** [comment]
@bbashy, Yes I've tried that but it throws an exception when I try an subscribe the product

Controller
`
$product = Product::create([
    'name' => str_random()
]);

$product->newSubscription('Name', 'Plan')->create('fake-valid-nonce');
`

Exception
`
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'product_id' in 'field list' (SQL: insert into `subscriptions` (`name`, `braintree_id`, `braintree_plan`, `quantity`, `trial_ends_at`, `ends_at`, `product_id`, `updated_at`, `created_at`) values (Name, jft7f6, Plan, 1, , , 1, 2017-11-08 11:54:24, 2017-11-08 11:54:24))
`

**Comment by bbashy** [comment]
@waferstick Change `user_id` to `product_id` then?

**Comment by waferstick** [comment]
@bbashy I'm going to also subscribe a job post. So maybe a polymorphic relations?

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
