### ISSUE TITLE
Bump DOMPDF version to resolve "No block-level parent found. Not good." error when using <head>

### ISSUE THREAD

**Issue by andyrobertscarpediem** [laravel/cashier#471]
When downloading an invoice, No block-level parent found. Not good. is thrown if the HEAD is present in the invoice template.

Example:
https://github.com/barryvdh/laravel-dompdf/issues/389

Fix has been committed below:
https://github.com/dompdf/dompdf/commit/ad41b6dd17ba774b017407ffba09c14a66665723

**Comment by SuperKiwi** [comment]
Same issue here. But Cashier requires dompdf `7.0.0` so I cannot upgrade to a newer version that fixes this issue.

**Comment by SuperKiwi** [comment]
Removing whitespace between the following elements solves the problem for me:

```
<html><head>
</head><body>
</body></html>
```

**Comment by andyrobertscarpediem** [comment]
That did resolve the issue, but would be good to get an actual fix rather than hacking the html everytime

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
