### ISSUE TITLE
Laravel Cashier Without Subscription

### ISSUE THREAD

**Issue by kirensiva** [laravel/cashier#477]
I have following requirement.

**App user A calls another user B and if the user B attends the call, $1 has to be debited from his credit card.** 

Card details will be collected during the registration step.There is no subscription involved in the process. So my question is Can I use Laravel cashier for this?

**Comment by Nestecha** [comment]
Yes, as written here : [Single charges](https://laravel.com/docs/5.5/billing#single-charges).

**Comment by driesvints** [comment]
yes you can use single charges for this.
