### ISSUE TITLE
3D Secure

### ISSUE THREAD

**Issue by scottybo** [laravel/cashier#482]
I can't find a mention of this in the docs or any other Github issues.

We're using Cashier (as part of Laravel Spark) to charge our users. Some of our users have 3D Secure enabled on their cards (see: https://stripe.com/docs/sources/three-d-secure) and their payment is failing as it seems that Cashier doesn't handle cards of this type.

Please advise on whether I've made a mistake, ways to fix this, and/or and plans for future support of 3D Secure.

**Comment by matejminar** [comment]
I am interested in this too.

**Comment by darkwinternight** [comment]
Same here!

**Comment by djam90** [comment]
The 3D Secure process seems a lot more complex than a simple charge, so maybe Cashier doesn't support it... hope it will though, this could potentially lose customers.

**Comment by burhanmt** [comment]
Same here. Laravel Cashier should have this feature.

**Comment by driesvints** [comment]
Hmm, I can see this being useful but not sure how this would be implemented. Feel free to send in a PR.

**Comment by insology** [comment]
Same here, big problems with 3D secure ;)

**Comment by darkmanAmazigh** [comment]
Me too, i'm interested in this

**Comment by u01jmg3** [comment]
Received this email from Stripe yesterday:

> In September (14th), the European Union will be introducing rules requiring [Strong Customer Authentication (SCA)](https://stripe.com/guides/strong-customer-authentication) for many online transactions as part of PSD2 regulation.
>
> Transactions that don’t meet the new SCA requirements may be declined by your customers’ banks.
>
> Stripe has built a new Payments API—[PaymentIntents](https://stripe.com/docs/payments/payment-intents)—to get European customers ready for these rule changes. PaymentIntents is designed to recognize when the new SCA rules apply and to trigger any required authentication.
>
> You can learn more in our [guide on SCA](https://stripe.com/guides/strong-customer-authentication) and [read the docs](https://stripe.com/docs/payments/payment-intents) to get started integrating this new SCA-ready payments API.
>
>
> [Get started with PaymentIntents](https://stripe.com/docs/payments/payment-intents)

---

I think the new PaymentIntents API is newly out of beta as they state:

> ℹ️ PaymentIntents are stable and suitable for use in production. However, not all Stripe products and APIs are fully compatible just yet. We’re working on it!

**Comment by ralphmorris** [comment]
Has anybody had any joy integrating this with Payment Intents yet?

**Comment by driesvints** [comment]
@ralphmorris atm I am waiting until they update the migration docs for billing before I take another stab at updating cashier.

**Comment by MarGul** [comment]
@driesvints Is there any updates on this? The migration guide for Charges are out that (from the small stuff that I could see) Laravel cashier is using?

**Comment by driesvints** [comment]
@MarGul I noticed Stripe finally published its guide on migrating a billing: https://stripe.com/docs/billing/migration/strong-customer-authentication

So I'll start working on the next version soon.

**Comment by pwarnes** [comment]
I've been talking with Stripe support about this for a while now, as I've been upgrading my implementation. When I asked about recurring payments, and even something like adding tax to a session using their hosted checkout, the reply is that it simply isn't finished yet :(

> Stripe support writes:
There are some features that are not fully built yet, I'm afraid. Subscriptions being one of them. We are releasing new docs on this mid-April with more information around utilising Checkout, subscriptions, and payment intents, including tax. 
You can sign up to an email notification here when these docs drop:
https://stripe.com/docs/strong-customer-authentication/payment-intents#sca-updates
Unfortunately, it looks like the missing pieces you need here just aren't yet available. 

In the last week I have also noticed significant changes to their documentation with details about the new way of doing things being added.

Personally I have run into enough walls that I've decided to put the project on hold until they finish the feature.

**Comment by bilfeldt** [comment]
Here are a few relevant quotes from Stripe, provided as information for any readers following this thread. Note that proper implementation of 3D Secure require Payment Intents API which there is a separate Issue for #636 

## 3D Secure Sources API is no longer recommended
> Use of Stripe’s legacy 3D Secure Sources API is no longer recommended, and will not support 3D Secure 2. [Source](https://stripe.com/docs/strong-customer-authentication/migration#sca-updates)

## Payment Intents API will be the de facto standard in Stripe
> The Payment Intents API also serves as the foundation of other products such as Terminal. In the future, we expect this API to power all payment collection on Stripe. [Source](https://stripe.com/docs/payments/payment-intents)

## The Payment Intents API is SCA-ready
> In September 2019, new European regulation will begin requiring Strong Customer Authentication (SCA) is a new regulatory requirement coming into effect on September 14, 2019 which will impact many European online payments. It requires customers to use two-factor authentication like 3D Secure to verify their purchase. (SCA) for many online payments to European businesses or from European customers. Impacted businesses will need to provide an extra layer of authentication at checkout to help keep their customers safe. **The Payment Intents API fully supports SCA—including exemption logic—and ensure that you only ask customers to provide additional authentication when strictly necessary**. [Source](https://stripe.com/docs/payments/payment-intents)

## Further changes needed for subscription in EU
> If you are based in Europe and preparing for Strong Customer Authentication (SCA) is a new regulatory requirement coming into effect on September 14, 2019 which will impact many European online payments. It requires customers to use two-factor authentication like 3D Secure to verify their purchase., **you will need to make further changes after July 1 in order to perform authentication when saving a card for subsequent off-session payments to qualify for off-session exemptions**. This API will be available by July 1. [Source](https://stripe.com/docs/payments/payment-intents/migration#saving-cards-checkout)

## Updates on migration guide

- [SCA Migration Guide](https://stripe.com/docs/strong-customer-authentication/migration)
- [Payment Intents Migration Guide](https://stripe.com/docs/payments/payment-intents/migration)

**Comment by driesvints** [comment]
The PR for payment intents was merged so v10 will have support for 3D Secure.

**Comment by midesweb** [comment]
Hi! 
Someone can inform the approximate time may take for the release of version 10?
Thanks!

**Comment by driesvints** [comment]
Probably end of july/begin august.

**Comment by MuhammadUsman678** [comment]
If You use Laravel Cashier version 9.03 and you're unable to update the cashier version due to some dependencies. But here is one solution for you you can create your own custom services class to handle these types of payments I have attached the repository link below.
https://github.com/JuanDMeGon/laravel-payment-processing
