### ISSUE TITLE
Cashier with Company Model (wo. email)

### ISSUE THREAD

**Issue by ApplicationError** [laravel/cashier#485]
I am encountering an error, and I'm wondering if this could be caused by the fact that I configured cashier to use my 'Company' model instead of the 'User' model. My 'companies' table does not have an 'email' column. I am suspecting that this could be the cause of the error I'm getting. 

The error:

```
[2018-01-13 12:34:09] local.ERROR: No such customer: tok_1BjoD0LrP3RyeWsmYarCAfom {"userId":24,"email":"daluk@test.com","exception":"[object] (Stripe\\Error\\InvalidRequest(code: 0): No such customer: tok_1BjoD0LrP3RyeWsmYarCAfom at .../vendor/stripe/stripe-php/lib/ApiRequestor.php:124)
```

Thoughts?

**Comment by shabaz-ejaz** [comment]
@ApplicationError Did you manage to use the Company model as the billable model okay? I also have the exact same use-case and was wondering whether this will cause any problems later?

**Comment by GavinCS** [comment]
Based on the Billable::createAsStripeCustomer method, you could just pass in an empty email key.
However considering the benefits that providing an emails gives you / your companies in terms of automatic notifications on failed payments, etc. Why not provide a company billing/accounts email, someone's needs to know about billing after all.

**Comment by driesvints** [comment]
Sent in a PR to https://github.com/laravel/cashier/pull/887
