### ISSUE TITLE
Billing Intervals

### ISSUE THREAD

**Issue by ghost** [laravel/cashier#488]
I want to be able to offer either monthly or yearly subscriptions depending on the customer.

Is it possible or can it be made possible to pass `interval_count` so a plan/subscription in Stripe can be 12 months or 1 month etc?

**Comment by ColinLaws** [comment]
You have to create separate products for that, you can't change the interval for a single plan.

**Comment by driesvints** [comment]
You can have a single product but you'll have to create separate plans for it.

https://stripe.com/docs/billing/subscriptions/examples#varying-pricing
