### ISSUE TITLE
Plan swap: subscriptions.name remain unchanged

### ISSUE THREAD

**Issue by jennataiga** [laravel/cashier#489]
When you swap a plan, every column in subscription is updated except "name" column.

**Comment by nerdalertdk** [comment]
Think we are waiting an release with this fix included 

https://github.com/laravel/cashier/commit/1e87a60f1bf5c8981730d2481350f74fccaf0947#diff-dde586b4ea0798ea4a467b9eba070a7e

**Comment by driesvints** [comment]
This just doesn't makes sense really. Why would you want to do this during a plan swap? It doesn't has anything to do with it. You can later just update your subscription name if you want to. 

https://github.com/laravel/cashier/pull/446 got merged into master (for 8.0 which is unreleased atm) but I think it's best to revert it.
