### ISSUE TITLE
newSubscription() creating two subscriptions

### ISSUE THREAD

**Issue by colinbarstow** [laravel/cashier#493]
I am not doing anything different to the documentation but for reason every time i call newSubscription() I am getting two subscriptions created in both my database and stripe subscriptions. 

My code is simply this:

```php
$user->newSubscription($membershipPlan->title, $membershipPlan->stripe_id)->create($stripeToken);
```

I am on local host just using test details, could it be some sort of timeout issue?

I am pulling my hair out, i've never had this issue before. Any help would be very much appreciated.

**Comment by monaye** [comment]
What is your Cashier and Laravel version? Also, can you paste the entire method?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
