### ISSUE TITLE
Better support for single payments

### ISSUE THREAD

**Issue by Roemerb** [laravel/cashier#497]
Hi,

I think Cashier is a great addition to the Laravel Ecosystem. I generally really like the 'side-packages' like Passport, Cashier, etc. It's great to have native support for these often used features. However, I feel it's a bit of a shame that Cashier is mainly focussed on subscription payments. I think it would be great if the package had a more solid API for single payments as well. For instance, I'm currently hesitant to use Cashier in a project that I'm working on that supports single Stripe payments, where the payment needs to be authorized initially and captured later. As there currently isn't great support for functionality like this, I think I'll be writing the boilerplate Stripe code myself.

Is there interest in expanding the functionality of this package beyond subscriptions? In my opinion, it would be useful for a lot of people. I know quite a lot of people use Laravel for things like small webshops, (API) services without subscription plans, up to full fletched webshops. I'm talking about features like:

- Storing transactions in the database
-- This has benefits over just storing the subscriptions, as you can track the status of individual transactions. Also allows for payment authorisation
- Authorise payments, and capture them later
- (Stripe) Customer support: Create (Stripe) customer resources 
- Perhaps support for Omnipay so users can use local payment service providers

I could go on and on with features that modern payment service providers support these days. I've actually worked for a payment service provider for quite some time, and I've been looking for a way to start contributing to the Laravel ecosystem, so I'd love to do some of this work if there is interest.

E-commerce is still on the rise of course, and I think having solid (and safe!) payments support would be great for Laravel.

**Comment by driesvints** [comment]
Hi there. You can already use single charges with Cashier: https://laravel.com/docs/5.7/billing#single-charges

As for the rest: I think these feature requests are a bit out of scope for Cashier. Cashier is meant for billing and payments. It provides a great api for Stripe and Braintree. Beyond that you can extend and build your own libraries if you want but these sort of things aren't anything we're probably going to support anytime soon.

Still thanks for suggesting. Hope you can find something out there or build something that works for you.
