### ISSUE TITLE
need to create single charge without user

### ISSUE THREAD

**Issue by yatinPatel13490** [laravel/cashier#499]
I used Laravel 5.4 and Laravel-cashier

now, my requirement is I need to get the charge from the guest user, Is it possible to use \Stripe\Charge directly without the user?

- how can I pass the card details? need to create the stripe card token manually or the \Stripe\Carge class will manage the card details?
- in  create($params = null, $options = null) of the \Stripe\Charge class, I am not getting where should I have to pass the card details.

I try to find the example how to do that but not getting. Can anybody help me out?

**Comment by timacdonald** [comment]
You will want to just use the [underlying Stripe library](https://github.com/stripe/stripe-php) to do this.

```php
\Stripe\Stripe::setApiKey(config('services.stripe.secret'));

$charge = Charge::create([
    'currency' => 'aud',
    'amount' => '9900', // $99.00
    'source'  => $token, // your stripe token goes here
    'statement_descriptor' => 'Short description',
    'description' => 'Long description',
]);
```

Checkout the [Stripe API docs](https://stripe.com/docs/charges) for more of what you can do.

**Comment by driesvints** [comment]
You can do this I believe:

```php
User::charge(100, ['source' => $stripeToken]);
```

I'll try to send in an update to the docs for this.

Or try the example by @timacdonald. Let me know whatever works.

**Comment by adgower** [comment]
> You can do this I believe:
> 
> ```
> User::charge(100, ['source' => $stripeToken]);
> ```
> 
> I'll try to send in an update to the docs for this.
> 
> Or try the example by @timacdonald. Let me know whatever works.

When I try:
```
return User::checkoutCharge(1200, 'T-Shirt', 5);
```
it returns:
```
Non-static method App\Models\User::checkoutCharge() cannot be called statically
```
any tips?

**Comment by driesvints** [comment]
@adgower that was a bad example from me. You need an instance of a user for that.

**Comment by govindtotla** [comment]
Laravel 8, Cashier 13.10
When i try to use $user->charge(100, ['source' => $stripeToken]); it through me error of invalid token. while my token is perfectly fine.

**Comment by driesvints** [comment]
@govindtotla please don't use the sources api's anymore as they're deprecated. Please only use the payment methods api's.

**Comment by govindtotla** [comment]
> @govindtotla please don't use the sources api's anymore as they're deprecated. Please only use the payment methods api's.
Thank you so much for quick answer, I found the PCI compliance details on getting card details to server.  I am trying to implement https://github.com/stripe/stripe-php this, I'll update if got any success.
Else, Have to implement it using stripe js.
Thanks
