### ISSUE TITLE
Using Billable::cards

### ISSUE THREAD

**Issue by Bronco84** [laravel/cashier#500]
It appears that in this method there is a reference to Card which is aliased in the class as StripeCard. Because Card isn't included, it doesn't apply the data into a card object and it returns an array of empty objects instead. When I replace Card with StripeCard it seems to work as intended. Below is the referenced function with the change.

```
    /**
     * Get a collection of the entity's cards.
     *
     * @param  array  $parameters
     * @return \Illuminate\Support\Collection
     */

    public function cards($parameters = [])
    {
        $cards = [];

        $parameters = array_merge(['limit' => 24], $parameters);

        $stripeCards = $this->asStripeCustomer()->sources->all(
            ['object' => 'card'] + $parameters
        );

        if (! is_null($stripeCards)) {
            foreach ($stripeCards->data as $card) {
                $cards[] = new StripeCard($this, $card);
            }
        }

        return new Collection($cards);
    }
```

**Comment by ColinLaws** [comment]
I'm getting an array of empty objects, but changing to StripeCard only gets me back the customer object for each card.

**Comment by driesvints** [comment]
Are you still experiencing this? Please note that `Card` is a class which comes with Cashier and is not a model. It holds a reference to its `$owner` which is the billable user and the original `Stripe\Card` which you can access with `asStripeCard`.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by jagroop** [comment]
@driesvints Yes this problem still exist

Its returning empty objects

```json
[
    {},
    {}
]
```
Had to apply temporary fix suggested by @Bronco84

**Comment by driesvints** [comment]
I think this works though. If you really believe this is broken please send in a PR with a failing test.

@jagroop which version of Cashier are you running?

**Comment by Bronco84** [comment]
Correct me if I'm wrong, but it seems that Laravel models by default return all the data from that model in an object, or array of objects if it is a collection. I think this code is working as it was intended, but I think for my case (retreiving a stripe customer's credit cards through AJAX) it would be great if the model data was returned by default and it was not necessary to iterate through the card models and building your own array.

Not sure if that makes sense, but hopefully it will help everyone understand what I was trying to accomplish.
