### ISSUE TITLE
Prevent adding the user/subscription if initial signup payment fails?

### ISSUE THREAD

**Issue by snipe** [laravel/cashier#503]
Hi all - I have a question that I'm sure is dumb, but I can't find documentation on it anywhere. On our signup form, we ask for your new login information *and* your payment information in the same form. We do not offer free trials, so the card is charged at the time of signup and then recurring at whichever interval you select, monthly or yearly. 

We have javascript validation (for better UI) on the front end, then a form request to handle the actual submission error checking. That all works fine.

The problem I can't figure out is how to avoid adding the user and subscription into stripe if the initial signup payment fails. The Stripe exception "Your card was declined." gets correctly thrown, but the user is still added to the users table and to stripe, and the subscription is still created in the subscriptions table and in stripe, just with no payment method associated. 

This is less than ideal for a variety of reasons, first of which being that email is unique in our user, so a failed signup payment that adds a user means they cannot use the same email address they just tried to sign up with. 

Ultimately, if the card is declined on signup, I don't want my database or my stripe customers/subscriptions to know anything about the user. I want to fail them with the Stripe exception, re-present the form for correction, and let them try again.

I feel like I must be missing something super obvious here, but I can't see any way to accomplish this easily, short of initiating the Stripe PHP package directly, which sort of defeats the purpose of using Cashier. 

Here's the code:

```
    public function subscribe(NewHostingRequest $request) {

        $subdomain = str_slug($request->input('subdomain'),'-');
        $stripeToken = $request->input('stripeToken');

        // No stripe token - something went wrong :(
        if (!isset($stripeToken)) {
            return redirect('hosting/sign-up')->withInput()->with('error','Something went wrong. Please make sure javascript is enabled in your browser.');
        }


        $user = new User;
        $user->name = $request->input('account_name');
        $user->email = $request->input('account_email');
        $user->company = $request->input('company_name');
        $user->password = \Hash::make($request->input('password'));

        $stripeSubscription = $user->newSubscription($request->input('subscription_type'), $request->input('subscription_type'));

        if ($request->has('coupon')) {
           $stripeSubscription->withCoupon($request->input('coupon'));
        }


        $stripeSubscription->create($stripeToken,
            ['metadata' =>
                [
                    'account_name' => $request->input('billing_name'),
                    'company_type' => $request->input('company_type'),
                ]
            ]
        );
```

PHP v7.2
Laravel v5.6
Cashier v7.0.13

Thanks so much in advance for any guidance you can provide. ❤️

**Comment by timacdonald** [comment]
Hey @snipe - did you get this sorted?

Sorry if I'm going over things you are already aware of. Digging into the source we find the following things happening:

1. On `$subscription->create()` Cashier will hit Stripe and create the customer.

It doesn't send the token at this point - so Stripe doesn't know if things are going to go well with the clients credit card.

2. The `$user` has the returned Stripe customer id added to it and is then saved.

So now you have your customer in your local DB and in Stripe and we haven't even looked at the token yet.

Generally speaking - these steps are always going to succeed - unless the API cannot be reached.

3. Now Cashier will hit Stripe again and associated the token with the customer.

This I guess is where you Exception is being thrown and you are dealing with that as needed. So at this point we need to reverse the previous stuff from happening.

One solution would be to wrap things in a transaction and then you could hit the Stripe API to delete the customer. I know it is not ideal hitting the API again - but you could do this:

```php
<?php

class HostingController
{
    public function subscribe(NewHostingRequest $request) {
        $subdomain = str_slug($request->input('subdomain'),'-');
        $stripeToken = $request->input('stripeToken');

        // No stripe token - something went wrong :(
        if (!isset($stripeToken)) {
            return redirect('hosting/sign-up')->withInput()->with('error','Something went wrong. Please make sure javascript is enabled in your browser.');
        }


        $user = new User;
        $user->name = $request->input('account_name');
        $user->email = $request->input('account_email');
        $user->company = $request->input('company_name');
        $user->password = \Hash::make($request->input('password'));

        $stripeSubscription = $user->newSubscription($request->input('subscription_type'), $request->input('subscription_type'))->withMetadata([
            'account_name' => $request->input('billing_name'),
            'company_type' => $request->input('company_type'),
        ]);

        if ($request->has('coupon')) {
           $stripeSubscription->withCoupon($request->input('coupon'));
        }

        // Wrap in a transaction so if an exception is throw our local DB will
        // rollback and the user / subscription won't persist in the DB.
        $stripeSubscription = \DB::transaction(function () use ($stripeSubscription, $stripeToken) {
            return $this->createSubscription($stripeSubscription, $token);
        });
    }

    protected function createSubscription($stripeSubscription, $stripeToken)
    {
        try {
            return $stripeSubscription->create($stripeToken);
        } catch (\Stripe\Error\Card $exception) {
            // something went wrong with the card - but the customer has already
            // been created in Stripe's backend at the point a card exception is
            // thrown, so let's hit Stripe and delete it.
            $stripeSubscription->getStripeCustomer()->delete();

            // We'll let it bubble up so we can deal with the error and return
            // an error response to the user.
            throw $exception;
        }
    }
}
```

I've just thrown it all on the controller - but you could always extract some of that out to some service that takes care of all of that for you.

**Comment by snipe** [comment]
Hi! I ended up using a hybrid of cashier and stripe (which is required anyway) - I couldn’t find a better way, and after introspecting into the api, it just seemed like too much of a pain in the ass. So I run validation though the stripe api, and then let cashier do what it does if it passes. It’s ugly and unfortunate, but I just didn’t have time to work around missing api functions. I can post my code when i’m back in front of my computer, but that’s how I solved it. 

I appreciate you sharing your solution. I’m certain it will help other folks.

**Comment by pierrocknroll** [comment]
@snipe I'm very interested to see your code, thanks

**Comment by driesvints** [comment]
@timacdonald actually, that's incorrect. Everything for Stripe happens within the `create` method. The `newSubscription` also doesn't returns an instance of a subscription but an instance of the `SubscriptionBuilder`.

@snipe the problem you're having is indeed the fact that customer creation and subscription creation are tied together. This is because there needs to be a customer registered within Stripe before we can create a subscription. Take a look at the `create` method on the `SubscriptionBuilder` below:

```php
    /**
     * Create a new Stripe subscription.
     *
     * @param  string|null  $token
     * @param  array  $options
     * @return \Laravel\Cashier\Subscription
     */
    public function create($token = null, array $options = [])
    {
        $customer = $this->getStripeCustomer($token, $options);

        $subscription = $customer->subscriptions->create($this->buildPayload());

        if ($this->skipTrial) {
            $trialEndsAt = null;
        } else {
            $trialEndsAt = $this->trialExpires;
        }

        return $this->owner->subscriptions()->create([
            'name' => $this->name,
            'stripe_id' => $subscription->id,
            'stripe_plan' => $this->plan,
            'quantity' => $this->quantity,
            'trial_ends_at' => $trialEndsAt,
            'ends_at' => null,
        ]);
    }
```

As you can see we do a `getStripeCustomer` call before we attempt to create a subscription. This will create a new Stripe customer if the billable entity doesn't have a `stripe_id` set yet. 

Now the solution for your problem is the following: you'll need to attempt to create the subscription and if it doesn't succeeds remove the Stripe customer yourself manually upon failure. This is the only way I'm afraid. This could look like as follows:

```php
$subscriptionBuilder = $user->newSubscription($request->input('subscription_type'), $request->input('subscription_type'))->withMetadata([
    'account_name' => $request->input('billing_name'),
    'company_type' => $request->input('company_type'),
]);

try {
    $subscriptionBuilder->create($stripeToken);
} catch (\Stripe\Error\Card $exception) {
    // Remove user from Stripe upon charge failure.
    $user->asStripeCustomer()->delete();

    // Remove user from DB.
    $user->delete();
}
```

Note that the internal call to `getStripeCustomer` will call `createAsStripeCustomer` which will save your user to the database. That's why you'll need to delete it again when the card charge fails.

This issue is a bit old but I hope this helps for future purposes.
