### ISSUE TITLE
Stripes new Billing product

### ISSUE THREAD

**Issue by chrismackie28** [laravel/cashier#504]
Stripe just release their new product called Billing. https://stripe.com/billing

Will this affect how Cashier works with plans if we use the new API? If so do we have an idea when Cashier will be updated to handle the new features?

**Comment by robthompsonweb** [comment]
Just setup cashier with Stripes new billing product and seems to work just fine :)
No major change in strips php sdk so all functionality should work

**Comment by bmelon** [comment]
Not quite, see #505

**Comment by Ap0gee** [comment]
Currently, there is no way to handle single subscriptions to all pricing plans under a given product, outlined here: https://stackoverflow.com/questions/49827572/laravel-cashier-one-subscription-to-all-product-plans

**Comment by ruudy-es** [comment]
Any news about this topic?

This could have major impact on following months and even make Cashier a deprecated library.

**Comment by driesvints** [comment]
The way I see it the new billing product offers additional functionality besides the subscription based formulas. We're open to PRs for this but cannot promise to build any of the functionality ourselves anytime soon. 

If you want some of the functionality to make it into a new Cashier release, either open a PR for it or **a detailed issue about the part which you want to add** and I'll tag it as a feature request. Please do not open a single issue just saying you want everything from Stripe Billing to be added to cashier.

Currently one issue for Metered Billing is already open: https://github.com/laravel/cashier/issues/555

Thanks!
