### ISSUE TITLE
Class 'Laravel\Cashier\Tests\Fixtures\User' not found

### ISSUE THREAD

**Issue by UXandre** [laravel/cashier#508]
Hi there, 

I'm using Cashier for my web app and the subscription works fine. However, when I tried to cancel the subscription for the use by using the code below in Controller:

```
$user = User::find($user_id);
$user->subscription('primary')->cancel();
```

I've got the error of 'Class 'Laravel\Cashier\Tests\Fixtures\User' not found'. I wonder if anyone knows why it happens?

The issue looks like it comes from the Subscription model:

 ```
  public function owner()
    {
        $model = getenv('STRIPE_MODEL') ?: config('services.stripe.model', 'App\\User');

        $model = new $model;

        return $this->belongsTo(get_class($model), $model->getForeignKey());
    }

```

I would really appreciate your help.

**Comment by UXandre** [comment]
[Update] I delete 'STRIPE_MODEL=Laravel\Cashier\Tests\Fixtures\User' in the env file and it all works fine now. Would appreciate it if someone can explain it a bit for me? Thank you in advance.

Andre

**Comment by timacdonald** [comment]
That is the model used for tests, it should not have been setup in your env. Perhaps your editor autocomplete it to the wrong User?

Not 100% how that happened for ya.

**Comment by UXandre** [comment]
@timacdonald thanks for the reply Tim. I just deleted it from my .env and all works as expected. Still really appreciate your time.

**Comment by timacdonald** [comment]
No problem. Should be right to close this issue 👍
