### ISSUE TITLE
get payment details from Stripe

### ISSUE THREAD

**Issue by allaghi** [laravel/cashier#522]
Hello everyone, 

I am wondering how to get payment details from stripe for specific charge id

Many thanks & best regards,

**Comment by timacdonald** [comment]
You can just use the [underlying Stripe library](https://github.com/stripe/stripe-php) to do this. Cashier doesn't provide a mechanism to just fetch charges.

```
\Stripe\Stripe::setApiKey(config('services.stripe.secret'));

$charge = \Stripe\Charge::retrieve($chargeId);
```

**Comment by allaghi** [comment]
so. I have to store $chargeId value  in local database, right?

**Comment by timacdonald** [comment]
That would work for sure.
