### ISSUE TITLE
Switching plans with Braintree

### ISSUE THREAD

**Issue by MrMooky** [laravel/cashier#523]
It appears that when using Braintree and switching plans, the new plan gets billed right away. When a user switches from monthly to yearly subscription, the new yearly plan should be billed when the monthly, already paid plan, runs out. Not right away.

Is this something I can "fix" from my end, or is it just how Braintree handles this?

**Comment by mkarnicki** [comment]
This should have been filed under laravel/cashier-braintree

[Here is](https://github.com/laravel/cashier-braintree/blob/341aa575e3de1f8379bc8247f4fbc880e96d8d18/tests/CashierTest.php#L248) how proration works. Also, see the previous test.

I'm currently looking into using Cashier, can't help more right now.

**Comment by mkarnicki** [comment]
Have a look [here](https://github.com/laravel/cashier-braintree/blob/2.0/src/Subscription.php#L237), too. It should prorate correctly (i.e. there should be a discount on the yearly plan, for the unused rest of the current monthly plan). If that's the case, please consider closing this issue.

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. If this is still an issue can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
