### ISSUE TITLE
Moving stripe_id, card_brand etc. to different table, renaming cols

### ISSUE THREAD

**Issue by nikolaynesov** [laravel/cashier#524]
Is there any way to move `stripe_id`, `card_brand`, `card_last_four`, `trial_ends_at` into separate table? 1-1 with user table.

In docs it says:

```
Schema::table('users', function ($table) {
    $table->string('stripe_id')->nullable();
    $table->string('card_brand')->nullable();
    $table->string('card_last_four')->nullable();
    $table->timestamp('trial_ends_at')->nullable();
});
```

Also, any way to change `stripe_id` to `billing_id` or anything else, `subscriptions. stripe_id` to `subscriptions.billing_id`?

**Comment by mlantz** [comment]
Add it to any table you want, but then just add the Billable trait to that Model as well make sure you set the proper Model in the services.php config.

**Comment by nikolaynesov** [comment]
@mlantz does it make sense having `stripe_id`, `card_brand`, `card_last_four`, `trial_ends_at` as just a separate table (polymorphic) if 2-3 Models can pay (Drivers, Passengers, Companies) and I need to store payment info separately for each one? Also I need to make subscriptions polymorphic and rewrite the cashier trait, right?

**Comment by driesvints** [comment]
Closing this in favor of https://github.com/laravel/cashier/issues/545. Please add further input there.
