### ISSUE TITLE
[Request] Add a method for updating a Stripe charge after raising an invoice

### ISSUE THREAD

**Issue by u01jmg3** [laravel/cashier#526]
- https://stripe.com/docs/api#update_charge

For example, it would useful to be able to add a description to a charge after an invoice has been raised. When an invoice is raised a charge is automatically created, but it only contains basic information and doesn't transfer the description from the invoice to the charge. This results in a blank description when viewing the charge through the Stripe dashboard which makes auditing more difficult.

**Comment by driesvints** [comment]
Heya, thanks for sending this in. Honestly, if you want to do this you could just use the Stripe API for this. There's currently no support for handling charges in Cashier other than one off payments which will give you back a `\Stripe\Charge` instance.

**Comment by u01jmg3** [comment]
> _if you want to do this you could just use the Stripe API for this_

This is true but then Cashier leverages many things that could be done using just the Stripe API!

**Comment by u01jmg3** [comment]
I understand - Cashier doesn't exist to be a clone of the Stripe API.

For auditing purposes though I do think that this will create an issue when you attempt to match up a description on an invoice with a charge but you cannot because only basic info is transferred to the charge when it is created. An example might be searching for a charge in order to refund a user based on an invoice that exists. Being able to lookup the description would be extremely useful and correctly tie together the invoice and the charge as you would expect.

Perhaps stating this in the documentation would help clarify to Cashier users when they lookup charges within Stripe.

I shall leave you to decide.

**Comment by driesvints** [comment]
Since we haven't received any issues with this from other developers we're going to leave this as is for the time being. People can still reference this issue in the tracker if they want to.

Still want to thank you for taking the time to report this.
