### ISSUE TITLE
[Proposal] set currency code, symbol and callable format in one line

### ISSUE THREAD

**Issue by Max13** [laravel/cashier#530]
To change default currency name/code, symbol and a format using a callable function (i.e.: to remove decimals), one need to call 2 methods:

```php
Cashier::useCurrency('XAF', 'F.CFA');
Cashier::formatCurrencyUsing(function ($amount) {
    return number_format($about / 100, 0, ' ');
});
```

Here is my commit, before requesting a PR: 2d8cb93de5412c13aa3466d78fafe31a6ad33fb5

**Comment by driesvints** [comment]
Closing this in favor of #531
