### ISSUE TITLE
Automatically boot Cashier from config files

### ISSUE THREAD

**Issue by Max13** [laravel/cashier#531]
This proposal depends on laravel/laravel#4675.

The idea is to automatically boot Cashier with values from a config file. This way, a user will unlikely have to call `Cashier::useCurrency()` anymore.

Here is my suggestion: a1a5921d893eecb01940d8d4346aa0ca2a1f22fd

PS: Also depends on #530

**Comment by driesvints** [comment]
Yeah I can see how a config file might be of use. I'll mark this as a feature request. Feel free to send in a PR to the master branch.

**Comment by driesvints** [comment]
This was merged and will be included in the next release.
