### ISSUE TITLE
invoiceFor in Braintree does not create invoice

### ISSUE THREAD

**Issue by morrislaptop** [laravel/cashier#533]
https://github.com/laravel/cashier-braintree/blob/341aa575e3de1f8379bc8247f4fbc880e96d8d18/src/Billable.php#L73

**Comment by morrislaptop** [comment]
Any update?

**Comment by driesvints** [comment]
Heya, we just enabled issues for the Braintree repo. Can you report the issue there? Thanks! https://github.com/laravel/cashier-braintree/issues
