### ISSUE TITLE
Stripe subscription pricing plan swap problem

### ISSUE THREAD

**Issue by Greene123b** [laravel/cashier#535]
I have a problem (probably ID10t) with swapping Stripe subscriptions and could use a little help. I'm using Laravel 5.6.26 and Cashier 7.1.2. In Stripe I have a single product setup with two pricing plans: a semiannual plan and an annual plan (priced slightly less). I can create new customers and have them subscribe to either plan without a problem. 

When someone swaps plans is when the problem occurs. My hope was that if you changed your pricing plan that the new plan would not kick in until the current subscription was completed. In other words if you were 2 months into the 6 month subscription and changed to the annual pricing plan then things would continue until 4 months later and then you would trigger the new 12 month subscription. What happens instead is that if you change from the 6 to the 12 it immediately bills the customer for the prorated difference .... or credits them if changing from 12 month to 6 month. If I turn off prorations it simply ignores the previous subscription and bills them for the full amount of the new plan. 

I strongly suspect that it's not a code problem (vanilla from the docs) but my misunderstanding of how products / pricing plans / billing cycles interact in Stripe. Any guidance?

**Comment by ruudy-es** [comment]
Cashier does not support newest Stripe Api Version, which includes the new Billing system.

There is another issue open: https://github.com/laravel/cashier/issues/504

No official response yet...

**Comment by driesvints** [comment]
Hey @Greene123b. Swapping plans is immediately done and cannot be "planned" or "scheduled" into the future. Thus the customer will immediately be invoiced for the new plan with the prorated amount. If you turn off prorate this will of course charge them the full amount.
