### ISSUE TITLE
I want to cancel a Subscription using the stripe_id

### ISSUE THREAD

**Issue by 4sh3** [laravel/cashier#538]
Hi,

**¿How can I cancel a subscription using the stripe_id?** ??? I think is the primary key of the subscription on stripe.

I don't understand why **Laravel Cashier force me to cancel a subscription using the plan_id**, for me this has no sense... This is not letting me to create multiple subscriptions of the same package for a user because I can't chose one of them to delete specifically, I want to let it do that.

**Comment by ColinLaws** [comment]
Cashier does not support multiple plans under one subscription. If you want to do that, you need to add Subscription Items to the subscription you initially create by directly using Stripe's API.

**Comment by driesvints** [comment]
Like @ColinLaws said, Cashier doesn't supports multiple plans per subscription at the moment. I can however see that it's perhaps a nice addition to add this functionality to Cashier. If you'd like this functionality to be added to a future version of Cashier, please open a feature request here.

**Comment by driesvints** [comment]
Someone started a PR for this but it was closed due to inactivity. You can perhaps use that as a starting point: https://github.com/laravel/cashier/pull/544
