### ISSUE TITLE
cancelNow() doesn't delete subscritpion from database

### ISSUE THREAD

**Issue by mydnic** [laravel/cashier#541]
Hello,

When using cancelNow() I noticed that the "subscriptions" table was not correctly updated. So the subscription data is still there in the database. Only the "ends_at" is updated.

So if you call `$user->subscription('main')->stripe_plan` to check the user's current plan, you will get a unexpected result.

Steps to reproduce:

```php
$user->newSubscription('main', $plan)->create(); // Subscription appears in Stripe Dashboard
$user->subscription('main')->cancelNow(); // Subscription disappears from Stripe Dashboard - meaning the subcription stripe id doesn't exist anymore
$user->subscription('main')->stripe_plan == $plan // true
```

Is this an expected behavior ? If so, why ?

Thanks

**Comment by mydnic** [comment]
I guess I should use `$user->subscribedToPlan($plan, 'main')` instead, but if you have many plan that's a lot of if's to write

**Comment by driesvints** [comment]
This is intended behavior. When your subscription ended, we'll keep the record stored for reference and perhaps later to resume a cancelled subscription. Like you said, use the `subscribedToPlan` to check the current plan. It contains the logic which is needed to see if the plan is still valid or not.
