### ISSUE TITLE
How to use Laravel Cashier stripe and braintree use for one model.

### ISSUE THREAD

**Issue by developer916** [laravel/cashier#542]
I am using laravel cashier for stripe and braintree payments . 
So i migrated some fields for stripe and braintree for rooms table and add billable in the rooms model .. 
When i execute it with stripe , It is working well .. 
But braintree  is not working .. 
I am getting "No such token: tokencc_bf_sdffcz_3d8ndc_dtqjzh_8gsc7f_zdz" this errors. 

Rooms model 

```php
use Laravel\Cashier\Billable;

class Rooms extends Model
{
	use Billable
}
```

in service.php , I added this lines . 

```php
'stripe' => [
        'model'  => App\Models\Rooms::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],
    'braintree' => [
        'model'  => App\Models\Rooms::class,
        'environment' => env('BRAINTREE_ENV'),
        'merchant_id' => env('BRAINTREE_MERCHANT_ID'),
        'public_key' => env('BRAINTREE_PUBLIC_KEY'),
        'private_key' => env('BRAINTREE_PRIVATE_KEY'),
    ],
```

But btraintree is not working well 
@taylorotwell  
Do you have any suggestions for this ? 

How can i fix this errors ?

**Comment by driesvints** [comment]
Heya. Stripe and Braintree are two separate libraries. You cannot use them together at the same time. Either use one or the other.

https://github.com/laravel/cashier-braintree
