### ISSUE TITLE
can not install this library 

### ISSUE THREAD

**Issue by rajjanorkar** [laravel/cashier#546]
composer require "laravel/cashier":"~7.0"

`roblem 1
    - laravel/cashier v7.1.2 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.1.1 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.1.0 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.9 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.8 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.7 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.6 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.5 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.4 requires stripe/stripe-php ~3.0 -> satisfiable by stripe/stripe-php[v3.0.0, v3.1.0, v3.10.0, v3.10.1, v3.11.0, v3.12.0, v3.12.1, v3.13.0, v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.2.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0, v3.3.0, v3.4.0, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.8.0, v3.9.0, v3.9.1, v3.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.3 requires stripe/stripe-php ~3.0 -> satisfiable by stripe/stripe-php[v3.0.0, v3.1.0, v3.10.0, v3.10.1, v3.11.0, v3.12.0, v3.12.1, v3.13.0, v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.2.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0, v3.3.0, v3.4.0, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.8.0, v3.9.0, v3.9.1, v3.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.2 requires stripe/stripe-php ~3.0 -> satisfiable by stripe/stripe-php[v3.0.0, v3.1.0, v3.10.0, v3.10.1, v3.11.0, v3.12.0, v3.12.1, v3.13.0, v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.2.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0, v3.3.0, v3.4.0, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.8.0, v3.9.0, v3.9.1, v3.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.13 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.12 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.11 requires stripe/stripe-php ~5.0 -> satisfiable by stripe/stripe-php[v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.3.0, v5.4.0, v5.5.0, v5.5.1, v5.6.0, v5.7.0, v5.8.0, v5.9.0, v5.9.1, v5.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.10 requires stripe/stripe-php ~4.0 -> satisfiable by stripe/stripe-php[v4.0.0, v4.0.1, v4.1.0, v4.1.1, v4.10.0, v4.11.0, v4.12.0, v4.13.0, v4.2.0, v4.3.0, v4.4.0, v4.4.1, v4.4.2, v4.5.0, v4.5.1, v4.6.0, v4.7.0, v4.8.0, v4.8.1, v4.9.0, v4.9.1] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.1 requires stripe/stripe-php ~3.0 -> satisfiable by stripe/stripe-php[v3.0.0, v3.1.0, v3.10.0, v3.10.1, v3.11.0, v3.12.0, v3.12.1, v3.13.0, v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.2.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0, v3.3.0, v3.4.0, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.8.0, v3.9.0, v3.9.1, v3.9.2] but these conflict with your requirements or minimum-stability.
    - laravel/cashier v7.0.0 requires stripe/stripe-php ~3.0 -> satisfiable by stripe/stripe-php[v3.0.0, v3.1.0, v3.10.0, v3.10.1, v3.11.0, v3.12.0, v3.12.1, v3.13.0, v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.2.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0, v3.3.0, v3.4.0, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.8.0, v3.9.0, v3.9.1, v3.9.2] but these conflict with your requirements or minimum-stability.
    - Installation request for laravel/cashier ~7.0 -> satisfiable by laravel/cashier[v7.0.0, v7.0.1, v7.0.10, v7.0.11, v7.0.12, v7.0.13, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.0.9, v7.1.0, v7.1.1, v7.1.2].`

**Comment by kohenkatz** [comment]
Can you share your `composer.json`?

**Comment by rajjanorkar** [comment]
Hi @kohenkatz 
Something else i guess i had added stripe php lib already in my composer with version 6+ and cashier wanted 5.9, so that was making all problem. so when i removed my stripe lib and give retry to cashier it worked. Thank you

**Comment by kohenkatz** [comment]
@rajjanorkar That's what I expected (and why I asked to see `composer.json`). Glad you figured it out.
