### ISSUE TITLE
[Proposal] Getting coupon name, not code for display in invoice

### ISSUE THREAD

**Issue by tobiasvielmetter** [laravel/cashier#547]
https://github.com/laravel/cashier/blob/3f8b198f85431012d18f9645179bac35a03753e6/src/Invoice.php#L126-L136

Hi there,

I would like to suggest adding a method to the Invoice.php  along the lines of:
```php
/**
     * Get the coupon name of the applied coupon code to the invoice.
     *
     * @return string|null
     */
    public function couponName()
    {
        if (isset($this->invoice->discount)) {
            return $this->invoice->discount->coupon->name?$this->invoice->discount->coupon->name:$this->invoice->discount->coupon->id;
        }
    }
```

That way one can access the coupon name, as it is intended by Stripe https://stripe.com/docs/api#discounts. I guess there are many reasons for this, first and foremost because one doesn't necessarily want to show the coupon code to the customer again, as it might be a coupon without limited use etc.

If interested I'd be happy to prep a pull request.

Best,
Tobias

**Comment by danieltwigg** [comment]
You can obtain the coupon name like in the following example (would be used in receipt.blade.php):

```
{{ $invoice->discount->coupon->name }}
```

**Comment by djam90** [comment]
You can obtain the coupon name like in the following example (would be used in receipt.blade.php):

```
{{ $invoice->discount->coupon->name }}
```

**Comment by driesvints** [comment]
I don't think we should add shortcuts like this to the main library. You can add a helper for this to your own codebase if you want.
