### ISSUE TITLE
swap() and cancelNow() on null

### ISSUE THREAD

**Issue by plastiik** [laravel/cashier#549]
https://github.com/laravel/cashier/blob/3f8b198f85431012d18f9645179bac35a03753e6/src/Subscription.php#L249

The ```swap()``` method also needs to update the ```name``` field on the database, else the second time we need to swap plans theres a bug that says we are trying to swap a null value.

This is the solution I did on my Dev to try solve the problem, but its a very ugly one...

Can we get this issue fixed? On a new release of Cashier?

```
$user->subscription('current_plan')->swap('plan_to_subscribe');
$user->save();

// Messed up work around cause of swap method bug
DB::update('update subscriptions set name = ? where user_id = ?', [
        $plan,
        $user->id
]);
```

**Comment by pierrocknroll** [comment]
The "name" column contains the product ID, not the plan ID, who is in the "stripe_plan" column and is updated when you swap !

**Comment by ColinLaws** [comment]
@pierrocknroll That's not correct, it is the id of the plan you are switching to.

Directly from the Laravel Cashier docs:

```php
$user = App\User::find(1);

$user->subscription('main')->swap('provider-plan-id');
```

**Comment by ColinLaws** [comment]
@plastiik I am not able to reproduce this. Just as a note, it looks like you are using the stripe_plan as the argument being passed to the $user->subscription() function. That is not the correct way Cashier is intended to be used.

The name of the subscription is a separate field than the stripe_plan. The name of a subscription simply provides you a human readable name that you reference for the sake of ease-of-use.

For instance: 
$user->subscription('main')->swap('stripe_plan_for_standard_plan');
$user->subscription('main')->swap('stripe_plan_for_premium_plan');

I hope that helps. Like I said, I tried reproducing the issue you mentioned with the name field being set to null when calling the swap function on a Billable model's subscription model.

**Comment by driesvints** [comment]
Thanks for answering this @ColinLaws 👍
