### ISSUE TITLE
Unix Timestamp error from stripe when adding 1 day trial to new subscription

### ISSUE THREAD

**Issue by robtesch** [laravel/cashier#558]
I have been having this issue intermittently for some time.

When a customer tries to add their card, I create a subscription for them in the back end. This subscription always has 1 trial day attached to it using the following pattern:

`$company->newSubscription('sub', 'plan')
                        ->trialDays($trialDays)
                        ->create($token, ['various options']);`

The majority of the time this works fine, but every now and then, I get the following error back from stripe:

`{
  "error": {
    "message": "Invalid timestamp: must be an integer Unix timestamp in the future.",
    "param": "trial_end",
    "type": "invalid_request_error"
  }
}`

I have checked in the stripe logs what actually gets submitted, and the "trial_end" parameter is indeed wrong, it's a unix timestamp about 2 hours before the request gets sent.

I have a strong feeling this is something to do with timezones. As a general note, my application is set to UTC timezone and all database dates are saved in UTC. Our customers are global. Taking a look at the trialDays function in the subscription builder, I see it's a simple Carbon::now()->addDays($trialDays); so it should be using my app's UTC timezone, but in this case it appears to be using the customer timezone somehow.

Any ideas? Perhaps force Carbon to UTC since that's what stripe expects?

**Comment by ColinLaws** [comment]
I had tons of issues with time related operations when I left my virtual machine open and put my Windows computer into sleep. When I came back to my machine, API calls would fail left and right to different services I'm using because the time becomes shifted from putting the machine to sleep.

If you're in production though, I don't see that being an issue. Just some food for thought.

**Comment by robtesch** [comment]
@driesvints the system timezone is also set to UTC. In either case I can't see much harm in changing that call to Carbon:now('UTC')->addDays($trialDays) in order to force carbon to use UTC when dealing with stripe?

**Comment by driesvints** [comment]
@robtesch what's the output of `echo date_default_timezone_get();`? (sorry if this seems repetitive, just want to make sure we don't miss anything)

Using UTC in the `Carbon::now` calls is probably the way to go but I suspect there must be something wrong on your end since this has been working fine so far.

**Comment by robtesch** [comment]
@driesvints agreed it probably is something on my side, but the server is definitely on UTC. Output of that command gives simply UTC. All indications point to carbon::now() using UTC, and i have no idea why it wouldn't be, but as i say, stripe seems to think differently.

**Comment by driesvints** [comment]
I'm very sorry but as it seems this is probably something on your end I'm going to close this at the moment. We're using this issue tracker mainly for bug reporting and new feature tracking. I'm sorry I can't be of more help. 

Something you can do is ask your question on one of the below channels to see if someone can help out:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Good luck. Hope you figure it out! Feel free to reach back once you found what's wrong.

**Comment by robtesch** [comment]
@driesvints understood and fair enough. For what it's worth, for the time being i have simply removed the trial period and i haven't had any issues since. Still think it's worth changing any Carbon::now() calls to Carbon::now('UTC'). Could i make a pull request for it?

**Comment by driesvints** [comment]
You can yeah but unsure if Taylor will merge it. I'm still not 100% convinced it's the right idea. You might want to gather some more opinions on it before sending in a PR.

**Comment by eberkund** [comment]
Is this fixed? I am encountering the same error

**Comment by tnylea** [comment]
@eberkund Ditto on my end. Care to show any code?

Here's what I'm working with in my RegisterController

```php
public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        DB::beginTransaction();

        event(new Registered($user = $this->create($request->all())));
        
        $user->newSubscription('main', 'starter')->create($request->token, ['email' => $user->email]);
        $user->trial_ends_at = NULL;
        $user->save();
        
        DB::commit();

        $this->guard()->login($user);

        return $this->registered($request, $user)
                        ?: redirect($this->redirectPath());
    }
```

I'll keep trying things on my end and reply back if I figure out my issue :)

**Comment by tnylea** [comment]
@eberkund right you are, that worked!

🤦I just needed to keep trucking away at it.

If anyone needs help with this issue here is how I have fixed it. Here is my controller code:

```php
public function register(Request $request)
    {
        $this->validator($request->all())->validate();


        DB::beginTransaction();

        event(new Registered($user = $this->create($request->all())));
        
        $user->newSubscription('main', 'starter')->create($request->payment_method, ['email' => $user->email]);
        $user->trial_ends_at = now();
        $user->save();

        DB::commit();

        $this->guard()->login($user);

        return $this->registered($request, $user)
                        ?: redirect($this->redirectPath());
    }
```

And here is the JS I used in my view. Would probably be good to show the form POST functionality in the docs. But either way, here is the JS I used on my end:

```javascript
const stripe = Stripe('{{ env("STRIPE_KEY") }}');
        console.log(stripe);

        const elements = stripe.elements();
        const cardElement = elements.create('card');

        cardElement.mount('#card-element');

        const cardHolderName = document.getElementById('name');
        const cardButton = document.getElementById('card-button');
        const clientSecret = cardButton.dataset.secret;
        let validCard = false;
        const cardError = document.getElementById('card-errors');

        cardElement.addEventListener('change', function(event) {
            
            if (event.error) {
                validCard = false;
                cardError.textContent = event.error.message;
            } else {
                validCard = true;
                cardError.textContent = '';
            }
        });

        var form = document.getElementById('signup-form');

        form.addEventListener('click', async (e) => {
            event.preventDefault();

            const { paymentMethod, error } = await stripe.createPaymentMethod(
                'card', cardElement, {
                    billing_details: { name: cardHolderName.value }
                }
            );

            if (error) {
                // Display "error.message" to the user...
                console.log(error);
            } else {
                // The card has been verified successfully...
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'payment_method');
                hiddenInput.setAttribute('value', paymentMethod.id);
                form.appendChild(hiddenInput);
                // Submit the form
                form.submit();
            }

        });
```
