### ISSUE TITLE
How to keep consistency between Cashier database and Stripe ?

### ISSUE THREAD

**Issue by pierrocknroll** [laravel/cashier#559]
Hello,

I'm wondering, since there are some data on the Cashier database, like "trial_ends_at"/"quantity"/"ends_at", if I change something on the Stripe dashboard (for example : cancel a subscription, stop the trial, change quantities, delete customer...), how to keep the database consistent ?

If I use webhooks, they will be triggered even if the actions are made on my app, not only from Cashier Dashboard, so they will be triggered a lot for no reason.
And if the webhooks are the solution, why these hooks are not handled by Cashier within WebhookController  ?

A cron job ? Is there any example somewhere ?

Thanks a lot

**Comment by ColinLaws** [comment]
I would say that you should only set up web hooks from Stripe for events that you aren't handling. For instance, you don't know when a customer had a failed payment, so you would use a web hook for that. 

Personally, I listen for the customer updated event on my web hook, because I don't know if the change happened in my system, or if our sales staff have made a modification to the customer using the Stripe portal. I check the difference between the customer's info in my database, and the data that comes back from the web hook, and I only update the customer in my database if they need to be.

I hope this helps. If you haven't noticed, like I said you're able to tell Stripe the web hooks that you actually want to use.

**Comment by pierrocknroll** [comment]
In fact, I'm not wondering for custom application needs, but only for the default fields provided by Cashier.

I've made something like this, in my opinion, this should be in Cashier code directly, maybe I'm wrong ?

```php
/**
 * Handle deleted customer
 */
protected function handleCustomerDeleted(array $payload)
{
    $user = $this->getUserByStripeId($payload['data']['object']['id']); /* @var $user \App\User */

    if ($user) {
        $user->subscriptions->each(function ($subscription) {
            /* @var $subscription \Laravel\Cashier\Subscription */
            $subscription->skipTrial()
                ->markAsCancelled();
        });

        $user->forceFill([
            'card_brand'     => null,
            'card_last_four' => null,
            'trial_ends_at'  => null,
            'stripe_id'      => null
        ])
        ->save();
    }

    return new Response('Webhook Handled', 200);
}

/**
 * Handle customer subscription updated
 */
protected function handleCustomerSubscriptionUpdated(array $payload)
{
    $user = $this->getUserByStripeId($payload['data']['object']['customer']);

    if ($user) {
        $user->subscriptions->filter(function ($subscription) use ($payload) {
            return $subscription->stripe_id === $payload['data']['object']['id'];
        })->each(function ($subscription) use ($payload) {
            /* @var $subscription \Laravel\Cashier\Subscription */

            // Quantity
            if (isset($payload['data']['object']['quantity'])) {
                $subscription->quantity = $payload['data']['object']['quantity'];
            }

            // Plan
            if (isset($payload['data']['object']['plan']['id'])) {
                $subscription->stripe_plan = $payload['data']['object']['plan']['id'];
            }

            // Trial ends
            if (isset($payload['data']['object']['trial_end'])) {
                $trial_ends = \Illuminate\Support\Carbon::createFromTimestamp(
                    $payload['data']['object']['trial_end']
                );
                if ($subscription->trial_ends_at->ne($trial_ends)) {
                    $subscription->trial_ends_at = $trial_ends;
                }
            }

            $subscription->save();
        });
    }

    return new Response('Webhook Handled', 200);
}

/**
 * Handle customer updated
 */
protected function handleCustomerUpdated(array $payload)
{
    $user = $this->getUserByStripeId($payload['data']['object']['id']); /* @var $user \App\User */

    if ($user) {
        // Change card details
        if (isset(
            $payload['data']['object']['default_source'],
            $payload['data']['previous_attributes']['default_source'],
            $payload['data']['object']['sources']['data']
        )) {
            $default_card = $payload['data']['object']['default_source'];
            foreach ($payload['data']['object']['sources']['data'] as $card) {
                if (isset($card['id']) && $card['id'] == $default_card) {
                    $user->forceFill([
                        'card_brand'     => $card['brand'] ?? null,
                        'card_last_four' => $card['last4'] ?? null
                    ])
                    ->save();
                    break;
                }
            }
        }
    }

    return new Response('Webhook Handled', 200);
}

```

**Comment by ColinLaws** [comment]
I see what you mean. I feel like the intent of Cashier is to provide you a means of manipulating customers and subscriptions via code, and having those changes be reflected in your database whenever the change was successful in Stripe. 

Whenever I update a customer in Stripe via Laravel, the data is updated in both my Laravel database, as well as Stripe. Are you saying that your data is not being updated (such as the default payment method) in your Laravel database when using Stripe? That should automatically be updated whenever you switch payment providers using a token that you generate using Stripe's front end utilities.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following websites:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by driesvints** [comment]
Btw, like @ColinLaws said, you can easily add your own web hooks. One of the reasons why there's not more included is that the behavior of these web hooks can differ significantly for different apps. You could always make an repo for web hooks which you create.
