### ISSUE TITLE
Observing Laravel Cashier Subscription model breaks tests

### ISSUE THREAD

**Issue by oscarmorrison** [laravel/cashier#560]
I have setup a Model observer in my `app/Providers/AppServiceProvider.php` like so:

` Subscription::observe(SubscriptionObserver::class);`

this works fine in production, but it breaks all our tests that involve factory creation of a Subscription 

`$team = factory(Subscription::class, 'on trial')` etc.

Would like some guidance for debugging this...

**Comment by shirshak55** [comment]
i think such question should go to forum :)
