### ISSUE TITLE
Another table than User table 

### ISSUE THREAD

**Issue by harbrinderdebut** [laravel/cashier#574]
I have companys table which has id as primary key (which is not int, its actually a uuid, char(36) ) . Everything works ok creating new subscription, creating new stripe customer. The only problem is that when there is new subscription in the Subscription table company_id column doesn't save Company table's primary key value.

It always save 0. So I change company_id type from int to char(36) same as Company table's id column. Not again it don't save any value in company_id for new subscription, now it saves 300.

Don't know where the issue is. Is it related to uuid? 

Any help will be appreciated highly... Thanks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
