### ISSUE TITLE
Add ability to lock in proration date

### ISSUE THREAD

**Issue by futzlarson** [laravel/cashier#576]
Per [Stripe's documentation](https://stripe.com/docs/billing/subscriptions/prorations):

> After using the invoice items to calculate the cost of the proposed subscription change, you could confirm the amount with the customer before making the change. But, because Stripe prorates to the second, the amount of the prorations can change slightly between the time they are previewed, and the time the update is actually performed. To avoid this problem, lock in the proration by passing a `subscription_proration_date` parameter (on an invoice, as in the above code) or `proration_date` parameter (on a subscription, in the following), which causes the proration to be calculated as though the change was made at that time.

Really been loving Cashier. It would be rad if there were a method on `Subscription.php` that lets you lock that timestamp in, so that the preview proration and actual proration (upon user confirmation) are the same. Something along the lines of:

`$subscription->setProrationTimestamp($timestamp)->swap($plan->id);`

Thanks!

**Comment by driesvints** [comment]
Could indeed be useful.

**Comment by driesvints** [comment]
It's since v10 possible to pass options to the `swap` method so this is now supported I guess.
