### ISSUE TITLE
Request to Add Signature Verification vs. Checking if Event Exists on Stripe Server

### ISSUE THREAD

**Issue by tonylangworthy** [laravel/cashier#577]
Is it possible to add signature verification to the WebhookController? The signature is sent on the same request anyway. Thanks!

**Comment by ankurk91** [comment]
Cashier is using this middleware to verify signatures
https://github.com/laravel/cashier/blob/8.0/src/Http/Middleware/VerifyWebhookSignature.php

Later cashier also checks if event exists in Stripe server
https://github.com/laravel/cashier/blob/be0bbad876b7510e39a7d29bc6ce9cff7a3979e4/src/Http/Controllers/WebhookController.php#L187

**Comment by tonylangworthy** [comment]
Very nice! @ankurk91 thank you!

**Comment by driesvints** [comment]
Please also check the docs: https://laravel.com/docs/5.7/billing#verifying-webhook-signatures
