### ISSUE TITLE
Add ability to add coupon in swap

### ISSUE THREAD

**Issue by ssrahman** [laravel/cashier#580]
Currently it is not possible to add coupon while changing a plan using swap. We offer coupons to users and promote migrating to yearly plans.

**Comment by Dasinfomedia2** [comment]
Does stripe support it the same? add coupon code with plan upgrade via API?

**Comment by driesvints** [comment]
@Dasinfomedia2 I'm not sure what you're asking. This is the repo for the Stripe integration.

**Comment by Dasinfomedia2** [comment]
Yes.
I also want to add coupon code while changing the plan. But it cannot be done with cashier.
I want to know does this feature stripe support? So, I can do it with stripe API coding.
I couldn't find on stripe API docs.

**Comment by driesvints** [comment]
I think so yes because there's a coupon field on the update method of a subscription: https://stripe.com/docs/api/subscriptions/update

**Comment by Dasinfomedia2** [comment]
Ok. 
Thanks for the link. 
I hope this functionality will be added in cashier ASAP.

**Comment by driesvints** [comment]
This will be added in the next major version.
