### ISSUE TITLE
Warning: Ambiguous class resolution,

### ISSUE THREAD

**Issue by surjit** [laravel/cashier#583]
composer require "laravel/cashier-braintree":"~2.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing braintree/braintree_php (3.36.0): Downloading (100%)
  - Installing laravel/cashier-braintree (v2.1.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "Laravel\Cashier\Billable" was found in both "laravel-app/vendor/laravel/cashier/src/Billable.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\Billable.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Cashier" was found in both "/laravel-app/vendor/laravel/cashier/src/Cashier.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\Cashier.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\CashierServiceProvider" was found in both "/laravel-app/vendor/laravel/cashier/src/CashierServiceProvider.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\CashierServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Http\Controllers\WebhookController" was found in both "/laravel-app/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\Http\Controllers\WebhookController.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Invoice" was found in both "/laravel-app/vendor/laravel/cashier/src/Invoice.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\Invoice.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Subscription" was found in both "/laravel-app/vendor/laravel/cashier/src/Subscription.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\Subscription.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\SubscriptionBuilder" was found in both "/laravel-app/vendor/laravel/cashier/src/SubscriptionBuilder.php" and "/laravel-app/vendor/laravel/cashier-braintree/src\SubscriptionBuilder.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

**Comment by driesvints** [comment]
You can't use cashier and cashier-braintree at the same time. You need to pick one.
