### ISSUE TITLE
Changelog for 8.0?

### ISSUE THREAD

**Issue by bkuhl** [laravel/cashier#587]
Cashier received a major version bump but I can't find any changelogs anywhere to indicate what changed.  The description says "code formatting" which seems inaccurate because it wouldn't make sense to bump a major version for code formatting issues.

**Comment by driesvints** [comment]
Unfortunately there isn't one at the moment. I plan on releasing change logs for all libraries eventually but it's gonna have to wait until I've gone through all the bug reports. In the meantime you're free to send in a PR with a change log if you want to put in the work.

**Comment by bkuhl** [comment]
Seems kind of crazy to have to go through the bugs and released change logs after the fact. How is a version number determined if not by the complexity and risk of the changes included?

**Comment by bkuhl** [comment]
I'm not going to push the point, Taylor already responded on Twitter and said something about trying to get better in this area moving forward.
