### ISSUE TITLE
SubscriptionBuilder::newSubscription() does not support specifying an existing payment method

### ISSUE THREAD

**Issue by ColinLaws** [laravel/cashier#605]
At the moment, creating a new subscription with Cashier via SubscriptionBuilder::newSubscription() accepts a token. If you do not provide a token, the subscription will be created with the default source set on the customer. 

It would be helpful if Cashier's newSubscription method accepted a source_id. That would allow me to specify a payment method that is not the customer's default payment method. In my application, customers may add multiple payment methods, and have multiple subscriptions. 

It is realistic to assume that enterprise customers will be using multiple payment methods in my use case. Making new subscriptions from my marketplace will allow users to choose which of their payment methods they would like to use. 

I may be able to code something up here soon, but I wanted to add the issue as an enhancement in case I don't get around to it.

**Comment by driesvints** [comment]
Yeah I can see that being useful. We'd have to think on how we could implement this with the other open feature requests in this tracker. Marking this as an enhancement for now.

**Comment by driesvints** [comment]
The new cashier version will make use of payment methods. It'll now be possible to choose a different card payment method for the subscription creator. This will then be the default payment method for that subscription.

At the moment this only allows for cards but later payment methods will also support banks.
