### ISSUE TITLE
How can i get cardholder name?

### ISSUE THREAD

**Issue by kalemdzievski** [laravel/cashier#608]
There is no information how to get the cardholder name for the card. I am using Stripe.
Thanks in advance!

**Comment by anakadote** [comment]
You can tap into Stripe's package directly, which is already available as it's a dependency of Cashier. For example, here's how you can get the cardholder's name from an invoice:

    Stripe::setApiKey(config('services.stripe.secret'));
    
    $invoice = $request->user()->findInvoiceOrFail($invoiceId);
    
    $charge = StripeCharge::retrieve($invoice->charge);
    
    $cardholderName = $charge->source->name;

**Comment by kalemdzievski** [comment]
@anakadote I don't need to get card holder name from an invoice. I need to get it from a saved card.

**Comment by anakadote** [comment]
Same idea: 
https://stripe.com/docs/api/cards/retrieve?lang=php#retrieve_card

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by kalemdzievski** [comment]
@driesvints there is no option in this library to get this information which I think is crucial. It would be good idea to add this.
