### ISSUE TITLE
Class 'App\User' not found

### ISSUE THREAD

**Issue by gathuku** [laravel/cashier#610]
Having the error when i try to swap a braintree subscription.Please help.

**Comment by snipe** [comment]
Did you add `use App\User;` to the top of your file, beneath the namespace?

**Comment by gathuku** [comment]
am using 
```
use App\Models\User;
```

**Comment by snipe** [comment]
Is your User model in a Models folder and namespaced as App/Models/User?

**Comment by gathuku** [comment]
@snipe Yes

**Comment by gathuku** [comment]
The error is in this file.
```
vendor/laravel/cashier-braintree/src/Subscription.php
```
In owner function
```
    public function owner()
    {
        $model = getenv('BRAINTREE_MODEL') ?: config('services.braintree.model', 'App\\User');
 
        $model = new $model;
 
        return $this->belongsTo(get_class($model), $model->getForeignKey());
    }
```

**Comment by gathuku** [comment]
I have fixed it in `config('services.braintree.model', 'App\\User')`

**Comment by JexPY** [comment]
Now its 
`config('cashier.model')`

**Comment by piotrku** [comment]
or use env to setup the cashier model:
`CASHIER_MODEL=App\Models\User `
[https://laravel.com/docs/6.x/billing#billable-model](https://laravel.com/docs/6.x/billing#billable-model)
