### ISSUE TITLE
Paper size customizable for invoices

### ISSUE THREAD

**Issue by Mittler1** [laravel/cashier#615]
Currently, invoices are always generated in paper format "US Letter, Portrait". Invoices should also be able to be generated in other paper formats. For example, DIN A4.

**Comment by driesvints** [comment]
I can see how that would be beneficial. I've actually experienced myself wanting to use A4 instead. We could think of an easy way of passing a parameter to the view as an option to adjust the format.

**Comment by driesvints** [comment]
PR merged.
