### ISSUE TITLE
Cancel and renew subscription

### ISSUE THREAD

**Issue by beuzathor** [laravel/cashier#619]
Hio,
I try the last api to stripe.
If i cancel a subscription and i renew it the subscription table is not updated to NULL in 'end_date'. 
So some function can't work correctly.
I think you must add in webhook 👍 

```php
    if (isset($data['cancel_at'] == NULL)) {  
        $subscription->end_date = NULL;    
    }
```
so we can check if subscription is active or not.

**Comment by beuzathor** [comment]
finally i just added that in webhook for to add null if renew subscription 👍 
 ```
if (isset($data['cancel_at_period_end']) && $data['cancel_at_period_end']) {
                    $subscription->ends_at = $subscription->onTrial()
                        ? $subscription->trial_ends_at
                        : Carbon::createFromTimestamp($data['current_period_end']);
                }
                else {
                    $subscription->ends_at = NULL;
                }
```

**Comment by driesvints** [comment]
Can you paste the code you use to renew the subscription? Please post as much code as possible to reproduce the problem.

**Comment by beuzathor** [comment]
I don't use code for renew subscription. I cancel and renex directly in stripe dashboard

**Comment by driesvints** [comment]
I see. This might be worth adding to a new webhook.

**Comment by pierrocknroll** [comment]
I saw the same thing and I've created a PR : #629

**Comment by hlorofos** [comment]
Let's try to formulate this as a bug https://github.com/laravel/cashier/issues/669 
so we might get a better understanding from maintainers and potentially some prioritization on this.

**Comment by driesvints** [comment]
This will be included in the next release.
