### ISSUE TITLE
Subscription swapping

### ISSUE THREAD

**Issue by damcclean** [laravel/cashier#626]
Hey,

I'm trying to swap the subscription my user is using by using this code:
`$user->subscription('standard')->swap($request->plan);`
The code itself works fine but the issue I have is that it only updates the `stripe_plan` column in the `subscriptions` table. Would it not make sense for it to also update the `name` column too?

I'm happy to make a pull request if you agree.

**Comment by driesvints** [comment]
Heya, this isn't feasible because the name of a plan is never sent to stripe. The `Subscription` is an Eloquent model and you can simply update the name of the plan after you do the swapping.

```php
$subscription->swap('new-plan');

$subscription->fill(['name' => 'New plan name']);
```

**Comment by damcclean** [comment]
Thanks for your reply. I'll do that instead.
