### ISSUE TITLE
Add in a note about stripeToken being unnecessary if customer exists

### ISSUE THREAD

**Issue by Pickeringwareltd** [laravel/cashier#627]
The cashier documentation is misleading when referring to the use of $stripeToken. It assumes the user knows that the $stripeToken is unnecessary if a customer already belongs to the user model you are calling it on. 

There needs to be a note on creating subscriptions to inform users that if they have already created a customer object for that user, to not include the stripeToken in the method params.

**Comment by driesvints** [comment]
Heya, if you feel that there needs to be changes to the cashier docs, feel free to send in a PR.
