### ISSUE TITLE
Stripe Subscriptions Change

### ISSUE THREAD

**Issue by pulkitjalan** [laravel/cashier#628]
- Cashier Version: 9.2.1
- Laravel Version: 5.7.16

### Description:
In the latest version of stripes api (2019-03-14), there is a major change to the way subscription payments are handled. The subscription is created regardless of the first payment failing. Mentioned in the [upgrade guide](https://stripe.com/docs/upgrades#2019-03-14) and in the [docs](https://stripe.com/docs/api/subscriptions/create). 

### Steps To Reproduce:
Create a subscription using the card number `4000 0000 0000 0341`. This will attach successfully to the customer but payments will fail.

Using the above on to create a subscription on version `2019-02-19` throws a Stripe error, however on `2019-03-14` it creates a subscription with an 'incomplete' status. Cashier then creates that as a successful subscription.

**Comment by driesvints** [comment]
Hmmm. This indeed needs reviewing. I thought everything worked as expected when I upgraded the api version because the tests passed but it seems this is a specific new scenario we need to keep into account. We'll need to create a regression test for this to make sure this doesn't breaks again.

**Comment by pulkitjalan** [comment]
Sounds good. How best should it be handled? Assuming the logic in cashier should persist, so likely want to check the subscription status and throw an exception if the payment fails?

**Comment by driesvints** [comment]
This is only happening when no trial is present and the subscription is paid for immediately right? How would you know if the payment failed when creating the subscription?

**Comment by pulkitjalan** [comment]
Yea correct. The subscription object would return with a status of `incomplete` https://stripe.com/docs/upgrades#2019-03-14

**Comment by driesvints** [comment]
In that case we could indeed throw an exception. Best that this is a cashier specific exception.

**Comment by driesvints** [comment]
Actually, come to think of it: how did it fail before? Did we get an exception from Stripe? Because the SDK seems to hint that the subscription was always created anyway.

**Comment by pulkitjalan** [comment]
It use to be a Stripe\Error\Card exception with your card was declined error.

**Comment by pulkitjalan** [comment]
But the subscription is still created, i think we would need to do another call to delete the subscription before throwing the exception to maintain current functionality.

**Comment by driesvints** [comment]
We'll indeed need to delete the subscription and throw an exception. We'll also need to check into swapping plans. 

I'll try to look into this together with https://github.com/laravel/cashier/issues/621 tomorrow.

**Comment by driesvints** [comment]
PR made: https://github.com/laravel/cashier/pull/631

**Comment by sdebacker** [comment]
Hello Dries,
It seems that the problem is still here on subscription swap: the subscription is updated by cashier even if Stripe marked it as incomplete.

**Comment by driesvints** [comment]
@sdebacker the behavior for all this will be different on the next release so let's just wait until v10 is out. You can help beta test if you want.

**Comment by sdebacker** [comment]
Ok, thanks, I will try v10.
