### ISSUE TITLE
Add support for Checkout and Billing API

### ISSUE THREAD

**Issue by yoeriboven** [laravel/cashier#632]
From September 2019, new European laws mean the current Checkout / Elements.js and the Billing API can't be used anymore. 

It seems you won't be able to create a new subscription with a `$token` anymore.

Not using the new libraries will mean charges will fail.

Info is on nearly all pages regarding Checkout / Elements: https://stripe.com/docs/stripe-js/elements/quickstart
New Checkout: https://stripe.com/docs/payments/checkout?success=true#seehow

**Comment by driesvints** [comment]
Heya! We're aware and currently looking at what needs to be done for this. We'll probably move to the new payment intents api for custom checkout experiences and also provide support for the new checkout product. At the moment I'm waiting a bit for Stripe's migration guide on the billing product before I start working on it.

**Comment by qwertyuu** [comment]
For those wondering about what the OP is talking about:
https://stripe.com/docs/strong-customer-authentication

It should come around September 14th of this year.

**Comment by dvyue** [comment]
Is there any updates on supporting Checkout?

**Comment by driesvints** [comment]
@dvyue no. We won't be supporting checkout at this time.

**Comment by driesvints** [comment]
@dvyue we're still accepting prs for it. There was a half finished pr by myself which anyone can pick up from.
