### ISSUE TITLE
Update the customer on stripe

### ISSUE THREAD

**Issue by MarGul** [laravel/cashier#633]
Hi.

I have the ability for the user to update their billing information in my system. I want to sync this with Stripe and I can't find a way to do this using Laravel Cashier. This is what I propose to add to the `Billable.php` file:

```
public function updateStripeCustomer(array $options = [])
{
    $customer = StripeCustomer::update(
        $this->stripe_id, $options, $this->getStripeKey()
    );

    return $customer;
}
```

Now I can use it like so: `$request->user()->updateStripeCustomer(['email' => 'billing@testcompany.com]);`

**Comment by driesvints** [comment]
I had this on my list as well and a generic solution might work, however I'd also like to see some specific methods like `updateVat`, `updateShippingAddress` etc but they could technically make use of this method under the hood.

**Comment by MarGul** [comment]
Totally agree. I'm using this to update the Shipping address so I can see if I can write another one to do that specifically.

**Comment by scottybo** [comment]
Just another vote for this...

**Comment by MarGul** [comment]
> Just another vote for this...

@scottybo I have sent in a PR for this that has been merged. Check it out #634

**Comment by scottybo** [comment]
Ah, brilliant! Thanks :)
