### ISSUE TITLE
Implement Money value object

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#638]
Instead of relying on our own logic to format a money value let's make use of a test library for this. Review places in Cashier where we can make use of this.

https://github.com/moneyphp/money

**Comment by pierrocknroll** [comment]
You're right.
There is a library on top of it for Laravel : https://github.com/cknow/laravel-money

**Comment by driesvints** [comment]
I'd probably make use of the originally library to not have too many vendors in between.
