### ISSUE TITLE
Write upgrade guide for v10

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#640]
Since v10 will contain some significant changes we should write a thorough upgrade for v10.

**Comment by damarinov1** [comment]
Besides the upgrade guide, is there anything left for the v10? 

Do you recon installing it, as I am currently doing this and would save me sh*t loads of time to use the v10 version rather than using the Stripe SDK?

**Comment by driesvints** [comment]
@damarinov1 if you're using Laravel and want billing then I definitely recommend using Cashier. It'll save you time figuring out payment intents etc. You could go for the Stripe API SDK directly and cut out the middleman. But you'll have to figure out much more.

**Comment by damarinov1** [comment]
Thanks! I am using Cashier on my project for recurring subscriptions. However, it took me a lot of time to realize that v9 is not SCA-ready. Will update to the v10 version now as I read all the PRs and issues about the new functionalities.

I also stumbled upon this upgrade guide which I believe you're referring here. https://github.com/laravel/cashier/blob/upgrade-guide/UPGRADE.md

It might be useful for someone else until v10 is officially released.

And last but not least, thanks for the good work, it is much appreciated. :raised_hands:

**Comment by dasjet** [comment]
> @damarinov1 if you're using Laravel and want billing then I definitely recommend using Cashier. It'll save you time figuring out payment intents etc. You could go for the Stripe API SDK directly and cut out the middleman. But you'll have to figure out much more.

Can we expect v10 very soon?

**Comment by driesvints** [comment]
Not that long away anymore. Please help with testing v10 if you can 👍

**Comment by damayantinama** [comment]
> Not that long away anymore. Please help with testing v10 if you can

when upgrade cashier 10 then show error 
undefine \Laravel\Cashier\Cashier::useCurrency('gbp', '£')

**Comment by driesvints** [comment]
@damayantinama https://github.com/laravel/cashier/blob/10.0/UPGRADE.md#invoices

**Comment by damayantinama** [comment]
> @damayantinama https://github.com/laravel/cashier/blob/10.0/UPGRADE.md#invoices

What I do for and when do before and after the upgrade.
Please help me

**Comment by damayantinama** [comment]
> @damayantinama https://github.com/laravel/cashier/blob/10.0/UPGRADE.md#invoices

![image](https://user-images.githubusercontent.com/48583310/65669835-df0afe80-e061-11e9-99c7-4b8d8982e290.png)

**Comment by damayantinama** [comment]
> @damayantinama https://github.com/laravel/cashier/blob/10.0/UPGRADE.md#invoices

![image](https://user-images.githubusercontent.com/48583310/65669979-17aad800-e062-11e9-9769-2551149d8a72.png)

**Comment by driesvints** [comment]
@damayantinama please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by damayantinama** [comment]
> @damayantinama please try a support channel:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

I have used all url but not found any solve

**Comment by damayantinama** [comment]
I have used spark 8 and i want to upgrade 9 for that need cashier 10 when upgrade cashier 9 to 10 then show error -

Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Laravel\Cashier\Cashier::useCurrency()

  at E:\xampp\htdocs\iplayproject\app\Providers\SparkServiceProvider.php:56
    52|     public function booted()
    53|     {
    54|         Spark::useStripe();
    55|         Spark::collectBillingAddress();
  > 56|         \Laravel\Cashier\Cashier::useCurrency('gbp', '£');
    57|         Spark::afterLoginRedirectTo('/playlist');
    58|         //Spark::promotion('Coupon Code');
    59|         Spark::plan('Level 1', 'level-1')
    60|             //->trialDays(14)


I read doc for upgrade cashier 9 to 10 but not understanding
