### ISSUE TITLE
Laravel Cashier DateTime::__construct(): Failed to parse time string (@) at position 0 (@):

### ISSUE THREAD

**Issue by jamesnogra** [laravel/cashier#645]
I have this code when displaying a list of invoices, this is similar or maybe exactly the same to the ones in the official Laravel Cashier documentation. I am getting this weird `DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character `error and I'm not sure what's the @ character doing in replace of a supposed to be a date.

```
@foreach (Auth::user()->invoices() as $invoice)
    <tr>
        <td>{{ $invoice->date()->toFormattedDateString() }}</td>
        <td>{{ $invoice->total() }}</td>
        <td>
            <a href="/user/invoice/{{ $invoice->id }}">Download</a>
        </td>
    </tr>
@endforeach
```

Does anyone have a similar experience? I have also tried to just var_dump each $invoice->date() in the controller but the error is still the same. I can just get the $invoice->total() just fine. I also cannot generate the invoice because of this date issue.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
Also please next time fill out the issue template.

**Comment by jamesnogra** [comment]
Thanks for the response. Where can I find this issue template?
I did ask for help twice in StackOverflow but no response.
https://stackoverflow.com/questions/55685197/laravel-cashier-invoice-date-issue
https://stackoverflow.com/questions/55718363/laravel-cashier-datetime-construct-failed-to-parse-time-string-at-posi

**Comment by driesvints** [comment]
> I did ask for help twice in StackOverflow but no response.

Can you try the Laracasts or Laravel.io forums? They usually are much quicker to answer Laravel related questions.

You get the issue template when you select "bug report" here: https://github.com/laravel/cashier/issues/new/choose

All other choices except the feature requests will guide you to a different place.
