### ISSUE TITLE
Add an Prorate() function to reverse the noProrate() function

### ISSUE THREAD

**Issue by yougotnet** [laravel/cashier#647]
- Cashier Version: 9.3.0
- Laravel Version: 5.8+
- PHP Version: 7+
- Database Driver & Version:

### Description:
The problem with the noProrate option is that when you execute a swap right afterward a swap with noProrate() function you can't turn on Prorate.

If I have a user downgrade the plan, I do not want to prorate or give a refund, but if the user downgrades and then upgrades higher to what the originally paid during the subscription period, then I want to swap to the original plan with noProrate and then swap to a higher plan with a Prorate.

What I did to fix the issue on my end is add a new function to the Subscription model called Prorate() so that I can turn the $prorate flag to true.  If you would simply add the function to the base code it would help a lot of developers out.

**Comment by driesvints** [comment]
Okay, I could see the benefit of this. Feel free to suggest something but please add a test as well.
