### ISSUE TITLE
Migrate saving cards for SCA

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#649]
> If you are based in Europe and preparing for Strong Customer Authentication you will need to make further changes after July 1 in order to perform authentication when saving a card for subsequent off-session payments to qualify for off-session exemptions. This API will be available by July 1.

Someone noted this [here](https://github.com/laravel/cashier/issues/636#issuecomment-485670361). We'll need to update the way we save cards to comply. The API for this will be released on July 1.

https://stripe.com/docs/payments/payment-intents/migration#saving-cards-checkout
https://stripe.com/docs/payments/payment-methods/saving

**Comment by scottybo** [comment]
This is a major issue, and I'm curious whether it will be backwards compatible with the likes of Laravel Spark? We're on the 5.x branch and upgrading to the next major version is a massive job for us.

**Comment by driesvints** [comment]
> This is a major issue, and I'm curious whether it will be backwards compatible with the likes of Laravel Spark? We're on the 5.x branch and upgrading to the next major version is a massive job for us.

Spark will receive an update with the latest version of Cashier. When that'll be or what the upgrade path will be is too early to tell at the moment.

**Comment by driesvints** [comment]
Maybe also goes together with https://github.com/laravel/cashier/issues/605

**Comment by driesvints** [comment]
I'm currently talking to Stripe to clear out the final things. It seems to me there's no way to set a default payment method atm in Stripe.

**Comment by driesvints** [comment]
Stripe just released their new API which should help with this. I'll take a look at this later this week: https://stripe.com/docs/payments/cards/reusing-cards

**Comment by driesvints** [comment]
Sent in a PR for this here: https://github.com/laravel/cashier/pull/696

Basically all of the old sources/token based implementation is completely replaced with the new payment methods api. These are quite some changes but necessary ones because that's the way Stripe is pushing us.

**Comment by damayantinama** [comment]
I have upgraded Laravel to 6.0, Laravel Spark to 9.0 and Cashier to 10.0

In the Spark Subscription settings, I am seeing undefined as the currency instead of £.

I tried adding CASHIER_CURRENCY=usd to .env but no difference.

Any idea ?

**Comment by driesvints** [comment]
@damayantinama please try a support channel like I've asked you to for several times already.
