### ISSUE TITLE
Make overview of implemented webhook events to listen for

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#650]
Stripe suggest you'd only listen for the events you need in your webhook endpoint so we should probably list these events in the docs.

**Comment by Xenonym** [comment]
List of events [`WebhookController.php`](https://github.com/laravel/cashier/blob/a8650ae9097e0ed7b8ff8adb71e73ecc25385d80/src/Http/Controllers/WebhookController.php) is listening to:
```
customer.subscription.created
customer.subscription.deleted
customer.updated
customer.source.deleted
customer.deleted
```

**Comment by driesvints** [comment]
@Xenonym Thanks! There will be a couple of more in the next release.

**Comment by hassanazimi** [comment]
There is one for checkout called `checkout.session.completed` for Fulfilling purchases with webhooks.

**Comment by driesvints** [comment]
@hassanazimi that one isn't included in the library atm.

**Comment by driesvints** [comment]
Ful list below. I'll add these to the new docs.

```
customer.subscription.updated
customer.subscription.deleted
customer.updated
customer.deleted
invoice.payment_action_required
```
