### ISSUE TITLE
Date Issue in Laravel Cashier Invoice

### ISSUE THREAD

**Issue by jamesnogra** [laravel/cashier#658]
I have this code to view all invoices in my page:

```
@foreach ($user->invoices() as $invoice)
    <tr>
        <td>{{ $invoice->date()->toFormattedDateString() }}</td>
        <td>{{ $invoice->total() }}</td>
        <td>
            <a href="/invoice/{{ $invoice->id }}">Download</a>
        </td>
    </tr>
@endforeach
```

However, the line `$invoice->date()->toFormattedDateString()` gives an error:

`DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character`

I just followed all instructions in the Laravel Cashier (Billing) website and I am getting this error. I have tried two versions of Laravel (5.8 and 5.5) and two Laravel Cashier versions (8.0 and 7.0). All tests have the same date issue.

I have added the correct migrations fields. This is how I insert/add subscription to my database:

```
$user = Auth::user();
$user->newSubscription('eat', 'eat_monthly')->create($request->stripeToken);
```

I am wondering where my issue is. Please help.
![laravel-cashier-invoice-date-error](https://user-images.githubusercontent.com/6120605/56789144-d48ad580-6833-11e9-874e-751629b8bbf3.PNG)

**Comment by driesvints** [comment]
Can you pleas fill out the issue template?

**Comment by jamesnogra** [comment]
Hi Dries, I did fill this out using this link https://github.com/laravel/cashier/issues/new/choose and chose Support Question. Let me just read through over the instructions on the link.

**Comment by driesvints** [comment]
Hey @jamesnogra. The issue template for support question asks that you try this first on a support channel.

![Screen Shot 2019-04-26 at 16 24 03](https://user-images.githubusercontent.com/594614/56814526-add29c00-683f-11e9-8f12-03939421e50e.png)

![Screen Shot 2019-04-26 at 16 24 11](https://user-images.githubusercontent.com/594614/56814532-b034f600-683f-11e9-857c-471781cb042b.png)

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by dtisgodsson** [comment]
@jamesnogra Stripe changed the name of the date property from `date` to `created`. Older versions of Cashier still look for the `date` property which is why you're getting the error.

The latest version of Cashier addresses this.

Cheers,
Darren

**Comment by jamesnogra** [comment]
Thanks Darren. The PDF invoice is not also working because of this but I guess I will wait for the fix.

**Comment by dtisgodsson** [comment]
@jamesnogra both of these issues are fixed in the latest version of Cashier.
