### ISSUE TITLE
Call to undefined method Stripe\Customer::createTaxId()

### ISSUE THREAD

**Issue by KinG-InFeT** [laravel/cashier#661]
- Cashier Version: 7.2.2
- Laravel Version: 5.5.45
- PHP Version: 7.2
- Database Driver & Version: MySQL 

### Description:
I try create a taxID for saved customer in my laravel application but the method not exist.
This is a required because the old tax_info e tax_ids are deprecated:
Official Info: https://stripe.com/docs/billing/migration/taxes#moving-from-taxinfo-to-customer-tax-ids

### Steps To Reproduce:
```
$customerTaxID = \Stripe\Customer::createTaxId($customerInfo->id, [
                    "type" => ($datiBilling->vat_valid == 1) ? 'eu_vat' : 'unknown', //Type of the tax ID, one of eu_vat, nz_gst, au_abn, or unknown
                    "value" => $datiBilling->taxvat,
        ]);```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
