### ISSUE TITLE
Invoice::hasStartingBalance() should account for a negative amount

### ISSUE THREAD

**Issue by anakadote** [laravel/cashier#675]
- Cashier Version: 8.0.1
- Laravel Version: 5.7.28
- PHP Version: 7.1.23
- Database Driver & Version: MySQL v5.7.22

### Description:
The Invoice::hasStartingBalance() method returns false if the user has a negative starting balance — I would expect that a negative starting balance is still a starting balance, and therefore should return true. Suggested fix is to change the following:

```php
public function hasStartingBalance()
{
    return $this->rawStartingBalance() > 0;
}
```

to:

```php
public function hasStartingBalance()
{
    return $this->rawStartingBalance() != 0;
}
```

### Steps To Reproduce:
You would need to create a negative starting balance in Stripe; and then the description above is  self-explanatory.

**Comment by driesvints** [comment]
Please fill out the issue template when posting issues.

**Comment by anakadote** [comment]
> Please fill out the issue template when posting issues.

Updated, thank you.

**Comment by driesvints** [comment]
Starting balance in this case means at least some amount of money so a negative balance doesn't makes much sense here. What you want is a method to determine if the starting balance isn't zero. You can achieve this with your snippet above which you may do in your own code.

Is there a particularly reason/situation why you want this to be changed?

**Comment by anakadote** [comment]
Thanks, that is what I am currently doing in the receipt.blade.php file to conditionally display the Starting Balance line item:

```php
@if ($invoice->rawStartingBalance() != 0)
    <!-- Existing Balance -->
    <tr>
        <td>Starting Balance</td>
        <td>&nbsp;</td>
        <td>{{ $invoice->startingBalance() }}</td>
    </tr>
@endif
```

I suppose it's a matter of semantics, but I personally would think that if I asked if an invoice had a starting balance, the answer would be yes/true even if that balance was negative.

I'll just continue to use rawStartingBalance().

Thank you

**Comment by driesvints** [comment]
Okay no worries. I think `rawStartingBalance` is twtg here and a custom check is in order. Good luck.
