### ISSUE TITLE
Subscription booking

### ISSUE THREAD

**Issue by ronlinet** [laravel/cashier#676]
We are selling online courses which start and end at a specific date and users are booking the courses in advance.

The cashier's subscription table does have `created_at` and `ends_at `attributes but these were not designed for a custom booking, the `ends_at` attribute is acting as a cancelation and not as an expiration ...

Technically we can use the `created_at` and `ends_at`  attributes for subscription booking but it is a bit hackish solution I went through the issue queue and I haven't seen any such use cases.  

Booking a subscription for a specific date is nothing new I came across these features in Drupal, Wordpress and many other online payment solutions. 

I have also already sent a booking feature request to Stripe dev team.  When it comes to Cashier it should only take one additional attribute '`starts_at`' in the subscriptions table would you consider this as a feature request?

**Comment by driesvints** [comment]
It seems to me that the "start" and "end" date for your courses are specific to your domain and not to Stripe's way of working with subscriptions. Subscriptions are meant to be recurring on a certain interval and long lasting. You're selling a product with specific start and end dates. I think it's best that in your case you implement a one-off charge for your courses and then take the start and end date of your course into account into your system. Or you could implement subscriptions and auto-cancel the subscription when the course ends.

Would be a solution?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by ronlinet** [comment]
Hi @driesvints . 

I have contacted stripe dev team and apparently I am not the first user who has asking about this feature. 

They are implementing subscription schedule that allows you to create and manage the lifecycle of a subscription by predefining dates. 

The name of the feature is "Stripe Subscription Schedules" and it is already in its beta version =>  
![Screen Shot 2019-06-28 at 10 07 30 AM](https://user-images.githubusercontent.com/2538315/60348072-d3d60300-998c-11e9-8978-496c06c676b5.png)
 . 

The attached snapshots are taken from https://stripe.com/docs/billing/subscriptions/schedules and you have to contact the strip support to get the access. 

Cashier is an excellent tool and this is the only missing thing.

**Comment by driesvints** [comment]
@ronlinet thanks. Feel free to open up a feature request issue once the feature gets released so we can have a look. I cannot promise this will get into Cashier at this time.
