### ISSUE TITLE
Stripe Checkout SCA upgrade

### ISSUE THREAD

**Issue by sunnyjayjay** [laravel/cashier#680]
Is Cashier being updated to work with the new Stripe Checkout (SCA compliant) which has to be implemented by September this year? If so, will that Cashier version be compatible with Laravel 5.6 or will I have to upgrade my project to Laravel 5.8?

**Comment by driesvints** [comment]
Hi there. You can follow along here: https://github.com/laravel/cashier/issues/637.

The next Cashier version will require at least 5.8
