### ISSUE TITLE
User details; via stripe.createToken or $user->newSubscription?

### ISSUE THREAD

**Issue by paulcanning** [laravel/cashier#692]
I'm confused about how we should go about including the customers address etc.

Do we use `stripe.createToken` with a second argument of a `tokenData` object, assuming this is added to the token object and when used with `$user->newSubscription` is added to Stripes records?

Or, with `$user->newSubscription` can we just add the arguments in there, foregoing `stripe.createToken`'s 2nd argument?

Or, do we have to use both?

**Comment by driesvints** [comment]
This falls a little outside of Cashier's scope atm. Please check the Stripe (api) docs about the best place to handle the address.
