### ISSUE TITLE
[Proposal] Billable::invoice() should return false if unsuccessful

### ISSUE THREAD

**Issue by ok200paul** [laravel/cashier#703]
- Cashier Version: 9.3.0
- Laravel Version: 5.8.14
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 8.0.11

### Description:
Long time listener, first time caller. When attempting to create one-off invoices for users, running `$user->invoice()` with a self-assembled `$options` array returns `true` for the invoice attempt, if the `$user->stripe_id` attribute is blank or not set. It should (.. I believe ..) return `false`, as the process should indicate failure. 

It'd be a simple enough update - would you like a PR for this, if you agree?

### Steps To Reproduce:
1. Create a user with no `stripe_id` and do the following
```
$user = User::find(1); // stripe_id is not set.
$options = [];   
$res = $user->invoice($options);
dd($res); // true, but unsuccessful.
```

### Workaround
A workaround would be to use `$user->tab()` to tab the line items as this performs a check for `$user->stripe_id`, then running `$user->invoice()` but this use case is for those stubborn types that insist on using the trait function directly without tabbing and not extending it.

**Comment by driesvints** [comment]
Hey, thanks for reporting. This behavior is fixed in the next release which will be out in a few weeks normally.

**Comment by ok200paul** [comment]
Cheers Dries.
