### ISSUE TITLE
doubt about two payment step

### ISSUE THREAD

**Issue by krubenrc** [laravel/cashier#713]
Hello,

i readed about two-step payment flows, https://stripe.com/es/blog/auth-capture
and i need do something like that.

I want that when an user start a chat, i send an auth of 30$ to his account, and when the user finish chat, for example, his cost is 40$, i send the charge, and if his account no have money, i have the auth of 30$. If his cost is minor, i only charge the cost, for example, 15$ and unlock the auth.

You can help me about if this is possible with laravel cashier?

Thanks you in advance. A regards!

**Comment by driesvints** [comment]
This seems like a really old blog post so not sure if that's still applicable. The charge method is also refactored for the next release and it'll make use of the new Payment Intents API instead. You review the internals here:

https://github.com/laravel/cashier/blob/master/src/Billable.php#L31-L53

It's probably best that you ask this on a support forum as the issue tracker here is only intended for bug reports.

- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
