### ISSUE TITLE
Error reporting for missing CSRF exception

### ISSUE THREAD

**Issue by Stroemgren** [laravel/cashier#714]
Thanks for this awesome package!

Just wanted to note that if someone forgets to add their webhook route to CSRF exceptions, Stripe requests will still go through and go green in the Stripe dashboard even though cancelling of subscriptions etc. will not happen in the Laravel app. It's kind of dangerous since it creates as mismatch between subscriptions statuses in Stripe and the Laravel app. Would be awesome if you could throw an error back to Stripe instead.

**Comment by driesvints** [comment]
Heya, thanks. We can't do that because webhooks need to always return a 200 status as soon as a webhook was successfully delivered. There's a note about this in the docs as well: https://laravel.com/docs/5.8/billing#handling-stripe-webhooks
