### ISSUE TITLE
Migrations clash

### ISSUE THREAD

**Issue by okydk** [laravel/cashier#718]
- Cashier Version: ~10.0@dev
- Laravel Version: 5.8.*
- PHP Version: 7.1.23

### Description:
The new included package migrations clash with existing tables.
Specifically `subscriptions` and columns on `users` which already exists, which could be circumvented if checked beforehand.
Otherwise custom migrations would need to be included before and after `2019_05_03_000001_create_customer_columns` and `2019_05_03_000002_create_subscriptions_table`?

### Steps To Reproduce:
Migrate an old setup prior to 10.0.

**Comment by okydk** [comment]
Just found the `Cashier::ignoreMigrations();` which can be combined with a custom migration.

**Comment by driesvints** [comment]
Also make sure to read the upcoming migration guide. It includes a part about the migrations: https://github.com/laravel/cashier/blob/upgrade-guide/UPGRADE.md#upgrading-to-100-from-90

**Comment by GigaMick** [comment]
@driesvints - that link is no longer working. I'm having this same issue, are there steps to resolve anywhere?

@okydk
