### ISSUE TITLE
Support sending notifications in PaymentActionRequired webhook

### ISSUE THREAD

**Issue by gbradley** [laravel/cashier#719]
10.0 will support automatically sending mail to customers to alert them when a SCA payment requires confirmation. This is great, although the webhook uses `Mail::to` which restricts us to one message channel. It would be even more useful for this to support Notifications instead of Mailables, so for example I can notify customers by mail and SMS.

As an added benefit the notifications can be queued, although #687 may handle this differently.

In the meantime I can of course just override the method in my own controller but it does require me to repeat the actual webhook handling logic.

**Comment by driesvints** [comment]
I was actually thinking of replacing that with a notification. Will look into this!

**Comment by driesvints** [comment]
Will be in the next release. You will be able to define a custom notification class as so:

    CASHIER_PAYMENT_NOTIFICATION=App\Notifications\ConfirmPayment
