### ISSUE TITLE
Class 'Laravel\Cashier\CashierServiceProvider' not found

### ISSUE THREAD

**Issue by shihastz** [laravel/cashier#725]
when I trying to add cashierServiceProvider in providers (config/app.php) it showing not found error. I am using laravel 4.2. how to solve this issue?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
