### ISSUE TITLE
Clarification on CASHIER_PAYMENT_NOTIFICATION

### ISSUE THREAD

**Issue by alphametric** [laravel/cashier#734]
- Cashier Version: 10.0.0-beta-2
- Laravel Version: 5.8.31
- PHP Version: 7.3.6
- Database Driver & Version: MySQL 8.0.16

### Description:

Per the upgrade guide for version 10... under the section labeled "Payment Notifications", it mentions using a `CASHIER_PAYMENT_NOTIFICATION` environment variable. 

Is it necessary to set / configure this if you're opting to let Stripe "do it all for you", as also highlighted in the upgrade guide:

> You can either let Stripe handle everything for you (you may configure this in the Stripe dashboard)

**Comment by driesvints** [comment]
Heya. No you won't need to set the notification them if you use the Stripe billing notifications. I'll send in a PR to the upgrade guide tomorrow to clarify that.

**Comment by driesvints** [comment]
Thanks for testing!
