### ISSUE TITLE
Incorrect JavaScript property for setupIntent.paymentMethod

### ISSUE THREAD

**Issue by alphametric** [laravel/cashier#735]
- Cashier Version: 10.0.0-beta-2
- Laravel Version: 5.8.31
- PHP Version: 7.3.6
- Database Driver & Version: MySQL 8.0.16

### Description:

The JavaScript example in the docs makes reference to `setupIntent.paymentMethod`.
This is incorrect, the correct property is `payment_method`

**Comment by driesvints** [comment]
Heya, thanks for testing. Which example is that exactly? Can you point to the line in the docs?

**Comment by alphametric** [comment]
Apologies.

Line 199 in `billing.md` (within `laravel/docs` repo)

**Comment by dasjet** [comment]
`setupIntent.paymentMethod` as per [billing.md](https://github.com/laravel/docs/blob/update-cashier-docs/billing.md) is the correct way for getting `paymentMethod`.

**Comment by alphametric** [comment]
@dasjet forgive me, but I don't think so. If you `console.log(setupIntent)`, then you get this:

<img width="594" alt="Screenshot 2019-08-08 at 11 42 15 am" src="https://user-images.githubusercontent.com/33156775/62697230-2e25a300-b9d2-11e9-99af-51be0590c5b4.png">

**Comment by codefir** [comment]
@alphametric is right on this one. I'm currently working with the API myself, the object property is payment_method.

**Comment by alphametric** [comment]
It's just a typo in the docs, easy enough for @driesvints to correct :)

**Comment by codefir** [comment]
On the same note, another typo (which I presume was wrongly imported from the Stripe's documentation) is the following:

![image](https://user-images.githubusercontent.com/920945/62699335-fc1f3b80-b9e7-11e9-84f8-d52ce90be24c.png)

**Comment by alphametric** [comment]
Well spotted @codefir, looks like another type.

**Comment by dasjet** [comment]
@alphametric My bad. I was mixed up with Line 248 in billing.md. I was using `stripe.createPaymentMethod` not `stripe.handleCardSetup`.

**Comment by alphametric** [comment]
Oh, is there a difference in the Stripe API between the two approaches? Does one return `paymentMethod` and another `payment_method`?

**Comment by dasjet** [comment]
Yes we can get the `paymentMethod.id` and use it for `single charge`.

**Comment by codefir** [comment]
> Oh, is there a difference in the Stripe API between the two approaches? Does one return `paymentMethod` and another `payment_method`?

No, not really sure why @dasjet says there's a difference. The "paymentMethod" for the single charge example is just how the object is named. The properties of this object should have the same naming convention as the rest of the API calls.

**Comment by driesvints** [comment]
Hey all. Just pushed a commit which should fix the typos. Please note that there's indeed a difference between `stripe.createPaymentMethod` & `stripe.handleCardSetup`. Thanks for testing!
