### ISSUE TITLE
Problem updating to v10 with composer

### ISSUE THREAD

**Issue by garygreen** [laravel/cashier#744]
- Cashier Version: v10.0.0
- Laravel Version: v5.8.32
- PHP Version: 7.2
- Database Driver & Version: --

### Description:

When doing a composer update to 10.0.0 of Cashier it get's stuck in an infinite loop:

```
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-illuminate$notifications.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-moneyphp$money.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-symfony$intl.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-illuminate$broadcasting.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-illuminate$bus.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-illuminate$mail.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-symfony$polyfill-intl-icu.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-symfony$icu.json from cache
Reading C:/Users/garreh/AppData/Local/Composer/repo/https---repo.packagist.org/provider-phpunit$phpunit-mock-objects.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #43)
```

It'll get stuck in the "something's changed" and keeps changing incrementing the pass counter and never fully completes.

I found an issue on composer https://github.com/composer/composer/issues/7665 - seems to suggest it's about version mismatches / trouble finding contrainsts.

Could it be related to [this](https://github.com/laravel/cashier/commit/42a851f10bb43cb9f0dc53d02d441c63099a9ebe#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) commit where the new version of Symphony v10 needs is ^4.3 however Laravel 5.8.32 is [still requiring ^4.2](https://github.com/laravel/framework/blob/v5.8.32/composer.json#L38) ?

It could also be just a weird setup I've got or some other issues with packages. Though I have no trouble updating composer with Cashier set at v9, it's only when I upgrade to v10 do I experience issues with composer update.

**Comment by driesvints** [comment]
Hmm that's odd. The ^4.3 shouldn't be a problem because ^4.2 allows for that to be installed. Have you tried running require with the `--update-with-dependencies` flag?

```bash
composer require laravel/cashier --update-with-require
```

**Comment by garygreen** [comment]
Apologies it was an issue in my composer file. I think I was using an old version of Laravel/Dusk so that may have intefered with the update. Bumped all the versions up and it installed fine.
