### ISSUE TITLE
Add customer ID to default SetupIntent options

### ISSUE THREAD

**Issue by hanspagel** [laravel/cashier#745]
Cashier 10 feels like a big improvement, congrats on the release!

After reading the documentation I stumbled about the customer option for SetupIntents

**customer**
    ID of the Customer this SetupIntent belongs to, if one exists.
    If present, payment methods used with this SetupIntent can only be attached to this Customer, and payment methods attached to other Customers cannot be used with this SetupIntent.

Isn't this the behaviour you'd expect when calling `$user->createSetupIntent();`? I'd expect the SetupIntent to be connected with the user in some way and as Stripe offers the option to make a relation between the Customer and the SetupIntent I think it would be nice to use it.

What do you think?

BTW In case someone wants to pass options, that's already possible with the current method. This would do the above explained thing:

    $user->createSetupIntent(['customer' => $user->stripe_id]);

**Comment by gbradley** [comment]
This may lead to slightly unpredictable behaviour, since `$user` may not be a customer yet. I'd personally argue that its best for the method to create SetupIntents consistently rather than having side-effects based on the internal state of the `Billable`, but then again it would be more convenient...

**Comment by hanspagel** [comment]
If the user is not a customer, the stripe_id is null, which is the default for `customer` anyways. ¯\_(ツ)_/¯

**Comment by gbradley** [comment]
Fair enough, I didn't consider that the API will just let you pass null. Good idea :)

**Comment by driesvints** [comment]
Actually we had that in place at first but then we ran into this issue: https://github.com/laravel/cashier/issues/720

So to me it seems unwanted to use this parameter with setup intents?

**Comment by driesvints** [comment]
We removed it again here: https://github.com/laravel/cashier/pull/704

**Comment by hanspagel** [comment]
Thanks! I'll close it then.
