### ISSUE TITLE
Calling updateDefaultPaymentMethod() with the customer's payment method

### ISSUE THREAD

**Issue by u01jmg3** [laravel/cashier#746]
Hello,

Previously for **one off** invoice payments I could do:

```php
$user->createAsStripeCustomer();
$user->updateCard($request->stripeToken);
```

I see this has changed and from your [Charges test](https://github.com/laravel/cashier/blob/10.0/tests/Integration/ChargesTest.php#L33-L44) you must now call `updateDefaultPaymentMethod()`.

```php
$user->createAsStripeCustomer();
$user->updateDefaultPaymentMethod('pm_card_visa');
```

What is the recommended way to determine the customer's payment method? Using the request? I see you have hard coded the method `pm_card_visa` in every test.

(Apologies if this is more of a question but it came up during my upgrade to `v10`.)

**Comment by driesvints** [comment]
Hey @u01jmg3, no problem. In Cashier 10 it's possible to attach multiple payment methods to a customer. You can retrieve the default billing payment method with with the `defaultPaymentMethod` method: https://laravel.com/docs/5.8/billing#retrieving-payment-methods

**Comment by u01jmg3** [comment]
What happens if the customer is brand new? My use case is customers paying for a conference who may never have used our site before and may never again. They stop by, register for a conference and then pay. They're then invoiced immediately.

Already came across these in your docs:

```php
$user->paymentMethods(); // null
$user->defaultPaymentMethod(); // null
```

**Comment by driesvints** [comment]
That's strange because `$user->paymentMethods();` should return an exception when you try to access it as a non-Stripe customer. 

I'm not sure what you're asking though. Your original example above is the correct one. It's the same thing you had to do with the token based api only now with the payment methods api. 

1. Create as a stripe customer
2. Add a default payment method
3. Use `invoiceFor` method to generate an invoice for whatever you want to invoice your customer for.

**Comment by driesvints** [comment]
@u01jmg3 I see you updated your message and I see you're still using the old token based API. In Cashier 10 everything's moved to the new Payment Methods API. This is noted [here](https://github.com/laravel/cashier/blob/10.0/UPGRADE.md#cards-and-payment-methods) and you can read more about how to store payment methods [here](https://laravel.com/docs/5.8/billing#storing-payment-methods). Let me know if that's clear or not.

**Comment by u01jmg3** [comment]
Thanks @driesvints - you've put me on the right track.

**Comment by Otienoh** [comment]
@u01jmg3 Did you figure this out?
