### ISSUE TITLE
$user->subscription('plan')->latestPayment(); returns empty

### ISSUE THREAD

**Issue by dasjet** [laravel/cashier#757]
- Cashier Version: v10.1.0
- Laravel Version: v5.8.33
- PHP Version: v7.2.18
- Database Driver & Version: MongoDB v4.0.1

### Description:

```
if ($user->subscription('plan')->hasIncompletePayment()) {
    return $user->subscription('plan')->latestPayment();
}
```
Returns `empty` while `stripe_status` in the database is `past_due` and invoice status in stripe dashboard is `scheduled` 

![image](https://user-images.githubusercontent.com/1393520/63494436-48d03f80-c4db-11e9-9f62-85d70ede553f.png)

### Steps To Reproduce:

1. Subscribe to Daily Plan using 3D Secure test card (`4000000000003220`)
2. Make the first payment
3. `stripe_status` column became `past_due` on next payment
4. Verify the payment using the following method
```
if ($user->subscription('plan')->hasIncompletePayment()) {
    return $user->subscription('plan')->latestPayment();
}
```
But return `empty`

**Comment by driesvints** [comment]
Make sure you have:

- webhooks set up properly as noted in the docs
- you're looking at the correct subscription/latest payment

I also noticed you said that the subscription has become `past_due`. This is normally only possible when swapping plans. In your steps to reproduce you're noting that you're subscribing to a new plan. If the error would happen here you subscription would be `incomplete`. So I think there's a couple pieces of info missing here?

**Comment by dasjet** [comment]
Thanks.

- The Webhooks are working properly

- I'm getting the correct subscription/latest payment. 

I can see the correct subscription data when I `return $user->subscription('plan')`

I'm not swapping the plans. 

**My Stripe Invoices**

![invoices](https://user-images.githubusercontent.com/1393520/63512655-fe15ee00-c501-11e9-8cf6-4ccfd44e639e.png)
I missed the 2nd and 3rd payment and payed the 4th one when it becomes `past_due`/`incomplete`.

I can't make a payment when `stripe_status` in the database is `past_due` and invoice status in stripe dashboard is `scheduled` by using `$user->subscription('plan')->latestPayment();`

**Comment by driesvints** [comment]
That's so odd. I can't find any information about "scheduled" invoices. Can you find anything about this in the docs?

**Comment by driesvints** [comment]
Afaik these are the only statuses you can have: https://stripe.com/docs/billing/invoices/workflow

![Screen Shot 2019-08-22 at 14 50 29](https://user-images.githubusercontent.com/594614/63515919-33afdc80-c4ec-11e9-812c-23a99f10e737.png)

**Comment by driesvints** [comment]
Which API version are you using? https://dashboard.stripe.com/test/apikeys

**Comment by dasjet** [comment]
I was using 2019-05-16 but now it's  2019-08-14.

**Comment by dasjet** [comment]
**This is the scenario**

![invoices_23aug_2019](https://user-images.githubusercontent.com/1393520/63568504-0cf8b100-c593-11e9-9850-379bfe9c38dd.png)
When I try to pay this by 
```
if ($user->subscription('plan')->hasIncompletePayment()) {
    return $user->subscription('plan')->latestPayment();
}
```

it return `empty`

Thanks

**Comment by driesvints** [comment]
I really have no idea what to do with this since there's no mention whatsoever of this in the docs or the API docs.

**Comment by dasjet** [comment]
Thanks.

I'll try to code accordingly.

**Comment by driesvints** [comment]
I guess you indeed have no other option than checking if there's a latest payment first. Glad you figured out a solution.

**Comment by uremovals** [comment]
Hi, @dasjet any info about this? I have exactly the same situation, or issue.

Thanks in advance

**Comment by zainnoor17** [comment]
How I can get an invoice of customers who buy the subscription? 
i use this code = $user->invoices();
it return empty array
