### ISSUE TITLE
Suggestion: move symfony/intl to 'suggest'

### ISSUE THREAD

**Issue by hipsterjazzbo** [laravel/cashier#759]
From what I can tell, `symphony/intl` is only used if `ext-intl` is not present. However, it is a huge package, and almost single-handedly prevents deployment to Laravel Vapor due to its size, when in all likelihood it's not even used.

Perhaps it should be moved to `suggest` in `composer.json`, in order to make that process smoother?

**Comment by hipsterjazzbo** [comment]
FWIW, the only way I was able to deploy to Vapor is to add all of `symphony/intl`'s files to `vapor.yml`'s undocumented `'ignore` property.

**Comment by driesvints** [comment]
I can see your problem and would be inclined to go with your suggestion. However, we can't make such a change anymore since it'll break everyone's apps who are using v10 and have not installed the `ext-intl` extension. Such a change can only be done in the next major release.

**Comment by hipsterjazzbo** [comment]
@driesvints Hmm, that's a good point. Is there maybe a way to install the package without intl? A seperate branch of version tag maybe?

**Comment by driesvints** [comment]
@hipsterjazzbo you'll need to fork the package and maintain your own version unfortunately.

**Comment by driesvints** [comment]
I'm gonna close this as I think it's better to keep the package. It's unfortunate that it's so large but I think it's better than having people to not have a working installation from the getgo.

**Comment by driesvints** [comment]
Also: no-one else has posted any problems with this yet.
