### ISSUE TITLE
Possible for SubscriptionBuilder to create subscription on stripe, but not in application

### ISSUE THREAD

**Issue by SlyDave** [laravel/cashier#760]
- Cashier Version: 10
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: MariaDB

### Description:

Seems it's possible for the create Subscription method on SubscriptionBuilder to start a subscription on Stripe, but then fail to create the subscription in your app. and it doesn't clean up the subscription on Stripe when this occurs.

### Steps To Reproduce:

* Setup a new subscription
* ensure your database will cause a problem (either offline or missing a column, whatever it takes)
* the SubscriptionBuilder::create() method will instruct Stripe to start the subscription, but the call to $owner->subscription->create() will fail due to database issues.
* This possibility isn't caught and Stripe isn't informed to cancel the subscription - leaving the system in flux  (no subscription in app, but subscription enabled in stripe) 

```php
        $stripeSubscription = $customer->subscriptions->create($this->buildPayload());

        // IF THIS FAILS, THE ABOVE ISN'T UNDONE
        $subscription = $this->owner->subscriptions()->create([
            'name' => $this->name,
            'stripe_id' => $stripeSubscription->id,
            'stripe_status' => $stripeSubscription->status,
            'stripe_plan' => $this->plan,
            'quantity' => $this->quantity,
            'trial_ends_at' => $trialEndsAt,
            'ends_at' => null,
        ]);
```

**Comment by driesvints** [comment]
Well, I'm sorry but this isn't something we can control in the library. You'll have to take care of this yourself I'm afraid.

**Comment by SlyDave** [comment]
So Cashier isn't ACID... that's problematic for a payment gateway solution no?

I'm happy to be educated however, why can't (or shouldn't) this be controlled in the library? 

If the library fails to handle one of it's own transactional exchanges it should clean up...? Surely try-catch would solve this for all users of the lib? you know the ids of the subscription that was created, so you can fire a stripe API call off on catching any non-stripe exception to cancel the created subscription.

The other side of this is making Cashier listen for the subscription.created webhook to ensure the database is in sync (the stripe docs even go as far as suggesting you should do that...)

**Comment by driesvints** [comment]
@SlyDave if you're having database issues then that's something you'll need to handle in your own app. You can cancel the subscription when an error occurs.

**Comment by SlyDave** [comment]
I'm not, but thanks for missing or deliberately avoiding the point. You didn't answer my question, but I'm not going to continue to press it. Maybe my poor communication of the issue, Maybe just don't care enough to make it robust.

**Comment by pierrocknroll** [comment]
`
try {
                $cashierSubscription = $subscription->create($request->get('token'), $stripe_params);
            } catch (\Stripe\Error\Base $exception) {
                $user->asStripeCustomer()->delete();
                throw new HttpException($exception->getHttpStatus(), $exception->getMessage());
            }
`
