### ISSUE TITLE
updateCard() method not available

### ISSUE THREAD

**Issue by rehmatworks** [laravel/cashier#769]
Hi community,
In recent versions of Cashier, `updateCard()` method was available on billable model but now I have found that it doesn't exist. Any help will be highly appreciated.

**Comment by Sti3bas** [comment]
Seems like the method name has changed from `updateCard` to `updateDefaultPaymentMethod`: https://laravel.com/docs/5.8/billing#updating-the-default-payment-method

**Comment by rehmatworks** [comment]
@Sti3bas Thank you! Looks like some massive changes are implemented.
