### ISSUE TITLE
Update to v7 of Stripe SDK

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#770]
Stripe just released v7 of their PHP SDK. Not entirely sure but we'll probably need to do this update in v11.

Release: https://github.com/stripe/stripe-php/releases/tag/v7.0.0
Migration guide: https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v7

**Comment by Stroemgren** [comment]
Looking forward to this. 
I'm implementing deprecated endpoints at this moment.
Not able to upgrade to v7, due to conflict with Cashier.
