### ISSUE TITLE
Stripe requesting card info twice when 3D Secure is required

### ISSUE THREAD

**Issue by jpranskaitis** [laravel/cashier#778]
- Laravel Version: 5.8.35
- Cashier Version: 10.2.1
- PHP Version: 7.2.22

### Description:

When 3D Secure is required on card user needs to be redirected to `cashier.payment`, which is all correct, but page requires to repeat card information for second time.

### Steps To Reproduce:

     try {
         $payment = $user->newSubscription('main', $plan->stripe_plan)->create($method->id);
     }   catch (IncompletePayment $exception) {
         return redirect()->route(
              'cashier.payment',
             [$exception->payment->id, 'redirect' => route('home')]
        );
     }

If the original blade is not changed you will get empty card form again.

### Possible solution:

As per https://stripe.com/docs/stripe-js/reference#stripe-handle-card-payment-no-element

Workaround (might not be very secure, but...) is to pass the same payment method to the redirection route like this:

    $token = StripeToken::retrieve($request->stripeToken, Cashier::stripeOptions());
    return redirect()->route(
        'cashier.payment',
        [
            $exception->payment->id, 
            'redirect' => route('home'), 
            'card_token' => $token->card->id
        ]
    );

Publish blade files:
`php artisan vendor:publish --tag="cashier-views"`

Make the `cashier.payment` blade trigger `this.confirmPayment()` on `mounted()`.

And change `stripe.handleCardPayment` to:

    stripe.handleCardPayment(
        '{{ $payment->clientSecret() }}', {
            payment_method: '{{ request()->get('card_token') }}',
        }, {
            payment_method_data: {
                billing_details: { name: this.name }
            }
        }
    )

Also name on card should be passed on initial card charge attempt, cause `cashier.payment` blade will instantly ask for 3DS authentication.

Now user is not forced to fill card info again.

All the page design changes and loading spinner is up to you.

**Comment by driesvints** [comment]
I see you're using a stripe token which is unfortunately deprecated in the new cashier. we only support the payment methods api.

**Comment by jpranskaitis** [comment]
So here you have support for that :). Please `@deprecate` then.

yeah i see now, my code has a mix of old 7.0 and new 10.2 Cashier.

so just to be clear, payment setup logic is as follows:
1. Setup Payment Intent
2. Show user Card form (process 3Ds if needed)
3. Get that payment method and charge or subscribe over it

am i correct ?

**Comment by driesvints** [comment]
I think it's best that if you need support for older versions that you try a support channel, sorry.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by jpranskaitis** [comment]
I don't need support for old version. As per issue details Cashier version was 10.2. But i think you are right, i should get support there.
