### ISSUE TITLE
formatAmount depending on user

### ISSUE THREAD

**Issue by pierrocknroll** [laravel/cashier#780]
Hi,
Cashier::formatAmount($amount, $currency); is really great but it searches for the locale in the config file, it not depends on the User.

Currently I do something like this :
```
$money = new Money($amount, new Currency($currency));
return $money->format($user->country);
```

Would you consider to add a parameter in your formatAmount method for the locale ? (or the country).

Thanks a lot

PS : now there is a preferred_locales into the Stripe Customer object, maybe this can be taken into account.

**Comment by driesvints** [comment]
Hmm, yeah a third parameter definitely could work.

I don't think that using the Stripe customer's preferred_locales as the default would be wise given the fact that there could be numerous reasons to do this in the app itself. Also: in the places where we use this method in Cashier this isn't always available.

**Comment by pierrocknroll** [comment]
You're right.
A great option would be to call a method in the Billable trait that could be overriden on the User model.

**Comment by driesvints** [comment]
@pierrocknroll I think that's something you can easily add yourself though. I don't see the need to add that natively in Cashier.

**Comment by damayantinama** [comment]
payment not working after upgrade cashier 10

showing below error   -
message: "No such payment_method: tok_1FPNJyIgbLu2cRMdi1GtRf2X"

Any idea how to solve it?

**Comment by pierrocknroll** [comment]
@damayantinama do you see something in common between your problem and this issue ? Please read the docs, especially the UPGRADE doc. And go elsewhere to complain.

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/cashier/pull/888

**Comment by driesvints** [comment]
Merged

**Comment by pierrocknroll** [comment]
Thanks a lot @driesvints :)
