### ISSUE TITLE
Support arbitrary options to Subscription on create

### ISSUE THREAD

**Issue by RedChops** [laravel/cashier#787]
The `SubscriptionBuilder::create()` method supports an $options array, which is passed on and added to the Customer. There are a couple extra options I'd like to be passing to the Stripe Subscription object as well, so I extended `SubscriptionBuilder` and added a third parameter to `create()`, `$subscriptionOptions = []`.

I merge this arbitrary array with the one created by `buildPayload()`, which then allows me to create a Subscription with options such as `backdate_start_date` without needing additional fluid functions or specific support.

I can prepare a PR for this, if this sounds like something Cashier would like to support.

**Comment by driesvints** [comment]
Why do you need the `backdate_start_date`?

**Comment by RedChops** [comment]
We're transitioning a subscription model using a manual payment collection method to Stripe. Due to how the customers are allowed to service their account and the fact that it's an enterprise service where our customers often have strict accounting departments, we have to ensure that any proration remains identical to the previous service. The transition has to backdate their subscription to the last invoice date, and we set the initial balance of their account to negate the initial charge. 

We also plan on experimenting with `collection_method => send_invoice` in the future, which I figure Cashier would not want to support, so I went with a more generic implementation of arbitrary options.

**Comment by driesvints** [comment]
I see. I definitely feel like we can add this in so you can have more flexibility but please be aware that taking this far as in modifying the defaults may not be completely compatible with Cashier.

**Comment by damayantinama** [comment]
Cashier 10 and spark 9.1.1 upgraded, but currency label showing undefined

![image](https://user-images.githubusercontent.com/48583310/65941493-caa37900-e448-11e9-916f-1cfbb47405c6.png)

Need help

**Comment by JackWH** [comment]
I just wanted to offer another use case for being able to pass options when creating a subscription.

If a user subscribes on the 28th, I'd like to set their anchor date to the 1st of the following month. I don't want to prorate their subscription — they can have the rest of the month free — so I'll just start billing them on the 1st day of the following month, continuing monthly from thereafter.

This isn't possible at the moment without overriding Cashier's subscription creation methods, but [Stripe's docs definitely show it's possible](https://stripe.com/docs/billing/subscriptions/billing-cycle#new-subscriptions).

Simply adding the `'prorate' => false` attribute to the `buildPayload()` method of `SubscriptionBuilder` (and removing the `array_filter()` within that function) seems to let Cashier support this.

**Comment by driesvints** [comment]
I'm for this change but this will need to go to the master branch for the next version (v11) because it'll break the method signature on the `create` method.

**Comment by magnuswiderberg** [comment]
Yet another use case:

I wish to use the `payment_behavior` option when creating a Subscription, setting it to `error_if_incomplete`.

**Comment by driesvints** [comment]
Will be in v11
