### ISSUE TITLE
undefined currency after upgrading to cashier 10.0

### ISSUE THREAD

**Issue by matthaselip** [laravel/cashier#788]
- Cashier Version: 10.1
- Laravel Version: 6
- PHP Version:7.2.22
- Database Driver & Version:
mysql 5.6
### Description:
 ive upgraded laravel to v6.0, laravel spark to v9, cashier to v10 an now any references to the currency symbol shows as 'undefined'

### Steps To Reproduce:
upgrade to cashier v10.0

**Comment by rocramer** [comment]
Did you follow the upgrade guide? You need to set the currency differently since v10. See: https://laravel.com/docs/5.8/billing#currency-configuration
