### ISSUE TITLE
The 'name' field on subscriptions table is just not right 

### ISSUE THREAD

**Issue by osuagwu** [laravel/cashier#792]
I have been getting some crazy behaviour and it turns out that the reason seems to be that the 'name' field on the 'subscriptions' table is treated strangely in Cashier.

The 'name' is used as a unique identifier but the 'subscriptions' tables allows this field to repeat.

Although its quite unclear, the 'name' seems to refer to 'product' on Stripe. If it is then 'name' cannot be used as a unique identifier in relation to subscriptions since Stripe allows a customer to have more than one subscription to the name product and even to the same plan. I was having strange behaviour with Cashier because my customers are able to have this multiple subscription. Cashier seems to assume that their is one subscription per customer; how can this be correct?

For now I have to start inserting plan_id into the 'name' field to make Cashier work at all.

**Comment by driesvints** [comment]
Name is your own identifier for your own system. It isn't related to Stripe. You can, for example, cancel a subscription and create a new one later one so the user might have two subscriptions in the database (a cancelled one and an active one). These can then be shown in the UI or used as reference purposes. Multiple users could have a subscription of a certain type, hence the reason why there's no unique constraint.

**Comment by osuagwu** [comment]
> You can, for example, cancel a subscription and create a new one later one so the user might have two subscriptions in the database (a cancelled one and an active one).

OK. But a quick look at `\Laravel\Cashier\Billable::subscription(...)` confirms that you are not allowing a user to have two subscriptions with the same `name` since only the first match will always be returned.

**Comment by driesvints** [comment]
@osuagwu you can't have two that's right. Always the latest one if returned. But records are kept for historical purposes.
