### ISSUE TITLE
What is the purpose of the built in payment page?

### ISSUE THREAD

**Issue by thomseddon** [laravel/cashier#795]
- Cashier Version: 10.3.0
- Laravel Version: 6.1.0
- PHP Version: 7.3.10
- Database Driver & Version: N/A

### Description:

The documentation says:

> SCA regulations often require extra verification in order to confirm and process a payment. When this happens, Cashier will throw an IncompletePayment exception that informs you that this extra verification is needed.
> ...
> First, you could redirect your customer to the dedicated payment confirmation page which is included with Cashier. 

However I'm struggling to understand the circumstances under which this would be needed.

The only way to create a payment via Cashier is firstly create a payment method using the stripe javascript client, so all cashier users are definitely using the stripe js client. However, any extra auth requirements will be handled by this client (e.g. 3D secure popups etc.) and the payment page just seems to be an implementation of that client.

So, as I'm using the stripe client, under what circumstances would I need to redirect to this page? I'd prefer to implement it myself if required, but I'm not sure what scenario I should be handling?

Many thanks!

**Comment by thomseddon** [comment]
Ah! I consider this a bug in the implementation as the whole incomplete payment flow and payment page now seem at best unnecessary and at worst confusing!

I will try to raise it on one of the support channels....

**Comment by netpok** [comment]
@thomseddon Long story short: as far as I know a bank can ask for confirmation any time even if you set subscription as off session. This means you can't really make a set up and forget subscription. Stripe also provides an option for this, but you can implement on your side if you want to send more customized emails or use other notification channels.
