### ISSUE TITLE
Allow SetupIntent creation without a Billable

### ISSUE THREAD

**Issue by netpok** [laravel/cashier#797]
Currently there is no way to create a SetupIntent without a Billable object, this means we need to use something like `(new User())->createSetupIntent()` to pass an intent to the registration page.

My proposal:
- Move the current implementation to the Cashier class so one can use `Cashier::createSetupIntent()` to create a new intent.
- Change the current implementation to call that method, but also pass the customer reference if it exists to [provide additional security](https://stripe.com/docs/api/setup_intents/create#create_setup_intent-customer).

These changes should not be breaking changes so it could be merged to this version. If needed I can make a pull request.

**Comment by driesvints** [comment]
Heya, thanks for proposing but I don't feel that this is necessary. Like you said you can just do `(new User())->createSetupIntent()` just like you can do `(new User())->charge()` if you want. 

We also explicitly removed the passing of the customer id to the setup intent from the first implementation because people were experiencing issues with that. I can't seem to find the exact issue about that anymore right now.

**Comment by HadiNiazi** [comment]
@driesvints Cashier is requiring that return an intent from the view like this 
~~~
'intent' => auth()->user()->createSetupIntent()
~~~
But I am charging my user for the registration. So how can I get rid of this intent? I just want to collect a one-time payment.

**Comment by Xoshbin** [comment]
Hi 👋 ,
Did anyone able to solve this, I want my users to be able to checkout out as guest users without registration.
When I do it like `(new User())->charge` it's giving:
`The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.`

**Comment by HadiNiazi** [comment]
Hello,
For this you can use stripe api 2 which is used to single charge the
customer without any registration.

**Comment by salahWD** [comment]
I know this is mostly too late but I think I have a simple answer which I use (but I was searching for a better way) ... it goes like this:
if (!auth()->check()) {
$user = new User();
}

return view("???")->with([
"intent" => auth()->check() ? auth()->user()->createSetupIntent() : $user->createSetupIntent(),
]);

and for your case (using it to charge on registrations) you can just make a new user object and use its intent without saving the user ... after payment, you make a new user and save it. i am sorry if I did not understand your case fully

**Comment by HadiNiazi** [comment]
Yes, it's depends upon your logic, and how you write it, it's good to not
create the variable and achieve the task without it.
