### ISSUE TITLE
How to check if used is subscribed to some stripe's plan

### ISSUE THREAD

**Issue by sergeynilov** [laravel/cashier#799]
- Cashier Version: ^10.3
- Laravel Version: 5.8
- PHP Version:  7.2
- Database Driver & Version:

### Description:

Hello,
In my Laravel 5.8 I search how to check if used is subscribed to some stripe's plan.
I make subscription with stripe and I have installed 

```
        "stripe/stripe-php": "^7.2",
        "laravel/cashier": "^10.3",
```

In app/User.php :

```php
use Laravel\Cashier\Billable;
...
class User extends Authenticatable implements MustVerifyEmail
{
    use Billable;
    use Notifiable;
```

When I ned to subscribe to stripe's plan I make :

```php
$ret= $user->newSubscription('main', 'plan_ID')->create($requestData['purchaseDetails']['payment_token']);
```

Where plan_ID is id of plan registered at stripe dashboard. Searching for checking subscribed method I found and tried:

```php
                if( Auth::user()->subscribed( 'main', $item['stripe_plan_id'] ) ) {
                    die("-1 XXZ ===  subscribed");
                }
```

I tried stripe_plan_id or stripe_plan_name - but failed in both cases                

Also I tried: `$user->subscriptions` but it returned empty array. In Stripe dashboard I see that logged user is subscribed to stripe_plan_id...

Which way is correct ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
