### ISSUE TITLE
Support for WebhookHandled event

### ISSUE THREAD

**Issue by mitulgolakiya** [laravel/cashier#803]
# WebhookHandled Event Support

Cashier provides a great in-built way to handle webhook from Stripe. When some modification happens on a remote stripe website with the subscription it handles it and makes changes to subscriptions in the database.

## Problem/Use Case

The additional use case that we came to last week was, When any customer is canceling a Subscription, we want to send him an email to know what was the reason he canceled his subscription and get the feedback. It needs to be done from both website as well as if a user is canceling subscription form the Stripe website directly.

There can be lots of other use cases, where if something happens on Stripe, we need to notify the user after his subscription changes have been recorded to databases via Webhook. E.g.

- Notify user that he is now on a free plan and will not able to access few features
- Due to lower plan migration, he can download his data from the given link in next 7 days (in case of storage-specific plans)
etc.

## Proposed Solution

As a solution, Cashier can fire an event after successful webhook handling. A user can optionally listen for that event in code and then can read the payload and take whatever action he wanted to take by reading `$payload['type']`.

## How to listen to WebhookHandled Event

As per Laravel documentation [here](https://laravel.com/docs/6.x/events#defining-listeners), create a listener to listen to the event.

```
<?php

namespace App\Listeners;

use Laravel\Cashier\Events\WebhookHandled;

class WebhookHandledListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  Laravel\Cashier\Events\WebhookHandled  $event
     * @return void
     */
    public function handle(WebhookHandled $event)
    {
        // Access the payload using $event->payload...
    }
}
```

I think by this way, we can give a very clean way if someone is optionally want to take some extra actions on webhooks.

**Comment by cwilby** [comment]
A solution you could use in the meantime is to override the `handleWebhook` method of `WebhookController` like so:

```php
<?php

namespace App\Http\Controllers;

use Laravel\Cashier\Http\Controllers\WebhookController as CashierController;
use Illuminate\Http\Request;

class MyWebhookController extends CashierController
{
  public function handleWebhook(Request $request)
  {
    parent::handleWebhook($request);
    event(new WebhookHandled($request));
  }
}
```

If you want the event to fire before the webhook is handled, move the dispatch above `parent::handleWebhook`

**Comment by mitulgolakiya** [comment]
@cwilby Thanks. I already used the same solution as of now. Though I haven't fired the event, just put code there send an email via a job.

**Comment by driesvints** [comment]
With https://github.com/laravel/cashier/pull/810 two new events `WebhookReceived` and `WebhookHandled` will be available. Thanks @mitulgolakiya!
