### ISSUE TITLE
Issue with `findInvoice()` returning with an undefined variable: `stripeInvoice`

### ISSUE THREAD

**Issue by u01jmg3** [laravel/cashier#815]
- Cashier Version: 10.4.0
- Laravel Version: 6.5.0
- PHP Version: 7.1.26

### Description:

If the invoice is not retrieved from Stripe for whatever reason, the variable `$stripeInvoice` will not be set.

This results in `return new Invoice($this, $stripeInvoice);` failing.

Perhaps there should be a check in place (e.g. `if (!isset($stripeInvoice)) { return null; }`) to prevent an undefined variable error. Happy to put a PR together.

```php
/**
 * Find an invoice by ID.
 *
 * @param  string  $id
 * @return \Laravel\Cashier\Invoice|null
 */
public function findInvoice($id)
{
    try {
        $stripeInvoice = StripeInvoice::retrieve(
            $id, $this->stripeOptions()
        );
    } catch (Exception $exception) {
        //
    }

    return new Invoice($this, $stripeInvoice);
}
```

**Comment by driesvints** [comment]
Thanks! I've sent in a PR here: https://github.com/laravel/cashier/pull/817
