### ISSUE TITLE
Laravel Cashier one subscription to all product plans

### ISSUE THREAD

**Issue by signvikas** [laravel/cashier#823]
Laravel Cashier one subscription to all product plans, because of stripe already allows to multiple plans to subscribe at a one time. Please add this feature because we really need.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier/issues/397

**Comment by rambo666** [comment]
When will cashier v11 gets released?

**Comment by driesvints** [comment]
@rambo666 Today 😀

**Comment by rambo666** [comment]
Will there be cashier documents update as well by today. I am soo eagerly waiting for the past 10 days and halt my project to use multi plans.

**Comment by driesvints** [comment]
The PR is already done and waiting to be merged as soon as v11 is tagged: https://github.com/laravel/docs/pull/5949

The upgrade guide is already merged: https://github.com/laravel/cashier/blob/master/UPGRADE.md
