### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by meradoou** [laravel/cashier#831]
- Cashier Version: v10.5.1
- Laravel Version: v5.8.35
- PHP Version: 7.4.0

### Description:
It's about Laravel\Cashier\Http\Controllers\WebhookController at line 41 and php 7.4 compatibility . https://github.com/laravel/framework/issues/30737

### Steps To Reproduce:

- Create a webhook route
- Open the webhook route url

**Comment by driesvints** [comment]
You need to send a POST request with the proper payload to a webhook. You can't just visit it in your browser. This is done by Stripe and a Stripe webhook always contains a "type" key.
