### ISSUE TITLE
Add AED currency

### ISSUE THREAD

**Issue by Messhias** [laravel/cashier#842]
We need to add AED currency to the cashier.

**Comment by driesvints** [comment]
These currencies depend on stripe support. Out of the box, Cashier supports all currencies that Stripe supports.

**Comment by Messhias** [comment]
This is very easy to add.

Can I add the currency and open the PR?

There's a lot legacy system using the library (laracom for exemple).

**Comment by driesvints** [comment]
Stripe already supports AED: https://stripe.com/docs/currencies

And Cashier makes use of the `moneyphp/money` library which also supports AED: https://github.com/moneyphp/money/blob/master/resources/currency.php#L1101

What exactly isn't working for you?

**Comment by Messhias** [comment]
The laracom uses this library and change it to stripe or whatever it'll be
a lot headache and my approach is just add other condition in the switch
case condition.

**Comment by driesvints** [comment]
We can't offer support for third party libraries. You'll have to ask the maintainers of Laracom to offer support for Cashier.

**Comment by Messhias** [comment]
Hello,

But this is not for only support third parties, this is for also another kind currency could be added on library.

Anyway, I already changed the core by myself and I keep my version.

Thank you,

Best Regards,

Fabio William Conceição

Remote: https://remote.com/fabiowilliam
Tel/Whastapp: +971 52 503 3008
Skype: fabioo.william.conceicao
LinkedIn: https://www.linkedin.com/in/fabio-william-concei%C3%A7%C3%A3o-379b9823/
Github: https://github.com/Messhias/
Upwork: https://www.upwork.com/o/profiles/users/_~0126d10487b9843f68/
