### ISSUE TITLE
Use proper invoice number on pdfs

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier#845]
At the moment as a default, the invoice id is used as an invoice number on the pdf.

    <strong>Invoice Number:</strong> {{ $id ?? $invoice->id }}<br>

I think it's best that we use the actual invoice number as a default here since it's auto-incremented by Stripe.

**Comment by JackEllis** [comment]
Agreed. We moved to this recently:
`<p>Invoice No.: <strong>{{ $id ?? $invoice->number }}</strong></p>`

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/cashier/pull/878
