### ISSUE TITLE
Get single payment method by id

### ISSUE THREAD

**Issue by quantumwebco** [laravel/cashier#847]
I may be missing something but there doesn't seem to be a function to get a single payment method by id. Only all paymentMethods or defaultPaymentMethod

Is there a way to get an instance of Laravel\Cashier\PaymentMethod by the payment method id?

**Comment by driesvints** [comment]
You can use `findPaymentMethod`: https://laravel.com/docs/6.x/billing#retrieving-payment-methods

**Comment by quantumwebco** [comment]
Oh derp, how did I miss that? Sorry about that!
