### ISSUE TITLE
Laravel Cashier: webhook 500 error... Class &#039;App/User&#039; not found in file 

### ISSUE THREAD

**Issue by laingmedia** [laravel/cashier#850]
- Cashier Version: 10
- Laravel Version: 6
- PHP Version: 7
- Database Driver & Version: MongoDB

Description: 
I am receiving the same error when I test the following webhooks. If my webhooks receive 500 error, does that mean I cant add new customers, collect payments, and add users to database? It sure looks like it, just wanted to check. I am just testing webhooks, its not live (if that makes a difference).

customer.subscription.updated
customer.subscription.deleted
customer.updated
customer.deleted
invoice.payment_action_required (This is the only one that works)

Here is my WebhookController

`
[WebhookController.php.zip](https://github.com/laravel/cashier/files/4058607/WebhookController.php.zip)

`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by laingmedia** [comment]
@driesvints Thanks
