### ISSUE TITLE
PDF invoice not showing tax percentage (Tax Rates)

### ISSUE THREAD

**Issue by carlosten** [laravel/cashier#854]
- Cashier Version: Master branch - f8b02e5ad1038fd7c9c441b0c15322772f49646b
- Laravel Version: 6.9.0

### Description:
Created a subscription with the new taxRates() and the pdf invoice generated by Cashier is not showing any tax percentage. The subscription is correctly created in Stripe (with the proper Tax Rates).

### Steps To Reproduce:
- Configure stripe:
	- Subscription
	- Tax Rate
- Use cashier to Subscribe one user to the subscription adding a tax rate using taxRates()
- Generate a PDF invoice using Cashier

 ### Expected:
- The generated invoice includes the taxes percentage.
<img width="512" alt="Captura de pantalla 2020-01-17 a las 15 20 08" src="https://user-images.githubusercontent.com/351733/72619366-5cbe8700-393d-11ea-82c5-896e6ef4296c.png">

 ### Result:
 - The generated invoice only shows the payment done by the user. 
<img width="531" alt="Captura de pantalla 2020-01-17 a las 15 21 08" src="https://user-images.githubusercontent.com/351733/72619341-5203f200-393d-11ea-8fde-078d0ea40366.png">

 ### Remarks:
 In  cashier/src/InvoiceLineItem.php line 135, $this->item->tax_rates is empty when generating the invoice. 

To generate the expected invoice I changed this property with $this->item->tax_amounts.

**Comment by driesvints** [comment]
We'll need some more info on how the tax rate and subscription set up as well as some code to reproduce the problem.

**Comment by carlosten** [comment]
### Tax setup
<img width="842" alt="Captura de pantalla 2020-01-19 a las 12 41 13" src="https://user-images.githubusercontent.com/351733/72680340-11c97e80-3ab9-11ea-8bda-d3c5208d7981.png">

### Subscription setup
Plan in €
10€ monthly charge
No trial

### Some code
Creating payment method:
```
public function create(Request $request)
{
	$user = Auth::user();
	$paymentMethod = $request->stripePaymentMethod;
	$user->createOrGetStripeCustomer();
	$user->addPaymentMethod($paymentMethod);

```

Creating subscription:

```
    $product_stripe_id = $request->product_stripe_id;
    $plan_stripe_id = $request->plan_stripe_id;

    $days = now()->diffInDays($user->trial_ends_at);     

    try {
        $subscription = $user->newSubscription($product_stripe_id, $plan_stripe_id)->trialDays($days)->create($paymentMethod, [
            'email' => $user->email,
        ]);
    } catch (IncompletePayment $exception) {
        return redirect()->route(
            'cashier.payment', [$exception->payment->id, 'redirect' => route('account')]
        );
    }
}
```


To get the invoices:
```
$user = Auth::user();
$invoices = $user->invoices();

```
In template:
`<td><a href="/user/invoice/{{ $invoice->id }}">Download</a></td>`

### Stripe invoice

This is how the Stripe invoice looks, with the taxes shown. The problem is only in the invoice generated by Cashier.
<img width="712" alt="Captura de pantalla 2020-01-19 a las 12 37 39" src="https://user-images.githubusercontent.com/351733/72680399-acc25880-3ab9-11ea-9151-8d24d9560e37.png">

**Comment by driesvints** [comment]
Thanks for the info. I probably won't have time to look into this until next week at the earliest.

**Comment by driesvints** [comment]
Managed to reproduce this. Will look into it.

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/cashier/pull/876

**Comment by driesvints** [comment]
Fixed on master
