### ISSUE TITLE
3D Payment Form. PaymentMethod Object, customer attribute is null

### ISSUE THREAD

**Issue by CodeScroll** [laravel/cashier#856]
- Cashier Version: ^10.4
- Laravel Version: 6.12.0
- PHP Version: 7.3.13

I have face that, when o Customer goes to create a Subscription, with the "newSubscription->create($paymentMethod)" Cashier function. For the Card, let's say 4000000000003063, who performs 'invoice.payment_action_required' event and executes the catch scope. After the succeeded payment on 3D form that shows up from Cashier, i dump the payment payment method, and the customer attribute is null. 

Is there a specific reason that customer attribute is null ? Because the immediate payment with the card, let's say 5555555555554444 have that attribute with the attached customer id.

Also, when i listed the customer's payment methods through 'PaymentMethod::all'. or cashier paymentMethods. It's not shown. So its have not attached.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by CodeScroll** [comment]
I'm trying to figure out. it's possibly a bug.
