### ISSUE TITLE
Laravel cashier with restfull

### ISSUE THREAD

**Issue by ghten** [laravel/cashier#857]
- Cashier Version: 10
- Laravel Version: 6.#.#
- PHP Version: 7.3

It is possible to use Laravel cashier in Restful because I have angular in the client. When I put the card in angular and stripe returns my a token "tok_" but in cashier it's impossible to create a subscription with a token. 

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
