### ISSUE TITLE
New subscription

### ISSUE THREAD

**Issue by ghten** [laravel/cashier#859]
- Cashier Version: 10.5
- Laravel Version: 6.0
- PHP Version: 7.3

Hi,

When you use subscription('main')->cancelNow() the subscription is removed from stripe but in the table subscription you have you update ends_at and if you create a new subscription, for stripe is new but not for cashier and we have an error “No such subscription: sub_XXXX”. To resolve this problem, I remove the subscription in the table.

Thanks

**Comment by driesvints** [comment]
I've done this scenario several times and never experienced this. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ghten** [comment]
Sorry but for me it's bug. In stripe with subscription('main')->cancelNow()  or others like $subscription->markAsCancelled(), stripe removes the subscription but in the table subscriptions is not removed, it is cancelled and when we use  $user()->subscription('main'), it returns a current plan but it doesn't exist in Stripe. Current Pan is obligatory an active plan, not a cancelled plan.

**Comment by driesvints** [comment]
@ghten subscriptions are kept in the table for reference purposes if the app needs to display previously subscriptions. You can check if a subscription is cancelled with `$subscription->cancelled()`.

**Comment by ghten** [comment]
I am ok with you, but $user()->subscription('main') return the current plan and this plan cannot be cancelled. Sorry, it's not very important but I don't see the logic in that. I had to find a solution for this function to resend the current plan and my solution has been to delete the subscription.
