### ISSUE TITLE
Subscription's default payment method

### ISSUE THREAD

**Issue by CodeScroll** [laravel/cashier#861]
The fact that all subscription's have null on default_payment_method . Make Cashier to be usefully for one card per user (customer's default payment method). According to Stripe politic, even if subscription created with card B or C. In the next billing cycle will attempt the payment from the Customer's default payment method. 

Do you intend to integrate, the option of subscription's default payment method ? 

The buildPayload() function build the create. I can make it, 
but i am not sure how to requested programatically via github

**Comment by driesvints** [comment]
No plans for this atm.

**Comment by Kubitomakita** [comment]
I'd use that too. One of the earliest Cashier versions assigned the payment method even if it was the default one. Or was is Spark? 🤔

**Comment by daugaard47** [comment]
@CodeScroll  Did you figure out a way to get this to work with the current version of Cashier? 
I too need this functionality, but had to achieve it by Not using cashier. 😞
