### ISSUE TITLE
Ability to customise customer check when creating an Invoice

### ISSUE THREAD

**Issue by u01jmg3** [laravel/cashier#862]
Hello,

I have an application which allows payment for effectively two different products; membership and registration fees. Unfortunately two different Stripe customer IDs were generated when someone bought both of these products. This has now been fixed but older transactions exist that were created in this manner.

Is there a way of customising this condition (I want to further check on the customer's email address)? Or a way of disabling this check? Without this I cannot provide access to invoices for both products.

- https://github.com/laravel/cashier/pull/801/files#diff-2e90a7f804b6b4d2e661f5d0bf080075R46

https://github.com/laravel/cashier/blob/1d2c7a701b659a2646dd211a7277eda06f35efbf/src/Invoice.php#L44-L48

**Comment by driesvints** [comment]
Unfortunately not. That would be solved with this issue: https://github.com/laravel/cashier/issues/545

**Comment by u01jmg3** [comment]
@driesvints: would it be a good idea to warn the user (or at least mention in the docs) that if they call `createAsStripeCustomer()` and a Stripe Customer ID already exists (`auth()->user()->stripe_id`) Cashier will *silently* overwrite what was previously there as per the code below:

https://github.com/laravel/cashier/blob/3c485612cfd22feaa550d99e78ade39f7c57b2f8/src/Billable.php#L741

Now that the new check is in place (`if ($owner->stripe_id !== $invoice->customer)`) any past invoices (if `createAsStripeCustomer()` was used) cannot be retrieved as the customer IDs won't match.

If a developer cares about displaying past invoices they should use `createOrGetStripeCustomer()` instead to re-use an existing Stripe Customer ID should it exist.

**Comment by driesvints** [comment]
Actually, the problem here is that the `createAsStripeCustomer` method shouldn't be callable when a stripe_id is already set. I'll re-open this and try to fix this by throwing an exception if it's already set.

**Comment by u01jmg3** [comment]
My only worry with throwing an exception at the point a `stripe_id` is already set and `createAsStripeCustomer()` is called relates to the following scenario.

When a customer makes their first ever transaction it is perfectly acceptable for a developer to use `createAsStripeCustomer()`. However, it's only when a customer makes a subsequent transaction that this new exception will be thrown when an existing `stripe_id` is found. This means a developer could have code in production that may only throw an exception if a customer makes more than one transaction.

Perhaps advocating the use of `createOrGetStripeCustomer()` would be a good idea too?

**Comment by driesvints** [comment]
@u01jmg3 in that scenario it's not wanted to constantly call `createAsStripeCustomer` for every transaction you make as you'll end up with numerous customers in Stripe which can't be traced back to that one user anymore. It's probably a bug in their app then.

I indeed now notice that `createOrGetStripeCustomer` isn't documented. I'll get that fixed as well. 

Thanks for reporting this btw 👍

**Comment by u01jmg3** [comment]
> _as you'll end up with numerous customers in Stripe which can't be traced back to that one user anymore_

Exactly - not good

> _I indeed now notice that `createOrGetStripeCustomer` isn't documented. I'll get that fixed as well._

Perfect 😄
