### ISSUE TITLE
Cashier treats cancelled subscription as valid if the subscription is on trial.

### ISSUE THREAD

**Issue by iamsayantan** [laravel/cashier#864]
- Cashier Version: 10.5
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
The way cashier checks if the subscription is valid is by checking if the subscription is active or on trial or on grace period.
```
    /**
     * Determine if the subscription is active, on trial, or within its grace period.
     *
     * @return bool
     */
    public function valid()
    {
        return $this->active() || $this->onTrial() || $this->onGracePeriod();
    }
```

But if I cancel a subscription stripe only updates the `stripe_status` and `ends_at` fields.
```
    /**
     * Mark the subscription as cancelled.
     *
     * @return void
     */
    public function markAsCancelled()
    {
        $this->fill([
            'stripe_status' => StripeSubscription::STATUS_CANCELED,
            'ends_at' => Carbon::now(),
        ])->save();
    }
```
So if someone cancels the subscription while on trial, after cancellation the subscription is still treated as a valid subscription as `$this->onTrial()` is true. And if they try to cancel again, stripe throws error `No such subscription: sub_id`. Shouldn't `trial_ends_at` date be set to current timestamp when user cancels the subscription?

**Comment by driesvints** [comment]
That's correct. We allow customers to use the remaining trial period when they already cancel the subscription before it ended. If you explicitly want them not to you'll have to call `skipTrial` before cancelling the subscription (like in the `customer.deleted` webhook.

I'll send in a PR to the docs to make this more obvious.

**Comment by driesvints** [comment]
Actually come to think of it the `markAsCancelled` is only used internally. It's not documented. You should only use the `cancel` and `cancelNow` methods.

**Comment by EntroSolutions** [comment]
What is returned when the payment is failed or the user cancels his subscription in Stripe directly?
