### ISSUE TITLE
Stripe Checkout WebHooks

### ISSUE THREAD

**Issue by GigaMick** [laravel/cashier#890]
Hi I've looked through old issues and the last update I can find about Stripe Checkout is July 2019. Apologies if I've missed a more recent update.

Is there any indication of when Cashier will handle the new Stripe Checkout web hooks, eg the payment intent and the checkout succeeded web hooks?

Thanks for the amazing work on Cashier.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier/issues/637

Atm we're not actively planning on working on this ourselves but we're open to anyone who wants to pick up the original pr: https://github.com/laravel/cashier/pull/652
