### ISSUE TITLE
AsStripeSubscription update error in docs/method?

### ISSUE THREAD

**Issue by quantumwebco** [laravel/cashier#891]
- Cashier Version: 10.5
- Laravel Version: 6.2
- PHP Version: 7.4
- Database Driver & Version: mysql 8.x

### Description:
Trying to update the subscription to change the anchor date with a trial i.e. https://stripe.com/docs/billing/subscriptions/billing-cycle#api-trials

In the Cashier docs https://laravel.com/docs/6.x/billing#stripe-sdk it says you can get the underlying stripe subscription from the SDK by
```
$stripeSubscription = $subscription->asStripeSubscription();

$stripeSubscription->update(['application_fee_percent' => 5]);
```
However this results in an error ```urlencode() expects parameter 1 to be string, array given"``` because the first param of the update method is the subscription id.

Also the method is static so I'm getting an error saying it should be called with :: instead of ->

If you pass in the id of the subscription and call it statically it then gives the error ```No API key provided.  (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)``` 

I'm not sure what I'm doing wrong here? Why can I not just update the subscription? Do I need to initialise stripe manually?

### Steps To Reproduce:
Try and update the stripe subscription as mentioned in the docs

**Comment by quantumwebco** [comment]
Although I could just use the ```extendTrial()``` method!

**Comment by quantumwebco** [comment]
This seemed to work...
```
    $sub = Subscription::find(12);
    //    $sub->noProrate()->anchorBillingCycleOn($date);
    $subscription                     = $sub->asStripeSubscription();
    $subscription->proration_behavior = 'none';
    $subscription->trial_end          = $date->timestamp;
    $subscription->save();
```

**Comment by driesvints** [comment]
The method you're using belongs to the Stripe SDK. Please open up an issue on their repo if you're having problems with it: https://github.com/stripe/stripe-php

**Comment by quantumwebco** [comment]
@driesvints The Cashier docs are still wrong. What is suggested in the docs does not work.

**Comment by driesvints** [comment]
@quantumwebco ah I see what you mean. I'll get that fixed 👍

**Comment by quantumwebco** [comment]
@driesvints is it possible to add the ```proration_behaviour``` flag somehow? Because then we could just use ```extendTrial()```. Unfortunately the ```noProrata()``` method doesn't seem to set that and so there's no way to add trial to an existing subscription without refunding some which isn't always wanted. Thanks

**Comment by driesvints** [comment]
No plans for that atm sorry.

**Comment by quantumwebco** [comment]
@driesvints Isn't that what the ```noProrate()``` method should do anyway?

**Comment by quantumwebco** [comment]
@driesvints Why does ```noProrate()``` method not set ```proration_behaviour```  to ```false``` anyway? Surely that's very simple to implement? Will you accept a PR if I implement that?

**Comment by driesvints** [comment]
@quantumwebco we haven't implemented the new proration behavior yet.

**Comment by driesvints** [comment]
Made an issue to follow that up: https://github.com/laravel/cashier/issues/902

**Comment by Mike-Antipov** [comment]
> @quantumwebco ah I see what you mean. I'll get that fixed 👍

I've got the same error, the code in the Cashier docs at https://laravel.com/docs/6.x/billing
> $stripeSubscription = $subscription->asStripeSubscription();
$stripeSubscription->update($subscription->stripe_id, ['application_fee_percent' => 5]);

returns 

>No API key provided.  (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)".  You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.

How ca I fix it? I have the same setup as @quantumwebco

**Comment by quantumwebco** [comment]
@Mike-Antipov I think this should work
```
    $stripeSubscription = $subscription->asStripeSubscription();
    $stripeSubscription->application_fee_percent = 5;
    $stripeSubscription->save();
```

**Comment by Mike-Antipov** [comment]
> @Mike-Antipov I think this should work
> 
> ```
>     $stripeSubscription = $subscription->asStripeSubscription();
>     $stripeSubscription->application_fee_percent = 5;
>     $stripeSubscription->save();
> ```

It did, thanks a lot! I was wondering how to make the Cashier method to work anyway.
