### ISSUE TITLE
Update stripe/stripe-php to add support php 7.4

### ISSUE THREAD

**Issue by sbellver** [laravel/cashier#892]
- Cashier Version: 7.0.#
- Laravel Version: 5.6.#
- PHP Version: 7.4.1
- Database Driver & Version:

### Description:

Recently they add support to php 7.4.1: https://github.com/stripe/stripe-php/issues/896

### Steps To Reproduce:

Upgrade php to 7.4 and call any Stripe function

`Trying to access array offset on value of type int `

**Comment by driesvints** [comment]
Cashier already supports this version: https://github.com/laravel/cashier/blob/10.0/composer.json#L30

Just update your dependencies.

**Comment by ErickTucto** [comment]
That error is a feature of php 7.4
[Documentation PHP](https://www.php.net/manual/es/migration74.incompatible.php)
![image](https://user-images.githubusercontent.com/22831024/88071752-d9732d80-cb39-11ea-9c67-5431f69c4313.png)
