### ISSUE TITLE
How to use Multiple Cashier Models

### ISSUE THREAD

**Issue by petericebear** [laravel/cashier#894]
Hi,

I have an App\User and an App\Company Eloquent Model which can both have subscriptions.
A User can have a subscription for reading articles, a company can have an active subscription with its own.

Is that possible right now, maybe with some overwriting of the config.model in Cashier.php and Subscription.php?

Or a suggestion that can you give some Models to find the used relation of the subscription created:
CASHIER_MODEL=App\Company,App\User

When user_id is set, load App\User or when company_id is set that App\Company is being used for getting and setting the model? Or it could be a Polymorphic relation? And where the Billable Trait is being Added to the subscription the model can be retrieved by reversing the Polymorphic relation?

How someone can help me out in this use case.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by petericebear** [comment]
It is also a bit of feature request, to make the subscriptions not connected to a single Model.
Or are you working on that in the new release?

**Comment by driesvints** [comment]
Hey @petericebear, that seems to be a duplicate of https://github.com/laravel/cashier/issues/545

We're not working on that ourselves atm but are open to prs.
