### ISSUE TITLE
The payment attempt failed because of an invalid payment method.

### ISSUE THREAD

**Issue by sonichandni** [laravel/cashier#899]
- Cashier Version: 10.x
- Laravel Version: 7.x
- PHP Version: 7.2

### Description:
While crating new subscripn I am getting this:
`"message": "The payment attempt failed because of an invalid payment method.",
    "exception": "Laravel\\Cashier\\Exceptions\\PaymentFailure",
    "file": "/home/chandni/Chandni/Bacancy/dita/vendor/laravel/cashier/src/Exceptions/PaymentFailure.php",`

### Steps To Reproduce:
$user->createOrGetStripeCustomer();
$user->updateDefaultPaymentMethod($request->paymentIntent['paymentMethod']['id']);
         
 $user->newSubscription('main', $plan->stripe_plan)
            ->create($request->paymentIntent['paymentMethod']['id'], [
                'name' => $billing_details['name'],
                'description' => 'test description',
                'email' => $billing_details['email'],
                "address" => $billing_details['address']
            ]);`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
