### ISSUE TITLE
Extending Subscription Model

### ISSUE THREAD

**Issue by Cragstar** [laravel/cashier#913]
Extending the model is simple enough, when trying to save new subscriptions though there is a custom_subscription_id error on the subscription items table.

Any ideas on how to resolve this?

**Comment by driesvints** [comment]
Please fill out the issue template and add steps to reproduce.

**Comment by Cragstar** [comment]
Sorry I missed this.
Basically I followed the instructions here
https://www.underthecocotree.co.uk/blog/extend-larvels-cashier-to-use-our-own-subscription-model

When then using the package I received the error around custom_subscription_id doesn't exist

**Comment by driesvints** [comment]
Please ask on a support channel.
