### ISSUE TITLE
Increment Quantity on MultiPlan

### ISSUE THREAD

**Issue by Cragstar** [laravel/cashier#917]
- Cashier Version: #.#.# 11.0.0
- Laravel Version: #.#.# 7.5.1
- PHP Version: #.#.# 7.3.9
- Database Driver & Version: MySQL 5.7.26

### Description:
When using the following method to update the quantities on a specific plan on a subscription
$user->subscription('default')->incrementQuantity(5, 'chat-plan');
I receive the following error

`"This method requires a plan argument since the subscription has multiple plans."`

### Steps To Reproduce:

1. Create a function server side to increase the quantities of the plan (i.e additional users above the base number that comes with the main subscription)
**Condensed version of the code**
`$type = Subscription::where('business_id', $userID)->firstOrFail();`
`$subscribe = $user->subscription($type->name)->incrementQuantity(1, 'plan_NUMBERISHERE');`

2. Call this function via the web interface
3. Laravel return the error stated above

You can see I am supplying a plan number to the method.

**Comment by driesvints** [comment]
I see the issue and I'll fix it. Thanks for reporting!

**Comment by driesvints** [comment]
Fixed now in v11.2.0

**Comment by Cragstar** [comment]
With a subscription item this only changes the quantity to the value passed in the increment and not by the number that is passed.
$user->subscription('default')->incrementQuantity(5, 'chat-plan');
Will change the quantity to 5 and not from say 2 -> 7 which an increment of 5 would do?

**Comment by driesvints** [comment]
You're right and good that you spotted this. I'll tackle this today 👍
