### ISSUE TITLE
noProrate() not working while updating quantity of a multiplan item

### ISSUE THREAD

**Issue by rambo666** [laravel/cashier#923]
- Cashier Version: 11.2.1
- Laravel Version: 6.18.10
- PHP Version: 7.2

### Description:
While I update a plan quantity belonging to a multiplan subscriptin. Putting noProrate does not work. After I went to the stripe I can still see remaining time of quantity being invoiced. 

I used the following code to update quantity for my plan
`$user->subscription('default')->noProrate()->updateQuantity($qty,$subscriptionPlan)`

Even though I used noProrate() the invoice on stripe was still prorating and showing remaining time of quantity on the invoice. 

### Steps To Reproduce:
Apply no prorate while updating quantity on stripe while there are multiplans on a subscription.

**Comment by driesvints** [comment]
Thanks, I also see the problem here. You've been very helpful so far, thanks!

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/cashier/pull/924
