### ISSUE TITLE
Multiple Plan Subscriptions with same Plan ID

### ISSUE THREAD

**Issue by tlaverdure** [laravel/cashier#927]
Thanks for adding multiple plans in 11.0! 

I'm currently working on a situation where a subscription needs to be created with multiple plans that have the same ID but different quantities. This will be specifically used to allow one entity to manage the subscriptions of other entities. For example, an enterprise that pays for the subscriptions of different teams within their organization. Each team has their own plan with different quantities and the quantity determines the tiered pricing for that specific plan as expressed in the [Stripe docs](https://stripe.com/docs/billing/subscriptions/multiplan).

**The goals are:**
1. Create a subscription with multiple plans that have different quantities.
2. Produce a single invoice and billing cycle for all the plans.
3. Reduce costs in charging subscriptions

While multiple plans can be added to the subscription builder, the plan id is used as the key which will only allow one unique plan item:
```php
    /**
     * Set a plan on the subscription builder.
     *
     * @param  string  $plan
     * @param  int  $quantity
     * @return $this
     */
    public function plan($plan, $quantity = 1)
    {
        $this->items[$plan] = [
            'plan' => $plan,
            'quantity' => $quantity,
            'tax_rates' => $this->getPlanTaxRatesForPayload($plan),
        ];

        return $this;
    }
```

Would it be possible to add method that allows an un-keyed array of items to be set on the subscription builder?
```php
    /**
     * Set the plans on the subscription builder.
     *
     * @param  array  $plans
     * @return $this
     */
    public function plans($plans)
    {
        $this->items = $plans;

        return $this;
    }
```

**What implications will this have in updating subscriptions items in the database?**
I think when a subscription is updated, we would need to match items based on the `stripe_id` and not the `stripe_plan`. Not sure if there is anything else that I'm missing.

https://github.com/laravel/cashier/blob/5d2f4b5905fa6987e27919e2fd7daed633121c52/src/Http/Controllers/WebhookController.php#L112-L128

**Comment by driesvints** [comment]
Stripe doesn't supports multiple plans with the same id on one subscription.

**Comment by tlaverdure** [comment]
Yeah it appears so. The docs made it seem so. Looks like I need to tackle this from another direction then. Thanks!

**Comment by stones** [comment]
Sorry for being late to the party, but the docs seem to say that you can pass a quantity:

> Provide the plan and, optionally, a quantity (when using a value other than 1), for each plan:

https://stripe.com/docs/billing/subscriptions/multiplan

Are the docs incorrect?
