### ISSUE TITLE
Error with multiples subscriptions

### ISSUE THREAD

**Issue by JavierTibi** [laravel/cashier#931]
- Cashier Version: 12.0
- Laravel Version: 6.0.4
- PHP Version: 7.2
- Database Driver & Version: MySQ

### Description:

When trying to make a multiple subscription in a "Recurring quantity" plan and in a "Metered usage" plan, through the addPlan method, I get the following error "Class name must be a valid object or a string".

I appreciate your help

### Steps To Reproduce:

`$subscription = $request->user()->newSubscription('main', 'plan_HBjI2Ap3W7uCeK')->create($request->paymentMethod);

$subscription->addPlan('monthly_employee_plan', 5);`

**Comment by driesvints** [comment]
We don't support metered billing yet. Please see https://github.com/laravel/cashier/issues/555
