### ISSUE TITLE
defaultPaymentMethod() does not return the customer's default payment method

### ISSUE THREAD

**Issue by connecteev** [laravel/cashier#933]
- Cashier Version: #.#.#^11.2
- Laravel Version: #.#.# 7.7.1
- PHP Version: #.#.# 7.4.5
- Database Driver & Version:MySQL

### Steps To Reproduce:

I've been looking high and low for a function to get the default payment method, but couldnt find one. I stumbled upon $User->defaultPaymentMethod() by reading through the source code....unfortunately it doesn't return the user's default payment method, eventhough I have it set in stripe. How can I get the defaultPaymentMethod?

## Update:
I found a roundabout way to do it after looking through the cashier source:
```
$stripeCustomer = $loggedinUser->createOrGetStripeCustomer();
$default_payment_method = $stripeCustomer->invoice_settings->default_payment_method;
return response()->json($default_payment_method);
```
which returns a value like ```"pm_0GhRNwEXGF9cqh5pMGhu331p"```

Unless I'm missing something, there seems to be a bug: calling $loggedinUser->defaultPaymentMethod()  doesn't return the same value.

**Comment by driesvints** [comment]
Why wouldn't this be a default payment method? Let's continue this discussion on Discord.

**Comment by slower1337** [comment]
Noooooo....
