### ISSUE TITLE
Cards vs Payment Methods

### ISSUE THREAD

**Issue by connecteev** [laravel/cashier#934]
I am not sure if this is a feature request, missing functionality or actually is a bug...but listing my thoughts below.

Here's what I've found from using Cashier 
Stripe exposes APIs for creating "cards"(which it considers to be ONE type of payment method).
- https://stripe.com/docs/api/cards/object
- https://stripe.com/docs/api/payment_methods/object

1. The Cashier APIs only expose [Payment Methods](https://laravel.com/docs/7.x/billing#payment-methods), not cards. It would be nice to expose the Cards CRUD APIs in Cashier, as well.
2. When you go to the Stripe Dashboard, and from within a customer object, you manually add a card, it creates a card, like so:
```
        {
            "id": "card_0GhSbBDXGF9cqh5pRFYCQcg6",
            "brand": "visa",
            "last_four": "4242",
            "exp_month": 5,
            "exp_year": 2055
        }
```

If you use the [addPaymentMethod() API](https://laravel.com/docs/7.x/billing#adding-payment-methods), it creates a payment method object that looks like this:
```
        {
            "id": "pm_0GhRNwDXGF9cqh5pMGhuPY1p",
            "brand": "visa",
            "last_four": "4242",
            "exp_month": 2,
            "exp_year": 2022
        }
```

This is weird and confusing and is also the cause for the issue https://github.com/laravel/cashier/issues/933

Even after a lot of trial and error and research, I'm not sure:
1. Should we be creating cards first, then payment methods, and then tying the card to the Payment Method?
2. Why does $user->defaultPaymentMethod() only return values for cards having ids like card_0GhSbBDXGF9cqh5pRFYCQcg6, and NOT payment method objects with IDs like pm_0GhRNwDXGF9cqh5pMGhuPY1p
?
3. How do you get the default payment method using Cashier? What is the use case for 
- $user->defaultPaymentMethod()
vs
- $user->asStripeCustomer()->invoice_settings->default_payment_method

I'd like to suggest 2 things:
- At a minimum, it would be helpful to get answers to the 3 questions above. 
- If it makes sense to do so, it might be helpful to also expose the Cards CRUD APIs in Cashier.

**Comment by driesvints** [comment]
> Should we be creating cards first, then payment methods, and then tying the card to the Payment Method?

Payment methods / payment intents are Stripe's new and current recommended way of providing ways in which customers can pay. The old card / sources api is the old deprecated and will be removed at some point in the future. See https://stripe.com/docs/sources/cards

> Use of this API is no longer recommended. We recommend adopting the Payment Intents API. This new integration lets you benefit from Dynamic 3D Secure and helps you avoid an increase in declined payments due to Strong Customer Authentication regulation in Europe.

> Why does $user->defaultPaymentMethod() only return values for cards having ids like card_0GhSbBDXGF9cqh5pRFYCQcg6, and NOT payment method objects with IDs like pm_0GhRNwDXGF9cqh5pMGhuPY1p

I think you mean the other way around? Atm this method returns objects with `pm_` ids.

> How do you get the default payment method using Cashier? What is the use case for

Exactly the method you gave: `$user->defaultPaymentMethod()`.

Let's continue this discussion on Discord as the issue tracker here isn't a support channel (see the issue templates).

**Comment by connecteev** [comment]
@driesvints sounds good, and sorry for the noise. I do still see the discrepancy between $user->defaultPaymentMethod() and $user->asStripeCustomer()->invoice_settings->default_payment_method (as detailed above). Let's continue the discussion on Discord
