### ISSUE TITLE
invoices(), upcomingInvoice() and invoicesIncludingPending() return no data

### ISSUE THREAD

**Issue by connecteev** [laravel/cashier#938]
- Cashier Version: #.#.# 11
- Laravel Version: #.#.# 7.x
- PHP Version: #.#.# 7.4.5
- Database Driver & Version: MySQL 8

### Description:
Even though $loggedinUser is a Billable model and belongs to a user with an active (monthly) plan, calling invoicesIncludingPending(), upcomingInvoice() or invoices() on it returns no data.
```
            $loggedinUser = auth()->user();
            $upcomingInvoice = $loggedinUser->invoicesIncludingPending();
            $upcomingInvoice = $loggedinUser->upcomingInvoice();
            $upcomingInvoice = $loggedinUser->invoices();
            return response([
                "upcoming_invoice" => $upcomingInvoice,
            ], Response::HTTP_OK);
```

This is what I get back:
```
{
    "upcoming_invoice": [
        {}
    ]
}
```
Note that on the Stripe dashboard I do see an upcoming invoice 1 month from now: https://www.webpagescreenshot.info/#v2=572v2l6nG

What I am trying to do is get the amount the user will be charged at the next billing cycle (note that this may not be the same as the subscription plan's price the user is on - they may have a credit applied to their account, etc)

**Comment by connecteev** [comment]
This is what I am trying to get done without relying on the Stripe library:

```
\Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
$customerId = $loggedinUser->asStripeCustomer()->id;
$upcomingInvoice = \Stripe\Invoice::upcoming(["customer" => $customerId]); // from https://stripe.com/docs/api/invoices/upcoming
return ['amount_due' => $upcomingInvoice->amount_due, 'invoice' => $upcomingInvoice];

```

**Comment by driesvints** [comment]
I get all the invoices back. You're confusing the `Invoice` objects to be serializable to json or arrayable (which they aren't). You can't simply return them from a route or a response.

**Comment by connecteev** [comment]
@driesvints thanks..Im not following the use-case. What is the right way to do it, if different from the code snippet?

**Comment by driesvints** [comment]
The right way to do what?

**Comment by connecteev** [comment]
@driesvints well I am following the documentation - what do you see wrong here? 

```
            $loggedinUser = auth()->user();
            $upcomingInvoice = $loggedinUser->invoicesIncludingPending();
            $upcomingInvoice = $loggedinUser->upcomingInvoice();
            $upcomingInvoice = $loggedinUser->invoices();
            return response([
                "upcoming_invoice" => $upcomingInvoice,
            ], Response::HTTP_OK);
```

**Comment by driesvints** [comment]
I've already explained above. Cashier's invoice object doesn't implements arrayable. You need the map the values you want to expose yourself.

**Comment by driesvints** [comment]
Where do you see this in the docs?

**Comment by connecteev** [comment]
@driesvints you are right, it's not exactly in the docs. I am going to try this again and report back..thanks.
