### ISSUE TITLE
Invoice - Missing tax information

### ISSUE THREAD

**Issue by AnalyzeMe** [laravel/cashier#945]
- Cashier Version: 11
- Laravel Version: 7.12
- PHP Version: 7.2
- Database Driver & Version: Mysql

### Description:

I have configured tax rates in Stripe and the subscription is correctly generated (with the reverse charge) when i download the invoice from the stripe dashboard i can see on the invoice "Tax to be paid on reverse charge basis".

The problem is when i download the invoice in laravel cashier 11 the "Tax to be paid on reverse charge basis" is not shown, i also think it's a bit strange that the first check is about, if the invoice has tax, if it's set to reverse it whould never have tax on it.

What am i missing here?

### Steps To Reproduce:

Just add reverse to customer in cashier and download invoice from cashier.

### Code with issue

```
@if ($invoice->hasTax())
                        @unless ($invoice->isNotTaxExempt())
                            <tr>
                                <td colspan="{{ $invoice->hasTax() ? 3 : 2 }}" style="text-align: right;">
                                    @if ($invoice->isTaxExempt())
                                        Tax is exempted
                                    @else
                                        Tax to be paid on reverse charge basis
                                    @endif
                                </td>
                                <td></td>
                            </tr>
                        @else
                            @foreach ($invoice->taxes() as $tax)
                                <tr>
                                    <td colspan="3" style="text-align: right;">
                                        {{ $tax->display_name }} {{ $tax->jurisdiction ? ' - '.$tax->jurisdiction : '' }}
                                        ({{ $tax->percentage }}%{{ $tax->isInclusive() ? ' incl.' : '' }})
                                    </td>
                                    <td>{{ $tax->amount() }}</td>
                                </tr>
                            @endforeach
                        @endunless
                    @endif
```

I think is wrong to check @if ($invoice->hasTax()) when the customer has "reverse" it whould never contain any tax.

Screenshot attached.
![Invoice_Stripe_Cashier](https://user-images.githubusercontent.com/65530423/82672741-093cac80-9c41-11ea-8f40-51bc6f207d09.jpeg)

Is this intended or is a bug? Thanks in advance for any clarification!

**Comment by driesvints** [comment]
Hey @AnalyzeMe, thanks for posting the screenshots. I think you're indeed correct that the first if check isn't needed. Feel free to send in a PR to remove them or I'll take care of it later today.

**Comment by AnalyzeMe** [comment]
I'm not sure how to send in a pull request.

Do u comment here or where can i see when you have changed the code? :)

**Comment by driesvints** [comment]
I'll let ya know.

**Comment by driesvints** [comment]
Didn't get around to this today. I'll tackle this on Monday and we'll release a fix on Tuesday.

**Comment by driesvints** [comment]
Fixed in https://github.com/laravel/cashier/pull/946
