### ISSUE TITLE
Multiple allowed hosts for VerifyRedirectUrl middleware

### ISSUE THREAD

**Issue by Zhythero** [laravel/cashier#951]
Hi,

My frontend and api(laravel) apps are hosted differently but I'm still utilizing the payment page of Cashier.

However, the payment page's redirect param only allows hosts from the laravel app.
Would be nice to have a configuration for this where we could allow multiple hosts, in my instance, my front-end app.

Maybe add a `config/cashier.php`?

**Comment by driesvints** [comment]
You can overwrite the `PaymentController`, use `Cashier::ignoreRoutes()` and publish and overwrite the routes if you want this.
