### ISSUE TITLE
invoiceItems() returning null while generating Invoice pdf.

### ISSUE THREAD

**Issue by rambo666** [laravel/cashier#955]
- Cashier Version: 11.2.1
- Laravel Version: 6.18.10
- PHP Version: 7.2

### Description:
I tried to produce an invoice pdf using your code as below.

`return $user->downloadInvoice($invoice_id, [
            'vendor'  => 'Company Name',
            'product' => 'Monthly Subscription or Something',
        ]);
`

Then I did 
`dd($invoice->invoiceItems());` 
on pdf view

It returns null. 

I tried to do a foreach of $invoice->invoiceItems() and there are no data. 

**I guess it is conflicting with multiplan subscription** Really not sure If I am doing it right or this is a bug.

**Comment by driesvints** [comment]
`invoiceItems` is only for extra line items that were applied to an invoice. 

`$invoice->subscriptions()` is for the subscriptions themselves. Is that what you need?

https://github.com/laravel/cashier/blob/11.x/resources/views/receipt.blade.php#L154-L181

**Comment by rambo666** [comment]
I think so. Not sure what invoiceItems() really does.

**Comment by driesvints** [comment]
It's when you add extra items to the invoice. Like with the `tab` method`.

**Comment by rambo666** [comment]
Ahh ok yes I got it. Thanks.
