### ISSUE TITLE
Cashier throws error “A parameter provided in the URL (payment_method) was repeated as a GET or POST parameter.” while adding payment method

### ISSUE THREAD

**Issue by poornimasudha** [laravel/cashier#957]
I am using cashier for stripe in laravel 7, getting this error while adding payment method.
" A parameter provided in the URL (payment_method) was repeated as a GET or POST parameter. You can only provide this information as a portion of the URL." 
I am passing payment intent to the blade like this, 
'intent' => $user->createSetupIntent() 
In js,

cardButton.addEventListener('click', async (e) => {
    e.preventDefault();
    const { setupIntent, error } = await stripe.confirmCardSetup(
        clientSecret, {
            payment_method: {
                card: cardElement,
                billing_details: { name: cardHolderName.value }
            }
        }
    );
 if (error) {

        // Display "error.message" to the user...
    } else {
        send('save', false, {
            data: {
                payment_method: setupIntent
            }

        });
        // The card has been verified successfully...
    }
});

then adding

 $paymentMethod=$request['payment_method'];
        $user->updateDefaultPaymentMethod($paymentMethod);
what is the meaning of this error?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by poornimasudha** [comment]
Thanks for the reply.I was not sure whether it was issue with cashier  or not. I used the default function from cashier and the error was a stripe Exception.I will ask help in supporting channel as you suggested:)

**Comment by poornimasudha** [comment]
It was a fault from my side,I passed complete setup intent instead of payment method in updateDefaultPaymentMethod.
