### ISSUE TITLE
swapAndInvoice function not writing to database

### ISSUE THREAD

**Issue by sunnyjayjay** [laravel/cashier#962]
- Cashier Version: 12.0.0
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version: mySql 5.7.19

### Description:
using swapAndInvoice to change plans immediately the original plan remains in the subscriptions table and there is no new entry for the new plan

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by sunnyjayjay** [comment]
> Heya, thanks for reporting.
> 
> I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets.
> 
> Thanks!

I am not sure how much you need. Bear in mind everything else is working (eg newSubscription()).

Here is the failing line:

    $tenant->subscription($currentPlan)->swapAndInvoice($newPlanId);

In that statement $tenant is the model for Cashier, $currentPlan is a string with a valid Stripe Product/Plan name, and $newPlanId is the Stripe ID for the new plan. 

Everything works fine in Stripe itself - I can see the customer plan changed successfully and the correct amount of money taken. However in the "subscriptions" table, the customer still has ONLY the old plan. nothing is changed at all. 

If you need more do please let me know.

Best wishes, Jonathan

**Comment by driesvints** [comment]
We'll still need much more info here. We're currently testing this scenario in our test suite. Please provide detailed steps on how to reproduce this in the most minimal example you can think of.

**Comment by sunnyjayjay** [comment]
Steps to reproduce:


   1. Create 2 Stripe plans, preferably in Stripe Test Mode. Each should
   have a different name and price.
   2. Subscribe a user to one of the plans (a simple form with normal
   Stripe payment stuff).
   3. After checking that the subscription is all fine in your
   subscriptions table and in Stripe, change the user plan to the other one
   using swapAndInvoice(). In my case the Stripe side is fine but the
   subscriptions table is untouched.

**Comment by driesvints** [comment]
@sunnyjayjay just tried your steps and everything works just fine for me. Please try a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by sunnyjayjay** [comment]
> @sunnyjayjay just tried your steps and everything works just fine for me. Please try a support channel:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> Thanks!

@driesvints Would you be able to share the code you used to test this please?

**Comment by sunnyjayjay** [comment]
I think I am getting to the issue now. My description of the problem was not actually correct, sorry, I have only just discovered this. In the "subscriptions" table there is a field call "name" which is for the name of the subscribed plan. There is also a field called "stripe_plan" which is for the ID of the subscribed plan. The latter field is indeed being correctly updated by Cashier, but the "name" field is not touched. I can see this in the code "Subscription.php" line 581:

    $this->fill([
            'stripe_status' => $stripeSubscription->status,
            'stripe_plan' => $stripeSubscription->plan ? $stripeSubscription->plan->id : null,
            'quantity' => $stripeSubscription->quantity,
            'ends_at' => null,
        ])->save();

The "name" field is not referenced. Is that something you can change or do I need to catch it myself? In my previous version of Cashier it was handled automatically.

**Comment by driesvints** [comment]
How does `$tenant->subscription($currentPlan)->swapAndInvoice($newPlanId);` update the name column? You're not passing any new name.

**Comment by sunnyjayjay** [comment]
OK, so what's the right way to do this? The call doesn't allow for the name to be included as far as I can see and the code I referenced would not do anything with it anyway. Before upgrading (I think I was on 6.x) the swap() function took care of updating the name.

**Comment by driesvints** [comment]
@sunnyjayjay no, it never did.

```php
$subscription = $tenant->subscription($currentPlan);

$subscription->swapAndInvoice($newPlanId);

$subscription->name = 'new-name';
$subscription->save();
```

**Comment by sunnyjayjay** [comment]
OK, sorry. Thanks for the answer.
