### ISSUE TITLE
Call to undefined method Laravel\Lumen\Routing\Router::name() 

### ISSUE THREAD

**Issue by paunin** [laravel/cashier#964]
- Cashier Version: 12.0.1
- **Lumen** Version: ^7.2
- PHP Version: 7.4
- Database Driver & Version: Postgres

### Description:

getting an error on publishing the resources...but think it does not matter.
`Call to undefined method Laravel\Lumen\Routing\Router::name() in /var/www/application/vendor/laravel/cashier/routes/web.php`

**Comment by paunin** [comment]
I understand that you might not support Lumen but is there actually any value in named routes?

**Comment by paunin** [comment]
Dumb hack here is to create new router with stub for `name()`
```
namespace App\Routing;

class Router extends \Laravel\Lumen\Routing\Router
{
    public function name(string $nameForRoute)
    {
    }
}
```
and use it in `app/bootstrap/app.php`
```
$app = new Laravel\Lumen\Application(
    dirname(__DIR__)
);

$app->router = new Router($app);
```

**Comment by driesvints** [comment]
Please see the docs. Cashier isnt supported by lumen. Please use Laravel if you need cashier.
