### ISSUE TITLE
Unrecognized request URL (GET: /v1/customers/)

### ISSUE THREAD

**Issue by iFeras93** [laravel/cashier#965]
- Cashier Version: 12.0.1
- Laravel Version: 7.17.2
- PHP Version: 7.4.6
- Database Driver & Version: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6

### Description:
I have a problem with when making subscriptions on my app.

![image](https://user-images.githubusercontent.com/6824682/85956939-b964aa00-b991-11ea-98f6-ae5a2ffa2bf4.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
