### ISSUE TITLE
Is there any way to use same payment method for multiple user subscription in laravel cashier?

### ISSUE THREAD

**Issue by poornimasudha** [laravel/cashier#968]
In my laravel project I have one super admin and many users. Super admin need to pay the subscription amount of each user using cashier.

    

- I tried to subscribe for each users using the payment method of super admin it doesn't support.
- I tried to add payment method of super admin to all the users it doesn't support.
-I am trying to buy multiple quantities product in super admin account using $user->subscription('default')->incrementQuantity(5); but I don't know how to allocate this purchased quantity to another user according to cashier concept.

Or is there any other method to use same payment method for multiple user subscription(except simple charge)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by poornimasudha** [comment]
But there is no way to do this currently until we customize. So I think this is possibility of enhancement
